//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the UI.Windows Flow Addon.
//     You may simply edit this file to setup your behavior.
// </auto-generated>
// <example>
// Pass parameters here
// Example: WindowSystem.Show<T>(true, "some text", this.transform);
// 
// 	public void OnParametersPass(bool anyBool, string text, Transform transform) {
// 	}
// </example>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI.Windows;
using UnityEngine.UI.Windows.Components;

namespace ExampleProject.UI.Other.MainLoader {

	public class MainLoaderScreen : MainLoaderScreenBase {

		private ButtonWithTextComponent button;

		public override void OnInit() {

			base.OnInit();

			this.FlowBackground();

			this.GetLayoutComponent(out this.button);
			this.button.SetText("Open Next Screen");
			this.button.SetCallback(() => {

				this.FlowGlobalMap();

			});

		}

	}

}