//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the UI.Windows Flow Addon.
//     You may not edit this file because of it's auto-generated by FlowCompiler.
//     See more: https://github.com/chromealex/Unity3d.UI.Windows
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI.Windows;
using UnityEngine.UI.Windows.Types;

namespace ExampleProject.UI.Other.MainLoader {

	public class MainLoaderScreenBase : LayoutWindowType {
		
		/// <summary>
		/// Flows to the GlobalMap.
		/// Full Name: ExampleProject.UI.Menu.GlobalMap.GlobalMapScreen
		/// </summary>
		/// <returns>GlobalMap</returns>
		public virtual ExampleProject.UI.Menu.GlobalMap.GlobalMapScreen FlowGlobalMap(params object[] parameters) {
			
			var instance = WindowSystem.Show<ExampleProject.UI.Menu.GlobalMap.GlobalMapScreen>(parameters);
			instance.SetFunctionIterationIndex(this.GetFunctionIterationIndex());
			
			return instance;
			
		}
				
		/// <summary>
		/// Flows to the Background.
		/// Full Name: ExampleProject.UI.Other.Background.BackgroundScreen
		/// </summary>
		/// <returns>Background</returns>
		public virtual ExampleProject.UI.Other.Background.BackgroundScreen FlowBackground(params object[] parameters) {
			
			var instance = WindowSystem.Show<ExampleProject.UI.Other.Background.BackgroundScreen>(parameters);
			instance.SetFunctionIterationIndex(this.GetFunctionIterationIndex());
			
			return instance;
			
		}
		
	}

}