//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the UI.Windows Flow Addon.
//     You may simply edit this file to setup your behavior.
//     See more: https://github.com/chromealex/Unity3d.UI.Windows
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI.Windows;
using UnityEngine.UI.Windows.Components;

namespace ExampleProject.UI.Menu.MainMenu {

	public class MainMenuScreen : MainMenuScreenBase {

		private ButtonComponent button;

		public override void OnInit() {

			base.OnInit();

			this.GetLayoutComponent(out this.button);
			this.button.SetCallback(() => {

				this.FlowHideFunctionLoader((routes) => {
					
					WindowSystem.HideAllAndClean(except: (WindowBase)null, callback: () => {

						routes.FlowGameplayView();

					});

				});

			});

		}



	}

}