//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the UI.Windows Flow Addon.
//
//     You may simply edit this file to setup your behavior.
// </auto-generated>
// <example>
// Pass parameters here
// Example: WindowSystem.Show<T>(true, "some text", this.transform);
// 
// 	public void OnParametersPass(bool anyBool, string text, Transform transform) {
// 	}
// </example>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI.Windows;

namespace MW2.UI.Common {

	public class SettingsScreen : LayoutWindowType {

		public override void OnInit() {
		}

	}

}