using UnityEngine;
using System.Collections;

public class MacrosInjectionTest2 : MonoBehaviour {

	// Use this for initialization
	void Start () {
	
	#region macros TEST2
	/*
	 * This code is auto-generated by Macros Module
	 * Do not change anything
	 */
	var a = "Source Test 2";
	Debug.Log(a);
	#endregion

	}
	
	// Update is called once per frame
	void Update () {
	
	}
}
