using UnityEngine;
using System.Collections;

public class MacrosInjectionTest2 : MonoBehaviour {

	// Use this for initialization
	void Start () {
	
	#region macros TEST2 (aa:"test")

	/*
	 * This code is auto-generated by Macros Module
	 * Do not change anything
	 */
	var a = "Source Test 2" + "test";
	Debug.Log(a);
	#endregion
	#region macros TEST3 (aa:"test",bb:"bb-test")

	/*
	 * This code is auto-generated by Macros Module
	 * Do not change anything
	 */
	var b = "Source Test 3" + "test";
	Debug.Log(b);
	Debug.Log("bb-test");
	#endregion
	#region macros TEST4 
	/*
	 * This code is auto-generated by Macros Module
	 * Do not change anything
	 */
	var c = "Source Test 4";
	Debug.Log(c);
	#endregion
	#region macros TEST5 (x:abc,code:var abc="test";)

	/*
	 * This code is auto-generated by Macros Module
	 * Do not change anything
	 */
	var abc="test";
	Debug.Log(abc);
	#endregion
	}
	
	// Update is called once per frame
	void Update () {
	
	}
}
