//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the UI.Windows Flow Addon.
//     You may simply edit this file to setup your behavior.
//     See more: https://github.com/chromealex/Unity3d.UI.Windows
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI.Windows;
using UnityEngine.UI.Windows.Components;

namespace ExampleProject.UI.Gameplay.GameplayHUD {

	public class GameplayHUDScreen : GameplayHUDScreenBase {

		private GameplayView.GameplayViewScreen gameplay;

		public void OnParametersPass(GameplayView.GameplayViewScreen gameplay) {

			this.gameplay = gameplay;

		}

		public override void OnInit() {

			base.OnInit();
			
			this.GetLayoutComponent<ButtonComponent>(LayoutTag.Tag2).SetCallback(() => { this.SetColor(Color.black); });
			this.GetLayoutComponent<ButtonComponent>(LayoutTag.Tag3).SetCallback(() => { this.SetColor(Color.white); });
			this.GetLayoutComponent<ButtonComponent>(LayoutTag.Tag4).SetCallback(() => { this.Quit(); });

		}

		private void SetColor(Color color) {
			
			this.gameplay.SetColor(color);

		}

		private void Quit() {

			this.gameplay.Quit();

		}

	}

}