//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the UI.Windows Flow Addon.
//
//     You may simply edit this file to setup your behavior.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI.Windows;

namespace ExampleProject.UI.Menu.GameTypeChooser {

	public class GameTypeChooserScreenBase : LayoutWindowType {

		//------------------------------------------------------------------------------
		// <auto-generated>
		//     This code was generated by the UI.Windows Flow Addon.
		//
		//     You may simply edit this file to setup your behavior.
		// </auto-generated>
		//------------------------------------------------------------------------------
		public virtual ExampleProject.UI.Shop.Menu.Shop.ShopScreenBase FlowShop() {
			
			return WindowSystem.Show<ExampleProject.UI.Shop.Menu.Shop.ShopScreenBase>();
			
		}		//------------------------------------------------------------------------------
		// <auto-generated>
		//     This code was generated by the UI.Windows Flow Addon.
		//
		//     You may simply edit this file to setup your behavior.
		// </auto-generated>
		//------------------------------------------------------------------------------
		public virtual ExampleProject.UI.GameplayLoader.GameplayLoaderScreenBase FlowGameplayLoader() {
			
			return WindowSystem.Show<ExampleProject.UI.GameplayLoader.GameplayLoaderScreenBase>();
			
		}
		
	}

}