//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the UI.Windows Flow Addon.
//     You may simply edit this file to setup your behavior.
//     See more: https://github.com/chromealex/Unity3d.UI.Windows
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI.Windows;
using UnityEngine.UI.Windows.Components;

namespace ExampleProject.UI.Other.Error {

	public class ErrorScreen : ErrorScreenBase {

		private ButtonComponent button;

		public override void OnInit() {

			base.OnInit();

			this.GetLayoutComponent(out this.button);

			this.button.SetCallback(() => {

				WindowSystem.HideAllAndClean(except: (WindowBase)null, callback: () => {

					WindowSystem.ShowRoot();

				}, forceAll: true, immediately: true);

			});

		}

	}

}