//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the UI.Windows Flow Addon.
//     You may simply edit this file to setup your behavior.
//     See more: https://github.com/chromealex/Unity3d.UI.Windows
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI.Windows;
using UnityEngine.UI.Windows.Components;
using ExampleProject.UI.Gameplay.GameplayView;

namespace ExampleProject.UI.Menu.MainMenu {

	public class MainMenuScreen : MainMenuScreenBase {

		public override void OnInit() {

			base.OnInit();

			this.GetLayoutComponent<ButtonComponent>(LayoutTag.Tag5).SetCallback(() => {

				this.Play(Side.White);

			});

			this.GetLayoutComponent<ButtonComponent>(LayoutTag.Tag6).SetCallback(() => {

				this.Play(Side.Black);

			});

		}

		public void Play(Side side) {

			this.FlowHideFunctionLoader((routes) => {

				#if !NO_WS_CLEANUP
				WindowSystem.HideAllAndClean(except: (WindowBase)null, callback: () => {
				#else
				WindowSystem.HideAll(except: (WindowBase)null, callback: () => {
				#endif
					
					routes.FlowGameplayView(side);

				}, forceAll: false, immediately: true);

			});

		}

	}

}