//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the UI.Windows Flow Addon.
//     You may simply edit this file to setup your behavior.
//     See more: https://github.com/chromealex/Unity3d.UI.Windows
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI.Windows;
using UnityEngine.UI.Windows.Components;

namespace ExampleProject.UI.Gameplay.EndGame {

	public class EndGameScreen : EndGameScreenBase {
		
		public override void OnInit() {
			
			base.OnInit();
			
			this.GetLayoutComponent<ButtonComponent>().SetCallback(() => {

				this.FlowHideFunctionLoader((routes) => {

					WindowSystem.HideAllAndClean(except: this, callback: () => {

						routes.FlowDefault();

					});

				});

			});

		}

	}

}