//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the UI.Windows Flow Addon.
//     You may not edit this file because of it's auto-generated by FlowCompiler.
//     See more: https://github.com/chromealex/Unity3d.UI.Windows
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI.Windows;
using UnityEngine.UI.Windows.Types;

namespace ExampleProject.UI.Other.MenuLoader {

	public class MenuLoaderScreenBase : LayoutWindowType {
		
		/// <summary>
		/// Flows to the GlobalMap.
		/// Full Name: ExampleProject.UI.Menu.GlobalMap.GlobalMapScreen
		/// </summary>
		/// <returns>GlobalMap</returns>
		public virtual ExampleProject.UI.Menu.GlobalMap.GlobalMapScreen FlowGlobalMap(params object[] parameters) {
			
			return WindowSystem.Show<ExampleProject.UI.Menu.GlobalMap.GlobalMapScreen>(parameters);
			
		}
				
		/// <summary>
		/// Flows to the Default.
		/// </summary>
		/// <returns>Default</returns>
		public virtual void FlowDefault(params object[] parameters) {
			
			WindowSystem.ShowDefault(parameters);
			
		}
		
	}

}