//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the UI.Windows Flow Addon.
//     You may simply edit this file to setup your behavior.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI.Windows;
using UnityEngine.UI.Windows.Types;

namespace ExampleProject.UI.Gameplay.GameplayView {

	public class GameplayViewScreenBase : LayoutWindowType {
		
		/// <summary>
		/// Flows to the EndGame.
		/// Full Name: ExampleProject.UI.Gameplay.EndGame.EndGameScreen
		/// </summary>
		/// <returns>EndGame</returns>
		public virtual ExampleProject.UI.Gameplay.EndGame.EndGameScreen FlowEndGame(params object[] parameters) {
			
			return WindowSystem.Show<ExampleProject.UI.Gameplay.EndGame.EndGameScreen>(parameters);
			
		}
				
		/// <summary>
		/// Flows to the GameplayHUD.
		/// Full Name: ExampleProject.UI.Gameplay.GameplayHUD.GameplayHUDScreen
		/// </summary>
		/// <returns>GameplayHUD</returns>
		public virtual ExampleProject.UI.Gameplay.GameplayHUD.GameplayHUDScreen FlowGameplayHUD(params object[] parameters) {
			
			return WindowSystem.Show<ExampleProject.UI.Gameplay.GameplayHUD.GameplayHUDScreen>(parameters);
			
		}
		
	}

}