//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the UI.Windows Flow Addon.
//     You may simply edit this file to setup your behavior.
//     See more: https://github.com/chromealex/Unity3d.UI.Windows
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI.Windows;
using ExampleProject.Gameplay.GameplayView.Components;

namespace ExampleProject.UI.Gameplay.GameplayView {

	public class GameplayViewScreen : GameplayViewScreenBase {

		private GameplayComponent gameplayComponent;
		private GameplayHUD.GameplayHUDScreen hud;

		public override void OnInit() {

			base.OnInit();

			this.GetLayoutComponent(out this.gameplayComponent);

		}

		public override void OnShowBegin() {

			base.OnShowBegin();
			
			this.hud = this.FlowGameplayHUD(this);
			this.SetColor(Color.white);

		}

		public void SetColor(Color color) {
			
			this.gameplayComponent.SetColor(color);
			
		}
		
		public void Quit() {

			var endGame = this.FlowEndGame();
			endGame.events.onEveryInstance.onShowEnd.AddListener(() => {
				
				this.hud.Hide();
				this.Hide();

			});

		}

	}

}