//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the UI.Windows Flow Addon.
//
//     You may simply edit this file to setup your behavior.
// </auto-generated>
// <example>
// Pass parameters here
// Example: WindowSystem.Show<T>(true, "some text", this.transform);
// 
// 	public void OnParametersPass(bool anyBool, string text, Transform transform) {
// 	}
// </example>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI.Windows;

namespace ExampleProject.UI.Window31Directory {

	public class Window31DirectoryScreen : Window31DirectoryScreenBase {

	}

}