//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the UI.Windows Flow Addon.
//     You may simply edit this file to setup your behavior.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI.Windows;
using UnityEngine.UI.Windows.Types;

namespace ExampleProject.UI.Other.GameplayLoader {

	public class GameplayLoaderScreenBase : LayoutWindowType {
		
		/// <summary>
		/// Flows to the GameplayView.
		/// Full Name: ExampleProject.UI.Gameplay.GameplayView.GameplayViewScreen
		/// </summary>
		/// <returns>GameplayView</returns>
		public virtual ExampleProject.UI.Gameplay.GameplayView.GameplayViewScreen FlowGameplayView(params object[] parameters) {
			
			return WindowSystem.Show<ExampleProject.UI.Gameplay.GameplayView.GameplayViewScreen>(parameters);
			
		}
		
	}

}