//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the UI.Windows Flow Addon.
//     You may simply edit this file to setup your behavior.
//     See more: https://github.com/chromealex/Unity3d.UI.Windows
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI.Windows;
using UnityEngine.UI.Windows.Components;
using ExampleProject.UI.Gameplay.GameplayView;

namespace ExampleProject.UI.Gameplay.GameplayHUD {

	public class GameplayHUDScreen : GameplayHUDScreenBase {

		private GameplayView.GameplayViewScreen gameplay;

		private ButtonComponent blackButton;
		private ButtonComponent whiteButton;

		public void OnParametersPass(GameplayView.GameplayViewScreen gameplay) {

			this.gameplay = gameplay;

		}

		public override void OnInit() {

			base.OnInit();

			this.GetLayoutComponent<ButtonComponent>(out this.blackButton, LayoutTag.Tag2);
			this.GetLayoutComponent<ButtonComponent>(out this.whiteButton, LayoutTag.Tag3);

			this.blackButton.SetCallback(this.OnBlackButton);
			this.whiteButton.SetCallback(this.OnWhiteButton);
			this.GetLayoutComponent<ButtonComponent>(LayoutTag.Tag4).SetCallback(this.OnQuit);

		}

		private void OnBlackButton() {

			this.SetSide(Side.Black);

		}

		private void OnWhiteButton() {

			this.SetSide(Side.White);

		}

		public void SetSide(Side side) {

			this.whiteButton.SetEnabled();
			this.blackButton.SetEnabled();

			switch (side) {
				
				case Side.Black:
					this.blackButton.SetDisabled();
					break;

				case Side.White:
					this.whiteButton.SetDisabled();
					break;

			}

			this.gameplay.SetSide(side);

		}

		public void OnQuit() {

			this.gameplay.Quit();

		}

	}

}