using UnityEngine;
using System.Collections;

public class MacrosInjectionTest : MonoBehaviour {

	void Start() {

		#region macros TEST1 
	/*
	 * This code is auto-generated by Macros Module
	 * Do not change anything
	 */
	var a = 260;
			--a;
			++a;
			if (UnityEngine.UI.Windows.Constants.LOGS_ENABLED == true) UnityEngine.Debug.Log(a);
	#endregion

	}

	// Update is called once per frame
	void Update () {
	}
}
