//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the UI.Windows Flow Addon.
//     You may simply edit this file to setup your behavior.
//     See more: https://github.com/chromealex/Unity3d.UI.Windows
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI.Windows;
using ExampleProject.Gameplay.GameplayView.Components;

namespace ExampleProject.UI.Gameplay.GameplayView {

	public enum Side : byte {
		Black,
		White,
	};

	public class GameplayViewScreen : GameplayViewScreenBase {

		private GameplayComponent gameplayComponent;
		private GameplayHUD.GameplayHUDScreen hud;

		private Side startSide;

		public void OnParametersPass(Side startSide) {

			this.startSide = startSide;

		}

		public override void OnInit() {

			base.OnInit();

			this.GetLayoutComponent(out this.gameplayComponent);

		}

		public override void OnShowBegin() {

			base.OnShowBegin();
			
			this.hud = this.FlowGameplayHUD(this);
			this.hud.SetSide(this.startSide);

		}

		public void SetSide(Side side) {

			switch (side) {

				case Side.Black:
					this.gameplayComponent.SetColor(Color.black);
					break;

				case Side.White:
					this.gameplayComponent.SetColor(Color.white);
					break;

			}

		}
		
		public void Quit() {

			var endGame = this.FlowEndGame();
			UnityEngine.Events.UnityAction action = null;
			action = () => {

				endGame.events.onEveryInstance.Unregister(WindowEventType.OnShowEnd, action);
				this.hud.Hide();
				this.Hide();

			};
			endGame.events.onEveryInstance.Register(WindowEventType.OnShowEnd, action);

		}

	}

}