.TH "ExampleProject.UI.Other.GameplayLoader.GameplayLoaderScreen" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleProject.UI.Other.GameplayLoader.GameplayLoaderScreen \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBExampleProject\&.UI\&.Other\&.GameplayLoader\&.GameplayLoaderScreenBase\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 19 of file GameplayLoaderScreen\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
