.TH "ExampleProject.UI.Gameplay.GameplayHUD" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleProject.UI.Gameplay.GameplayHUD \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGameplayHUDScreen\fP"
.br
.ti -1c
.RI "class \fBGameplayHUDScreenBase\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
