.TH "ExampleProject.UI.Menu.GlobalMap.GlobalMapScreenBase" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleProject.UI.Menu.GlobalMap.GlobalMapScreenBase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Types\&.LayoutWindowType\fP\&.
.PP
Inherited by \fBExampleProject\&.UI\&.Menu\&.GlobalMap\&.GlobalMapScreen\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBExampleProject\&.UI\&.Menu\&.GameTypeChooser\&.GameTypeChooserScreen\fP \fBFlowGameTypeChooser\fP (params object[] parameters)"
.br
.RI "\fIFlows to the \fBGameTypeChooser\fP\&. Full Name: \fBExampleProject\&.UI\&.Menu\&.GameTypeChooser\&.GameTypeChooserScreen\fP \fP"
.ti -1c
.RI "virtual \fBExampleProject\&.UI\&.Menu\&.ShopOperations\&.Shop\&.ShopScreen\fP \fBFlowShop\fP (params object[] parameters)"
.br
.RI "\fIFlows to the Shop\&. Full Name: \fBExampleProject\&.UI\&.Menu\&.ShopOperations\&.Shop\&.ShopScreen\fP \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file GlobalMapScreenBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBExampleProject\&.UI\&.Menu\&.GameTypeChooser\&.GameTypeChooserScreen\fP ExampleProject\&.UI\&.Menu\&.GlobalMap\&.GlobalMapScreenBase\&.FlowGameTypeChooser (params object[] parameters)\fC [virtual]\fP"

.PP
Flows to the \fBGameTypeChooser\fP\&. Full Name: \fBExampleProject\&.UI\&.Menu\&.GameTypeChooser\&.GameTypeChooserScreen\fP 
.PP
\fBReturns:\fP
.RS 4
\fBGameTypeChooser\fP
.RE
.PP

.PP
Definition at line 20 of file GlobalMapScreenBase\&.cs\&.
.SS "virtual \fBExampleProject\&.UI\&.Menu\&.ShopOperations\&.Shop\&.ShopScreen\fP ExampleProject\&.UI\&.Menu\&.GlobalMap\&.GlobalMapScreenBase\&.FlowShop (params object[] parameters)\fC [virtual]\fP"

.PP
Flows to the Shop\&. Full Name: \fBExampleProject\&.UI\&.Menu\&.ShopOperations\&.Shop\&.ShopScreen\fP 
.PP
\fBReturns:\fP
.RS 4
Shop
.RE
.PP

.PP
Definition at line 31 of file GlobalMapScreenBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
