.TH "ExampleProject.UI.Gameplay.EndGame.EndGameScreenBase" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleProject.UI.Gameplay.EndGame.EndGameScreenBase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Types\&.LayoutWindowType\fP\&.
.PP
Inherited by \fBExampleProject\&.UI\&.Gameplay\&.EndGame\&.EndGameScreen\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBExampleProject\&.UI\&.Other\&.MenuLoader\&.MenuLoaderScreen\fP \fBFlowMenuLoader\fP (params object[] parameters)"
.br
.RI "\fIFlows to the MenuLoader\&. Full Name: \fBExampleProject\&.UI\&.Other\&.MenuLoader\&.MenuLoaderScreen\fP \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file EndGameScreenBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBExampleProject\&.UI\&.Other\&.MenuLoader\&.MenuLoaderScreen\fP ExampleProject\&.UI\&.Gameplay\&.EndGame\&.EndGameScreenBase\&.FlowMenuLoader (params object[] parameters)\fC [virtual]\fP"

.PP
Flows to the MenuLoader\&. Full Name: \fBExampleProject\&.UI\&.Other\&.MenuLoader\&.MenuLoaderScreen\fP 
.PP
\fBReturns:\fP
.RS 4
MenuLoader
.RE
.PP

.PP
Definition at line 20 of file EndGameScreenBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
