.TH "ExampleProject.UI.Menu.GameTypeChooser.GameTypeChooserScreenBase" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleProject.UI.Menu.GameTypeChooser.GameTypeChooserScreenBase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Types\&.LayoutWindowType\fP\&.
.PP
Inherited by \fBExampleProject\&.UI\&.Menu\&.GameTypeChooser\&.GameTypeChooserScreen\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBExampleProject\&.UI\&.Menu\&.ShopOperations\&.Shop\&.ShopScreen\fP \fBFlowShop\fP (params object[] parameters)"
.br
.RI "\fIFlows to the Shop\&. Full Name: \fBExampleProject\&.UI\&.Menu\&.ShopOperations\&.Shop\&.ShopScreen\fP \fP"
.ti -1c
.RI "virtual \fBExampleProject\&.UI\&.Other\&.GameplayLoader\&.GameplayLoaderScreen\fP \fBFlowGameplayLoader\fP (params object[] parameters)"
.br
.RI "\fIFlows to the GameplayLoader\&. Full Name: \fBExampleProject\&.UI\&.Other\&.GameplayLoader\&.GameplayLoaderScreen\fP \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file GameTypeChooserScreenBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBExampleProject\&.UI\&.Other\&.GameplayLoader\&.GameplayLoaderScreen\fP ExampleProject\&.UI\&.Menu\&.GameTypeChooser\&.GameTypeChooserScreenBase\&.FlowGameplayLoader (params object[] parameters)\fC [virtual]\fP"

.PP
Flows to the GameplayLoader\&. Full Name: \fBExampleProject\&.UI\&.Other\&.GameplayLoader\&.GameplayLoaderScreen\fP 
.PP
\fBReturns:\fP
.RS 4
GameplayLoader
.RE
.PP

.PP
Definition at line 31 of file GameTypeChooserScreenBase\&.cs\&.
.SS "virtual \fBExampleProject\&.UI\&.Menu\&.ShopOperations\&.Shop\&.ShopScreen\fP ExampleProject\&.UI\&.Menu\&.GameTypeChooser\&.GameTypeChooserScreenBase\&.FlowShop (params object[] parameters)\fC [virtual]\fP"

.PP
Flows to the Shop\&. Full Name: \fBExampleProject\&.UI\&.Menu\&.ShopOperations\&.Shop\&.ShopScreen\fP 
.PP
\fBReturns:\fP
.RS 4
Shop
.RE
.PP

.PP
Definition at line 20 of file GameTypeChooserScreenBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
