.TH "ExampleProject.UI.Gameplay.GameplayView.GameplayViewScreenBase" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleProject.UI.Gameplay.GameplayView.GameplayViewScreenBase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Types\&.LayoutWindowType\fP\&.
.PP
Inherited by \fBExampleProject\&.UI\&.Gameplay\&.GameplayView\&.GameplayViewScreen\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBExampleProject\&.UI\&.Gameplay\&.EndGame\&.EndGameScreen\fP \fBFlowEndGame\fP (params object[] parameters)"
.br
.RI "\fIFlows to the \fBEndGame\fP\&. Full Name: \fBExampleProject\&.UI\&.Gameplay\&.EndGame\&.EndGameScreen\fP \fP"
.ti -1c
.RI "virtual \fBExampleProject\&.UI\&.Gameplay\&.GameplayHUD\&.GameplayHUDScreen\fP \fBFlowGameplayHUD\fP (params object[] parameters)"
.br
.RI "\fIFlows to the \fBGameplayHUD\fP\&. Full Name: \fBExampleProject\&.UI\&.Gameplay\&.GameplayHUD\&.GameplayHUDScreen\fP \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file GameplayViewScreenBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBExampleProject\&.UI\&.Gameplay\&.EndGame\&.EndGameScreen\fP ExampleProject\&.UI\&.Gameplay\&.GameplayView\&.GameplayViewScreenBase\&.FlowEndGame (params object[] parameters)\fC [virtual]\fP"

.PP
Flows to the \fBEndGame\fP\&. Full Name: \fBExampleProject\&.UI\&.Gameplay\&.EndGame\&.EndGameScreen\fP 
.PP
\fBReturns:\fP
.RS 4
\fBEndGame\fP
.RE
.PP

.PP
Definition at line 20 of file GameplayViewScreenBase\&.cs\&.
.SS "virtual \fBExampleProject\&.UI\&.Gameplay\&.GameplayHUD\&.GameplayHUDScreen\fP ExampleProject\&.UI\&.Gameplay\&.GameplayView\&.GameplayViewScreenBase\&.FlowGameplayHUD (params object[] parameters)\fC [virtual]\fP"

.PP
Flows to the \fBGameplayHUD\fP\&. Full Name: \fBExampleProject\&.UI\&.Gameplay\&.GameplayHUD\&.GameplayHUDScreen\fP 
.PP
\fBReturns:\fP
.RS 4
\fBGameplayHUD\fP
.RE
.PP

.PP
Definition at line 31 of file GameplayViewScreenBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
