.TH "ExampleProject.UI.Gameplay.GameplayHUD.GameplayHUDScreen" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleProject.UI.Gameplay.GameplayHUD.GameplayHUDScreen \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBExampleProject\&.UI\&.Gameplay\&.GameplayHUD\&.GameplayHUDScreenBase\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 19 of file GameplayHUDScreen\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
