.TH "ExampleProject.UI.Other.MainLoader.MainLoaderScreenBase" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleProject.UI.Other.MainLoader.MainLoaderScreenBase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Types\&.LayoutWindowType\fP\&.
.PP
Inherited by \fBExampleProject\&.UI\&.Other\&.MainLoader\&.MainLoaderScreen\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBExampleProject\&.UI\&.Menu\&.GlobalMap\&.GlobalMapScreen\fP \fBFlowGlobalMap\fP (params object[] parameters)"
.br
.RI "\fIFlows to the GlobalMap\&. Full Name: \fBExampleProject\&.UI\&.Menu\&.GlobalMap\&.GlobalMapScreen\fP \fP"
.ti -1c
.RI "virtual \fBExampleProject\&.UI\&.Other\&.Background\&.BackgroundScreen\fP \fBFlowBackground\fP (params object[] parameters)"
.br
.RI "\fIFlows to the \fBBackground\fP\&. Full Name: \fBExampleProject\&.UI\&.Other\&.Background\&.BackgroundScreen\fP \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file MainLoaderScreenBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBExampleProject\&.UI\&.Other\&.Background\&.BackgroundScreen\fP ExampleProject\&.UI\&.Other\&.MainLoader\&.MainLoaderScreenBase\&.FlowBackground (params object[] parameters)\fC [virtual]\fP"

.PP
Flows to the \fBBackground\fP\&. Full Name: \fBExampleProject\&.UI\&.Other\&.Background\&.BackgroundScreen\fP 
.PP
\fBReturns:\fP
.RS 4
\fBBackground\fP
.RE
.PP

.PP
Definition at line 31 of file MainLoaderScreenBase\&.cs\&.
.SS "virtual \fBExampleProject\&.UI\&.Menu\&.GlobalMap\&.GlobalMapScreen\fP ExampleProject\&.UI\&.Other\&.MainLoader\&.MainLoaderScreenBase\&.FlowGlobalMap (params object[] parameters)\fC [virtual]\fP"

.PP
Flows to the GlobalMap\&. Full Name: \fBExampleProject\&.UI\&.Menu\&.GlobalMap\&.GlobalMapScreen\fP 
.PP
\fBReturns:\fP
.RS 4
GlobalMap
.RE
.PP

.PP
Definition at line 20 of file MainLoaderScreenBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
