.TH "ExampleProject.UI.Other.GameplayLoader.GameplayLoaderScreenBase" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleProject.UI.Other.GameplayLoader.GameplayLoaderScreenBase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Types\&.LayoutWindowType\fP\&.
.PP
Inherited by \fBExampleProject\&.UI\&.Other\&.GameplayLoader\&.GameplayLoaderScreen\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBExampleProject\&.UI\&.Gameplay\&.GameplayView\&.GameplayViewScreen\fP \fBFlowGameplayView\fP (params object[] parameters)"
.br
.RI "\fIFlows to the GameplayView\&. Full Name: \fBExampleProject\&.UI\&.Gameplay\&.GameplayView\&.GameplayViewScreen\fP \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file GameplayLoaderScreenBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBExampleProject\&.UI\&.Gameplay\&.GameplayView\&.GameplayViewScreen\fP ExampleProject\&.UI\&.Other\&.GameplayLoader\&.GameplayLoaderScreenBase\&.FlowGameplayView (params object[] parameters)\fC [virtual]\fP"

.PP
Flows to the GameplayView\&. Full Name: \fBExampleProject\&.UI\&.Gameplay\&.GameplayView\&.GameplayViewScreen\fP 
.PP
\fBReturns:\fP
.RS 4
GameplayView
.RE
.PP

.PP
Definition at line 20 of file GameplayLoaderScreenBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
