.TH "ExampleProject.UI.Menu.GameTypeChooser.GameTypeChooserScreen" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleProject.UI.Menu.GameTypeChooser.GameTypeChooserScreen \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBExampleProject\&.UI\&.Menu\&.GameTypeChooser\&.GameTypeChooserScreenBase\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 19 of file GameTypeChooserScreen\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
