.TH "C:/Unity3d.UI.Windows/Assets/UI.Windows/Addons/Flow/Core/FlowWindow.cs" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Unity3d.UI.Windows/Assets/UI.Windows/Addons/Flow/Core/FlowWindow.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowWindow\fP"
.br
.ti -1c
.RI "struct \fBUnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowWindow\&.ComponentLink\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBUnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBUnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.CompletedState\fP { \fBUnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.CompletedState\&.NotReady\fP, \fBUnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.CompletedState\&.ReadyButWarnings\fP, \fBUnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.CompletedState\&.Ready\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
