.TH "C:/Unity3d.UI.Windows/Assets/UI.Windows/Core/IWindow.cs" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Unity3d.UI.Windows/Assets/UI.Windows/Core/IWindow.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBUnityEngine\&.UI\&.Windows\&.IPreviewEditor\fP"
.br
.ti -1c
.RI "interface \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBUnityEngine\&.UI\&.Windows\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBUnityEngine\&.UI\&.Windows\&.WindowEventType\fP : byte { \fBUnityEngine\&.UI\&.Windows\&.WindowEventType\&.OnInit\fP, \fBUnityEngine\&.UI\&.Windows\&.WindowEventType\&.OnDeinit\fP, \fBUnityEngine\&.UI\&.Windows\&.WindowEventType\&.OnShowBegin\fP, \fBUnityEngine\&.UI\&.Windows\&.WindowEventType\&.OnShowEnd\fP, \fBUnityEngine\&.UI\&.Windows\&.WindowEventType\&.OnHideBegin\fP, \fBUnityEngine\&.UI\&.Windows\&.WindowEventType\&.OnHideEnd\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
