.TH "UnityEditor.UI.Windows.Plugins.Flow.FlowSystemEditor" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.Flow.FlowSystemEditor \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Rect \fBGetCenterRect\fP (EditorWindow editorWindow, float width, float height)"
.br
.ti -1c
.RI "static Rect \fBGetCenterRect\fP (Rect rect, float width, float height)"
.br
.ti -1c
.RI "static Rect \fBScale\fP (Rect realRect, Rect minMaxRect, Rect toPosition, Vector2 offset)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file FlowSystemEditorWindow\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static Rect UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSystemEditor\&.GetCenterRect (EditorWindow editorWindow, float width, float height)\fC [static]\fP"

.PP
Definition at line 17 of file FlowSystemEditorWindow\&.cs\&.
.SS "static Rect UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSystemEditor\&.GetCenterRect (Rect rect, float width, float height)\fC [static]\fP"

.PP
Definition at line 25 of file FlowSystemEditorWindow\&.cs\&.
.SS "static Rect UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSystemEditor\&.Scale (Rect realRect, Rect minMaxRect, Rect toPosition, Vector2 offset)\fC [static]\fP"

.PP
Definition at line 33 of file FlowSystemEditorWindow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
