.TH "UnityEditor.UI.Windows.Plugins.Flow.FlowSceneView" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.Flow.FlowSceneView \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFlowSceneItem\fP \fBGetItem\fP ()"
.br
.ti -1c
.RI "static \fBFlowSceneViewWindow\fP \fBGetView\fP ()"
.br
.ti -1c
.RI "static \fBFlowInspectorWindow\fP \fBGetInspector\fP ()"
.br
.ti -1c
.RI "static \fBFlowHierarchyWindow\fP \fBGetHierarchy\fP ()"
.br
.ti -1c
.RI "static bool \fBIsActive\fP ()"
.br
.ti -1c
.RI "static void \fBSetControl\fP (\fBFlowSystemEditorWindow\fP rootWindow, \fBFlowWindow\fP window, System\&.Action< float > onProgress)"
.br
.ti -1c
.RI "static void \fBReset\fP (System\&.Action< float > onProgress, bool onDestroy=false)"
.br
.ti -1c
.RI "static void \fBShow\fP ()"
.br
.ti -1c
.RI "static void \fBHide\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBFlowSceneViewWindow\fP \fBrecompileChecker\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1269 of file FlowItemEditorWindow\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBFlowHierarchyWindow\fP UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneView\&.GetHierarchy ()\fC [static]\fP"

.PP
Definition at line 1294 of file FlowItemEditorWindow\&.cs\&.
.SS "static \fBFlowInspectorWindow\fP UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneView\&.GetInspector ()\fC [static]\fP"

.PP
Definition at line 1288 of file FlowItemEditorWindow\&.cs\&.
.SS "static \fBFlowSceneItem\fP UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneView\&.GetItem ()\fC [static]\fP"

.PP
Definition at line 1276 of file FlowItemEditorWindow\&.cs\&.
.SS "static \fBFlowSceneViewWindow\fP UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneView\&.GetView ()\fC [static]\fP"

.PP
Definition at line 1282 of file FlowItemEditorWindow\&.cs\&.
.SS "static void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneView\&.Hide ()\fC [static]\fP"

.PP
Definition at line 1352 of file FlowItemEditorWindow\&.cs\&.
.SS "static bool UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneView\&.IsActive ()\fC [static]\fP"

.PP
Definition at line 1300 of file FlowItemEditorWindow\&.cs\&.
.SS "static void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneView\&.Reset (System\&.Action< float > onProgress, bool onDestroy = \fCfalse\fP)\fC [static]\fP"

.PP
Definition at line 1327 of file FlowItemEditorWindow\&.cs\&.
.SS "static void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneView\&.SetControl (\fBFlowSystemEditorWindow\fP rootWindow, \fBFlowWindow\fP window, System\&.Action< float > onProgress)\fC [static]\fP"

.PP
Definition at line 1307 of file FlowItemEditorWindow\&.cs\&.
.SS "static void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneView\&.Show ()\fC [static]\fP"

.PP
Definition at line 1345 of file FlowItemEditorWindow\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFlowSceneViewWindow\fP UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneView\&.recompileChecker\fC [static]\fP"

.PP
Definition at line 1271 of file FlowItemEditorWindow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
