.TH "UnityEngine.UI.Windows.Components.InputFieldComponent" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Components.InputFieldComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.WindowComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBGetText\fP ()"
.br
.ti -1c
.RI "void \fBSetText\fP (string \fBtext\fP)"
.br
.ti -1c
.RI "void \fBSetContentType\fP (InputField\&.ContentType contentType)"
.br
.ti -1c
.RI "void \fBSetLineType\fP (InputField\&.LineType lineType)"
.br
.ti -1c
.RI "void \fBSetCharacterLimit\fP (int length=0)"
.br
.ti -1c
.RI "void \fBSetCallbacks\fP (UnityAction< string > onChange, UnityAction< string > onEditEnd)"
.br
.ti -1c
.RI "override void \fBOnDeinit\fP ()"
.br
.RI "\fIRaises the deinit event\&. You can override this method but call it's base\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Text \fBtext\fP"
.br
.ti -1c
.RI "InputField \fBinputField\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file InputFieldComponent\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "string UnityEngine\&.UI\&.Windows\&.Components\&.InputFieldComponent\&.GetText ()"

.PP
Definition at line 18 of file InputFieldComponent\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Components\&.InputFieldComponent\&.OnDeinit ()\fC [virtual]\fP"

.PP
Raises the deinit event\&. You can override this method but call it's base\&. 
.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowComponent\fP\&.
.PP
Definition at line 55 of file InputFieldComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.InputFieldComponent\&.SetCallbacks (UnityAction< string > onChange, UnityAction< string > onEditEnd)"

.PP
Definition at line 48 of file InputFieldComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.InputFieldComponent\&.SetCharacterLimit (int length = \fC0\fP)"

.PP
Definition at line 42 of file InputFieldComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.InputFieldComponent\&.SetContentType (InputField\&.ContentType contentType)"

.PP
Definition at line 30 of file InputFieldComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.InputFieldComponent\&.SetLineType (InputField\&.LineType lineType)"

.PP
Definition at line 36 of file InputFieldComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.InputFieldComponent\&.SetText (string text)"

.PP
Definition at line 24 of file InputFieldComponent\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "InputField UnityEngine\&.UI\&.Windows\&.Components\&.InputFieldComponent\&.inputField\fC [protected]\fP"

.PP
Definition at line 13 of file InputFieldComponent\&.cs\&.
.SS "Text UnityEngine\&.UI\&.Windows\&.Components\&.InputFieldComponent\&.text\fC [protected]\fP"

.PP
Definition at line 10 of file InputFieldComponent\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
