.TH "UnityEditor.UI.Windows.Plugins.DevicePreview.Output.DeviceOutputBase" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.DevicePreview.Output.DeviceOutputBase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.IDeviceOutput\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetRect\fP (Rect screenRect, Rect \fBrect\fP, Rect landscapeRect, ScreenOrientation \fBorientation\fP)"
.br
.ti -1c
.RI "virtual float \fBGetLandscapeOrientationAngle\fP ()"
.br
.ti -1c
.RI "virtual float \fBGetPortraitOrientationAngle\fP ()"
.br
.ti -1c
.RI "virtual string \fBGetMainImage\fP ()"
.br
.ti -1c
.RI "virtual void \fBDoPreGUI\fP ()"
.br
.ti -1c
.RI "virtual void \fBDoPostGUI\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnPreGUI\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnPostGUI\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Rect \fBrect\fP"
.br
.ti -1c
.RI "Rect \fBdeviceRect\fP"
.br
.ti -1c
.RI "ScreenOrientation \fBorientation\fP"
.br
.ti -1c
.RI "Sprite \fBsprite\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file DeviceOutputBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.DeviceOutputBase\&.DoPostGUI ()\fC [virtual]\fP"

.PP
Implements \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.IDeviceOutput\fP\&.
.PP
Definition at line 94 of file DeviceOutputBase\&.cs\&.
.SS "virtual void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.DeviceOutputBase\&.DoPreGUI ()\fC [virtual]\fP"

.PP
Implements \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.IDeviceOutput\fP\&.
.PP
Definition at line 86 of file DeviceOutputBase\&.cs\&.
.SS "virtual float UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.DeviceOutputBase\&.GetLandscapeOrientationAngle ()\fC [virtual]\fP"

.PP
Definition at line 68 of file DeviceOutputBase\&.cs\&.
.SS "virtual string UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.DeviceOutputBase\&.GetMainImage ()\fC [virtual]\fP"

.PP
Definition at line 80 of file DeviceOutputBase\&.cs\&.
.SS "virtual float UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.DeviceOutputBase\&.GetPortraitOrientationAngle ()\fC [virtual]\fP"

.PP
Definition at line 74 of file DeviceOutputBase\&.cs\&.
.SS "virtual void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.DeviceOutputBase\&.OnPostGUI ()\fC [virtual]\fP"

.PP
Implements \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.IDeviceOutput\fP\&.
.PP
Definition at line 103 of file DeviceOutputBase\&.cs\&.
.SS "virtual void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.DeviceOutputBase\&.OnPreGUI ()\fC [virtual]\fP"

.PP
Implements \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.IDeviceOutput\fP\&.
.PP
Definition at line 102 of file DeviceOutputBase\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.DeviceOutputBase\&.SetRect (Rect screenRect, Rect rect, Rect landscapeRect, ScreenOrientation orientation)"

.PP
Implements \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.IDeviceOutput\fP\&.
.PP
Definition at line 16 of file DeviceOutputBase\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Rect UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.DeviceOutputBase\&.deviceRect\fC [protected]\fP"

.PP
Definition at line 10 of file DeviceOutputBase\&.cs\&.
.SS "ScreenOrientation UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.DeviceOutputBase\&.orientation\fC [protected]\fP"

.PP
Definition at line 12 of file DeviceOutputBase\&.cs\&.
.SS "Rect UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.DeviceOutputBase\&.rect\fC [protected]\fP"

.PP
Definition at line 9 of file DeviceOutputBase\&.cs\&.
.SS "Sprite UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.DeviceOutputBase\&.sprite\fC [protected]\fP"

.PP
Definition at line 14 of file DeviceOutputBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
