.TH "UnityEngine.UI.Windows.WindowSystemSettings" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.WindowSystemSettings \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBase\fP"
.br
.ti -1c
.RI "class \fBCamera\fP"
.br
.ti -1c
.RI "class \fBSortingLayer\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBApply\fP (UnityEngine\&.Camera \fBcamera\fP=null, UnityEngine\&.Canvas canvas=null)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBase\fP \fBbaseInfo\fP"
.br
.ti -1c
.RI "\fBCamera\fP \fBcamera\fP"
.br
.ti -1c
.RI "\fBSortingLayer\fP \fBsortingLayer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file WindowSystemSettings\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.UI\&.Windows\&.WindowSystemSettings\&.Apply (UnityEngine\&.Camera camera = \fCnull\fP, UnityEngine\&.Canvas canvas = \fCnull\fP)"

.PP
Definition at line 51 of file WindowSystemSettings\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBase\fP UnityEngine\&.UI\&.Windows\&.WindowSystemSettings\&.baseInfo"

.PP
Definition at line 47 of file WindowSystemSettings\&.cs\&.
.SS "\fBCamera\fP UnityEngine\&.UI\&.Windows\&.WindowSystemSettings\&.camera"

.PP
Definition at line 48 of file WindowSystemSettings\&.cs\&.
.SS "\fBSortingLayer\fP UnityEngine\&.UI\&.Windows\&.WindowSystemSettings\&.sortingLayer"

.PP
Definition at line 49 of file WindowSystemSettings\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
