.TH "UnityEngine.UI.Windows.Components.ProgressAnimatedComponent" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Components.ProgressAnimatedComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Components\&.ProgressComponent\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBtileDuration\fP = 2f"
.br
.ti -1c
.RI "\fBProgressAnimationProcessing\fP \fBprocessing\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 6 of file ProgressAnimatedComponent\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBProgressAnimationProcessing\fP UnityEngine\&.UI\&.Windows\&.Components\&.ProgressAnimatedComponent\&.processing"

.PP
Definition at line 10 of file ProgressAnimatedComponent\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.Components\&.ProgressAnimatedComponent\&.tileDuration = 2f"

.PP
Definition at line 8 of file ProgressAnimatedComponent\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
