.TH "UnityEngine.UI.Windows.Types.TextTipWindowType" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Types.TextTipWindowType \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnParametersPass\fP (string \fBtext\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBtext\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file TextTipWindowType\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.UI\&.Windows\&.Types\&.TextTipWindowType\&.OnParametersPass (string text)"

.PP
Definition at line 12 of file TextTipWindowType\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Text UnityEngine\&.UI\&.Windows\&.Types\&.TextTipWindowType\&.text"

.PP
Definition at line 10 of file TextTipWindowType\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
