.TH "UnityEngine.UI.Windows.Animations.WindowAnimationBase.Transition" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Animations.WindowAnimationBase.Transition \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBApplyInputParameters\fP (\fBWindowComponentBase\fP layoutElement)"
.br
.ti -1c
.RI "\fBTransitionBase\&.ParametersBase\fP \fBGetDefaultInputParameters\fP ()"
.br
.ti -1c
.RI "void \fBPlay\fP (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root, bool forward, System\&.Action callback)"
.br
.ti -1c
.RI "float \fBGetDuration\fP (\fBTransitionInputParameters\fP parameters, bool forward)"
.br
.ti -1c
.RI "void \fBSetInState\fP (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)"
.br
.ti -1c
.RI "void \fBSetOutState\fP (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)"
.br
.ti -1c
.RI "void \fBSetResetState\fP (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTransitionBase\fP \fBtransition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file WindowAnimationBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationBase\&.Transition\&.ApplyInputParameters (\fBWindowComponentBase\fP layoutElement)"

.PP
Definition at line 14 of file WindowAnimationBase\&.cs\&.
.SS "\fBTransitionBase\&.ParametersBase\fP UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationBase\&.Transition\&.GetDefaultInputParameters ()"

.PP
Definition at line 22 of file WindowAnimationBase\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationBase\&.Transition\&.GetDuration (\fBTransitionInputParameters\fP parameters, bool forward)"

.PP
Definition at line 34 of file WindowAnimationBase\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationBase\&.Transition\&.Play (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root, bool forward, System\&.Action callback)"

.PP
Definition at line 28 of file WindowAnimationBase\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationBase\&.Transition\&.SetInState (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)"

.PP
Definition at line 40 of file WindowAnimationBase\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationBase\&.Transition\&.SetOutState (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)"

.PP
Definition at line 46 of file WindowAnimationBase\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationBase\&.Transition\&.SetResetState (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)"

.PP
Definition at line 52 of file WindowAnimationBase\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTransitionBase\fP UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationBase\&.Transition\&.transition"

.PP
Definition at line 12 of file WindowAnimationBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
