.TH "UnityEngine.UI.Windows.WindowSystemSettings.Camera" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.WindowSystemSettings.Camera \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBApply\fP (UnityEngine\&.Camera \fBcamera\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBorthographic\fP = true"
.br
.ti -1c
.RI "float \fBorthographicSize\fP = 5f"
.br
.ti -1c
.RI "float \fBnearClipPlane\fP = -100f"
.br
.ti -1c
.RI "float \fBfarClipPlane\fP = 100f"
.br
.ti -1c
.RI "bool \fBuseOcclusionCulling\fP = false"
.br
.ti -1c
.RI "bool \fBhdr\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file WindowSystemSettings\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.UI\&.Windows\&.WindowSystemSettings\&.Camera\&.Apply (UnityEngine\&.Camera camera)"

.PP
Definition at line 27 of file WindowSystemSettings\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float UnityEngine\&.UI\&.Windows\&.WindowSystemSettings\&.Camera\&.farClipPlane = 100f"

.PP
Definition at line 23 of file WindowSystemSettings\&.cs\&.
.SS "bool UnityEngine\&.UI\&.Windows\&.WindowSystemSettings\&.Camera\&.hdr = false"

.PP
Definition at line 25 of file WindowSystemSettings\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.WindowSystemSettings\&.Camera\&.nearClipPlane = -100f"

.PP
Definition at line 22 of file WindowSystemSettings\&.cs\&.
.SS "bool UnityEngine\&.UI\&.Windows\&.WindowSystemSettings\&.Camera\&.orthographic = true"

.PP
Definition at line 20 of file WindowSystemSettings\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.WindowSystemSettings\&.Camera\&.orthographicSize = 5f"

.PP
Definition at line 21 of file WindowSystemSettings\&.cs\&.
.SS "bool UnityEngine\&.UI\&.Windows\&.WindowSystemSettings\&.Camera\&.useOcclusionCulling = false"

.PP
Definition at line 24 of file WindowSystemSettings\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
