.TH "UnityEngine.UI.Windows.Preferences" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Preferences \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBDepth\fP { \fBDepth\&.Auto\fP = 0, \fBDepth\&.AlwaysTop\fP = 1, \fBDepth\&.AlwaysBack\fP = 2 }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDepth\fP \fBdepth\fP"
.br
.ti -1c
.RI "bool \fBdontDestroyOnLoad\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 265 of file WindowBaseModules\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBUnityEngine\&.UI\&.Windows\&.Preferences\&.Depth\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIAuto \fP\fP
.TP
\fB\fIAlwaysTop \fP\fP
.TP
\fB\fIAlwaysBack \fP\fP
.PP
Definition at line 267 of file WindowBaseModules\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDepth\fP UnityEngine\&.UI\&.Windows\&.Preferences\&.depth"

.PP
Definition at line 271 of file WindowBaseModules\&.cs\&.
.SS "bool UnityEngine\&.UI\&.Windows\&.Preferences\&.dontDestroyOnLoad = true"

.PP
Definition at line 274 of file WindowBaseModules\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
