.TH "UnityEditor.UI.Windows.Plugins.DevicePreview.Output.IDeviceOutput" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.DevicePreview.Output.IDeviceOutput \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.DeviceOutputBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetRect\fP (Rect screenRect, Rect rect, Rect landscapeRect, ScreenOrientation orientation)"
.br
.ti -1c
.RI "void \fBOnPreGUI\fP ()"
.br
.ti -1c
.RI "void \fBOnPostGUI\fP ()"
.br
.ti -1c
.RI "void \fBDoPreGUI\fP ()"
.br
.ti -1c
.RI "void \fBDoPostGUI\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file IDeviceOutput\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.IDeviceOutput\&.DoPostGUI ()"

.PP
Implemented in \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.DeviceOutputBase\fP\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.IDeviceOutput\&.DoPreGUI ()"

.PP
Implemented in \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.DeviceOutputBase\fP\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.IDeviceOutput\&.OnPostGUI ()"

.PP
Implemented in \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.DeviceOutputBase\fP\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.IDeviceOutput\&.OnPreGUI ()"

.PP
Implemented in \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.DeviceOutputBase\fP\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.IDeviceOutput\&.SetRect (Rect screenRect, Rect rect, Rect landscapeRect, ScreenOrientation orientation)"

.PP
Implemented in \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Output\&.DeviceOutputBase\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
