.TH "UnityEngine.UI.Windows.Animations.WindowAnimationBase" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Animations.WindowAnimationBase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTransition\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBApplyInputParameters\fP (\fBWindowComponentBase\fP layoutElement)"
.br
.ti -1c
.RI "void \fBSetInState\fP (List< \fBTransitionInputParameters\fP > parameters, \fBWindowComponentBase\fP root)"
.br
.ti -1c
.RI "void \fBSetOutState\fP (List< \fBTransitionInputParameters\fP > parameters, \fBWindowComponentBase\fP root)"
.br
.ti -1c
.RI "void \fBSetResetState\fP (List< \fBTransitionInputParameters\fP > parameters, \fBWindowComponentBase\fP root)"
.br
.ti -1c
.RI "void \fBPlay\fP (List< \fBTransitionInputParameters\fP > parameters, \fBWindowComponentBase\fP root, bool forward, System\&.Action callback)"
.br
.ti -1c
.RI "float \fBGetDuration\fP (List< \fBTransitionInputParameters\fP > parameters, bool forward)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBTransition\fP > \fBtransitions\fP = new List<\fBTransition\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file WindowAnimationBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationBase\&.ApplyInputParameters (\fBWindowComponentBase\fP layoutElement)"

.PP
Definition at line 62 of file WindowAnimationBase\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationBase\&.GetDuration (List< \fBTransitionInputParameters\fP > parameters, bool forward)"

.PP
Definition at line 134 of file WindowAnimationBase\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationBase\&.Play (List< \fBTransitionInputParameters\fP > parameters, \fBWindowComponentBase\fP root, bool forward, System\&.Action callback)"

.PP
Definition at line 106 of file WindowAnimationBase\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationBase\&.SetInState (List< \fBTransitionInputParameters\fP > parameters, \fBWindowComponentBase\fP root)"

.PP
Definition at line 73 of file WindowAnimationBase\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationBase\&.SetOutState (List< \fBTransitionInputParameters\fP > parameters, \fBWindowComponentBase\fP root)"

.PP
Definition at line 84 of file WindowAnimationBase\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationBase\&.SetResetState (List< \fBTransitionInputParameters\fP > parameters, \fBWindowComponentBase\fP root)"

.PP
Definition at line 95 of file WindowAnimationBase\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBTransition\fP> UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationBase\&.transitions = new List<\fBTransition\fP>()"

.PP
Definition at line 60 of file WindowAnimationBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
