.TH "UnityEngine.UI.Windows.Components.ISelectable" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Components.ISelectable \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Components\&.IComponent\fP\&.
.PP
Inherited by \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSelect\fP ()"
.br
.ti -1c
.RI "void \fBDeselect\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file ITextComponent\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.ISelectable\&.Deselect ()"

.PP
Implemented in \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonComponent\fP\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.ISelectable\&.Select ()"

.PP
Implemented in \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonComponent\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
