.TH "UnityEngine.UI.Windows.Events" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Events \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBOnDestroy\fP ()"
.br
.ti -1c
.RI "void \fBOnInit\fP ()"
.br
.ti -1c
.RI "void \fBOnDeinit\fP ()"
.br
.ti -1c
.RI "void \fBOnShowBegin\fP (System\&.Action callback)"
.br
.ti -1c
.RI "void \fBOnShowEnd\fP ()"
.br
.ti -1c
.RI "void \fBOnHideBegin\fP (System\&.Action callback)"
.br
.ti -1c
.RI "void \fBOnHideEnd\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "EventsAction< \fBWindowEventType\fP > \fBevents\fP = new EventsAction<\fBWindowEventType\fP>()"
.br
.ti -1c
.RI "EventsAction< \fBWindowEventType\fP > \fBeventsInstance\fP = new EventsAction<\fBWindowEventType\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 230 of file WindowBaseModules\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.UI\&.Windows\&.Events\&.Clear ()"

.PP
Definition at line 235 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Events\&.OnDeinit ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 256 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Events\&.OnDestroy ()"

.PP
Definition at line 241 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Events\&.OnHideBegin (System\&.Action callback)"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 259 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Events\&.OnHideEnd ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 260 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Events\&.OnInit ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 255 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Events\&.OnShowBegin (System\&.Action callback)"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 257 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Events\&.OnShowEnd ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 258 of file WindowBaseModules\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "EventsAction<\fBWindowEventType\fP> UnityEngine\&.UI\&.Windows\&.Events\&.events = new EventsAction<\fBWindowEventType\fP>()"

.PP
Definition at line 232 of file WindowBaseModules\&.cs\&.
.SS "EventsAction<\fBWindowEventType\fP> UnityEngine\&.UI\&.Windows\&.Events\&.eventsInstance = new EventsAction<\fBWindowEventType\fP>()"

.PP
Definition at line 233 of file WindowBaseModules\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
