.TH "UnityEngine.UI.ButtonWithReference" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.ButtonWithReference \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.ButtonExtended\fP\&.
.PP
Inherited by \fBUnityEngine\&.UI\&.ButtonWithLabel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnDeselect\fP (BaseEventData eventData)"
.br
.ti -1c
.RI "override void \fBOnMove\fP (AxisEventData eventData)"
.br
.ti -1c
.RI "override void \fBOnPointerDown\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "override void \fBOnPointerEnter\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "override void \fBOnPointerExit\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "override void \fBOnPointerUp\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "override void \fBOnSelect\fP (BaseEventData eventData)"
.br
.ti -1c
.RI "override bool \fBIsInteractable\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Button \fBrootButton\fP"
.br
.ti -1c
.RI "Button \fBreferenceButton\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDoStateTransition\fP (Selectable\&.SelectionState state, bool instant)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "new bool \fBinteractable\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file ButtonWithReference\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void UnityEngine\&.UI\&.ButtonWithReference\&.DoStateTransition (Selectable\&.SelectionState state, bool instant)\fC [protected]\fP"

.PP
Definition at line 12 of file ButtonWithReference\&.cs\&.
.SS "override bool UnityEngine\&.UI\&.ButtonWithReference\&.IsInteractable ()"

.PP
Definition at line 101 of file ButtonWithReference\&.cs\&.
.SS "override void UnityEngine\&.UI\&.ButtonWithReference\&.OnDeselect (BaseEventData eventData)"

.PP
Definition at line 20 of file ButtonWithReference\&.cs\&.
.SS "override void UnityEngine\&.UI\&.ButtonWithReference\&.OnMove (AxisEventData eventData)"

.PP
Definition at line 27 of file ButtonWithReference\&.cs\&.
.SS "override void UnityEngine\&.UI\&.ButtonWithReference\&.OnPointerDown (PointerEventData eventData)"

.PP
Definition at line 34 of file ButtonWithReference\&.cs\&.
.SS "override void UnityEngine\&.UI\&.ButtonWithReference\&.OnPointerEnter (PointerEventData eventData)"

.PP
Definition at line 41 of file ButtonWithReference\&.cs\&.
.SS "override void UnityEngine\&.UI\&.ButtonWithReference\&.OnPointerExit (PointerEventData eventData)"

.PP
Definition at line 48 of file ButtonWithReference\&.cs\&.
.SS "override void UnityEngine\&.UI\&.ButtonWithReference\&.OnPointerUp (PointerEventData eventData)"

.PP
Definition at line 55 of file ButtonWithReference\&.cs\&.
.SS "override void UnityEngine\&.UI\&.ButtonWithReference\&.OnSelect (BaseEventData eventData)"

.PP
Definition at line 62 of file ButtonWithReference\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Button UnityEngine\&.UI\&.ButtonWithReference\&.referenceButton"

.PP
Definition at line 10 of file ButtonWithReference\&.cs\&.
.SS "Button UnityEngine\&.UI\&.ButtonWithReference\&.rootButton"

.PP
Definition at line 9 of file ButtonWithReference\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "new bool UnityEngine\&.UI\&.ButtonWithReference\&.interactable\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 69 of file ButtonWithReference\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
