.TH "UnityEngine.UI.Windows.Animations.TransitionBase.ParametersBase" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Animations.TransitionBase.ParametersBase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionAlpha\&.Parameters\fP, \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionSlide\&.Parameters\fP, and \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.Parameters\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParametersBase\fP ()"
.br
.ti -1c
.RI "\fBParametersBase\fP (\fBParametersBase\fP defaults)"
.br
.ti -1c
.RI "virtual void \fBSetup\fP (\fBParametersBase\fP defaults)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBinDelay\fP"
.br
.ti -1c
.RI "float \fBoutDelay\fP"
.br
.ti -1c
.RI "float \fBinDuration\fP"
.br
.ti -1c
.RI "float \fBoutDuration\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file TransitionBase\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.ParametersBase\&.ParametersBase ()"

.PP
Definition at line 17 of file TransitionBase\&.cs\&.
.SS "UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.ParametersBase\&.ParametersBase (\fBParametersBase\fP defaults)"

.PP
Definition at line 19 of file TransitionBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.ParametersBase\&.Setup (\fBParametersBase\fP defaults)\fC [virtual]\fP"

.PP
Definition at line 31 of file TransitionBase\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.ParametersBase\&.inDelay"

.PP
Definition at line 11 of file TransitionBase\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.ParametersBase\&.inDuration"

.PP
Definition at line 14 of file TransitionBase\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.ParametersBase\&.outDelay"

.PP
Definition at line 12 of file TransitionBase\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.ParametersBase\&.outDuration"

.PP
Definition at line 15 of file TransitionBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
