.TH "UnityEngine.UI.Windows.Components.ITextComponent" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Components.ITextComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Components\&.IComponent\fP\&.
.PP
Inherited by \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonWithTextComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.TextComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetValue\fP (int value, \fBUnityEngine\&.UI\&.Windows\&.Components\&.TextComponent\&.ValueFormat\fP format=UnityEngine\&.UI\&.Windows\&.Components\&.TextComponent\&.ValueFormat\&.None)"
.br
.ti -1c
.RI "void \fBSetText\fP (string text)"
.br
.ti -1c
.RI "string \fBGetText\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file ITextComponent\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "string UnityEngine\&.UI\&.Windows\&.Components\&.ITextComponent\&.GetText ()"

.PP
Implemented in \fBUnityEngine\&.UI\&.Windows\&.Components\&.TextComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonWithTextComponent\fP\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.ITextComponent\&.SetText (string text)"

.PP
Implemented in \fBUnityEngine\&.UI\&.Windows\&.Components\&.TextComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonWithTextComponent\fP\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.ITextComponent\&.SetValue (int value, \fBUnityEngine\&.UI\&.Windows\&.Components\&.TextComponent\&.ValueFormat\fP format = \fCUnityEngine\&.UI\&.Windows\&.Components\&.TextComponent\&.ValueFormat\&.None\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
