.TH "UnityEngine.UI.Windows.Modules.CloseButton" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Modules.CloseButton \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.WindowModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetManualCallback\fP (System\&.Action callback)"
.br
.ti -1c
.RI "void \fBOnAction\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file CloseButton\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.UI\&.Windows\&.Modules\&.CloseButton\&.OnAction ()"

.PP
Definition at line 17 of file CloseButton\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Modules\&.CloseButton\&.SetManualCallback (System\&.Action callback)"

.PP
Definition at line 11 of file CloseButton\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
