.TH "UnityEngine.UI.Windows.Animations.TransitionBase" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Animations.TransitionBase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.PP
Inherited by \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionAlpha\fP, \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionSlide\fP, and \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBParametersBase\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBParametersBase\fP \fBGetDefaultInputParameters\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetInState\fP (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)"
.br
.ti -1c
.RI "virtual void \fBSetOutState\fP (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)"
.br
.ti -1c
.RI "virtual void \fBSetResetState\fP (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)"
.br
.ti -1c
.RI "void \fBPlay\fP (\fBWindowBase\fP window, bool forward, System\&.Action callback)"
.br
.ti -1c
.RI "void \fBPlay\fP (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root, bool forward, System\&.Action callback)"
.br
.ti -1c
.RI "void \fBPlay\fP (\fBWindowBase\fP window, \fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root, bool forward, System\&.Action callback)"
.br
.ti -1c
.RI "virtual void \fBOnInit\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnPlay\fP (\fBWindowBase\fP window, object tag, \fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root, bool forward, System\&.Action callback)"
.br
.ti -1c
.RI "virtual float \fBGetDelay\fP (\fBTransitionInputParameters\fP parameters, bool forward)"
.br
.ti -1c
.RI "virtual float \fBGetDuration\fP (\fBTransitionInputParameters\fP parameters, bool forward)"
.br
.ti -1c
.RI "T \fBGetParams< T >\fP (\fBTransitionInputParameters\fP parameters)"
.br
.ti -1c
.RI "virtual void \fBOnRenderTransition\fP (\fBWindowBase\fP window, RenderTexture source, RenderTexture destination)"
.br
.ti -1c
.RI "virtual bool \fBIsValid\fP (\fBWindowBase\fP window)"
.br
.ti -1c
.RI "virtual void \fBSetupCamera\fP (Camera camera)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file TransitionBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBParametersBase\fP UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.GetDefaultInputParameters ()\fC [virtual]\fP"

.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionSlide\fP, \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\fP, and \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionAlpha\fP\&.
.PP
Definition at line 37 of file TransitionBase\&.cs\&.
.SS "virtual float UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.GetDelay (\fBTransitionInputParameters\fP parameters, bool forward)\fC [virtual]\fP"

.PP
Definition at line 107 of file TransitionBase\&.cs\&.
.SS "virtual float UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.GetDuration (\fBTransitionInputParameters\fP parameters, bool forward)\fC [virtual]\fP"

.PP
Definition at line 121 of file TransitionBase\&.cs\&.
.SS "T UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.GetParams< T > (\fBTransitionInputParameters\fP parameters)"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIParametersBase\fP
.PP
Definition at line 135 of file TransitionBase\&.cs\&.
.SS "virtual bool UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.IsValid (\fBWindowBase\fP window)\fC [virtual]\fP"

.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\fP\&.
.PP
Definition at line 154 of file TransitionBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.OnInit ()\fC [virtual]\fP"

.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\fP\&.
.PP
Definition at line 103 of file TransitionBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.OnPlay (\fBWindowBase\fP window, object tag, \fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root, bool forward, System\&.Action callback)\fC [virtual]\fP"

.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\fP, \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionSlide\fP, and \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionAlpha\fP\&.
.PP
Definition at line 105 of file TransitionBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.OnRenderTransition (\fBWindowBase\fP window, RenderTexture source, RenderTexture destination)\fC [virtual]\fP"

.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\fP\&.
.PP
Definition at line 152 of file TransitionBase\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.Play (\fBWindowBase\fP window, bool forward, System\&.Action callback)"

.PP
Definition at line 64 of file TransitionBase\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.Play (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root, bool forward, System\&.Action callback)"

.PP
Definition at line 70 of file TransitionBase\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.Play (\fBWindowBase\fP window, \fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root, bool forward, System\&.Action callback)"

.PP
Definition at line 76 of file TransitionBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.SetInState (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)\fC [virtual]\fP"

.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\fP, \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionSlide\fP, and \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionAlpha\fP\&.
.PP
Definition at line 43 of file TransitionBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.SetOutState (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)\fC [virtual]\fP"

.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\fP, \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionSlide\fP, and \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionAlpha\fP\&.
.PP
Definition at line 50 of file TransitionBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.SetResetState (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)\fC [virtual]\fP"

.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\fP, \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionSlide\fP, and \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionAlpha\fP\&.
.PP
Definition at line 57 of file TransitionBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.SetupCamera (Camera camera)\fC [virtual]\fP"

.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\fP\&.
.PP
Definition at line 156 of file TransitionBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
