.TH "UnityEditor.UI.Windows.Plugins.Flow.FlowSystemEditorWindow" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.Flow.FlowSystemEditorWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEditor\&.EditorWindowExt\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnActive\fP ()"
.br
.ti -1c
.RI "override void \fBOnInactive\fP ()"
.br
.ti -1c
.RI "override void \fBOnClose\fP ()"
.br
.ti -1c
.RI "override void \fBUpdate\fP ()"
.br
.ti -1c
.RI "Vector2 \fBGetWindowSize\fP (\fBFlowWindow\fP window)"
.br
.ti -1c
.RI "void \fBOnLostFocus\fP ()"
.br
.ti -1c
.RI "void \fBDrawWindowLayout\fP (\fBFlowWindow\fP window)"
.br
.ti -1c
.RI "void \fBDrawWaitForConnection\fP ()"
.br
.ti -1c
.RI "void \fBOpenFlowData\fP (\fBFlowData\fP flowData)"
.br
.ti -1c
.RI "void \fBChangeFlowData\fP ()"
.br
.ti -1c
.RI "void \fBOnItemProgress\fP (float value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFlowSystemEditorWindow\fP \fBShowEditor\fP (System\&.Action onClose)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static GUISkin \fBdefaultSkin\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 44 of file FlowSystemEditorWindow\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSystemEditorWindow\&.ChangeFlowData ()"

.PP
Definition at line 1316 of file FlowSystemEditorWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSystemEditorWindow\&.DrawWaitForConnection ()"

.PP
Definition at line 502 of file FlowSystemEditorWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSystemEditorWindow\&.DrawWindowLayout (\fBFlowWindow\fP window)"

.PP
Definition at line 474 of file FlowSystemEditorWindow\&.cs\&.
.SS "Vector2 UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSystemEditorWindow\&.GetWindowSize (\fBFlowWindow\fP window)"

.PP
Definition at line 443 of file FlowSystemEditorWindow\&.cs\&.
.SS "override void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSystemEditorWindow\&.OnActive ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEditor\&.EditorWindowExt\fP\&.
.PP
Definition at line 91 of file FlowSystemEditorWindow\&.cs\&.
.SS "override void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSystemEditorWindow\&.OnClose ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEditor\&.EditorWindowExt\fP\&.
.PP
Definition at line 103 of file FlowSystemEditorWindow\&.cs\&.
.SS "override void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSystemEditorWindow\&.OnInactive ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEditor\&.EditorWindowExt\fP\&.
.PP
Definition at line 97 of file FlowSystemEditorWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSystemEditorWindow\&.OnItemProgress (float value)"

.PP
Definition at line 2197 of file FlowSystemEditorWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSystemEditorWindow\&.OnLostFocus ()"

.PP
Definition at line 462 of file FlowSystemEditorWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSystemEditorWindow\&.OpenFlowData (\fBFlowData\fP flowData)"

.PP
Definition at line 1309 of file FlowSystemEditorWindow\&.cs\&.
.SS "static \fBFlowSystemEditorWindow\fP UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSystemEditorWindow\&.ShowEditor (System\&.Action onClose)\fC [static]\fP"

.PP
Definition at line 50 of file FlowSystemEditorWindow\&.cs\&.
.SS "override void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSystemEditorWindow\&.Update ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEditor\&.EditorWindowExt\fP\&.
.PP
Definition at line 118 of file FlowSystemEditorWindow\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "GUISkin UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSystemEditorWindow\&.defaultSkin\fC [static]\fP"

.PP
Definition at line 46 of file FlowSystemEditorWindow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
