.TH "UnityEditor.UI.Windows.Plugins.Flow.Editors.FlowGameViewRenderWindow" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.Flow.Editors.FlowGameViewRenderWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEditor\&.EditorWindowExt\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetRenderSize\fP (int width, int height, float ppi)"
.br
.ti -1c
.RI "override void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBOnGUI\fP ()"
.br
.ti -1c
.RI "override void \fBOnClose\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFlowGameViewRenderWindow\fP \fBShow\fP (\fBWindowBase\fP previewScreen)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 11 of file FlowGameViewWindow\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowGameViewRenderWindow\&.OnClose ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEditor\&.EditorWindowExt\fP\&.
.PP
Definition at line 126 of file FlowGameViewWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowGameViewRenderWindow\&.OnGUI ()"

.PP
Definition at line 97 of file FlowGameViewWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowGameViewRenderWindow\&.SetRenderSize (int width, int height, float ppi)"

.PP
Definition at line 30 of file FlowGameViewWindow\&.cs\&.
.SS "static \fBFlowGameViewRenderWindow\fP UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowGameViewRenderWindow\&.Show (\fBWindowBase\fP previewScreen)\fC [static]\fP"

.PP
Definition at line 13 of file FlowGameViewWindow\&.cs\&.
.SS "override void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowGameViewRenderWindow\&.Update ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEditor\&.EditorWindowExt\fP\&.
.PP
Definition at line 83 of file FlowGameViewWindow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
