.TH "UnityEngine.UI.Windows.WindowSystemInput" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.WindowSystemInput \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLateUpdate\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBComponentEvent\fP \fBonPointerUp\fP = new \fBComponentEvent\fP()"
.br
.ti -1c
.RI "static \fBComponentEvent\fP \fBonPointerDown\fP = new \fBComponentEvent\fP()"
.br
.ti -1c
.RI "static \fBComponentEvent\fP \fBonPointerClick\fP = new \fBComponentEvent\fP()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file WindowSystemInput\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.UI\&.Windows\&.WindowSystemInput\&.LateUpdate ()"

.PP
Definition at line 13 of file WindowSystemInput\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBComponentEvent\fP UnityEngine\&.UI\&.Windows\&.WindowSystemInput\&.onPointerClick = new \fBComponentEvent\fP()\fC [static]\fP"

.PP
Definition at line 11 of file WindowSystemInput\&.cs\&.
.SS "\fBComponentEvent\fP UnityEngine\&.UI\&.Windows\&.WindowSystemInput\&.onPointerDown = new \fBComponentEvent\fP()\fC [static]\fP"

.PP
Definition at line 10 of file WindowSystemInput\&.cs\&.
.SS "\fBComponentEvent\fP UnityEngine\&.UI\&.Windows\&.WindowSystemInput\&.onPointerUp = new \fBComponentEvent\fP()\fC [static]\fP"

.PP
Definition at line 9 of file WindowSystemInput\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
