.TH "UnityEditor.UI.Windows.Plugins.Flow.IWindowFlowAddon" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.Flow.IWindowFlowAddon \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEditor\&.UI\&.Windows\&.IWindowAddon\fP\&.
.PP
Inherited by \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowAddon\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnFlowWindowGUI\fP (\fBFlowWindow\fP window)"
.br
.ti -1c
.RI "void \fBOnFlowSettingsGUI\fP ()"
.br
.ti -1c
.RI "void \fBOnFlowToolbarGUI\fP (GUIStyle toolbarButton)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file FlowAddon\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.IWindowFlowAddon\&.OnFlowSettingsGUI ()"

.PP
Implemented in \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreview\fP, \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompiler\fP, and \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowAddon\fP\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.IWindowFlowAddon\&.OnFlowToolbarGUI (GUIStyle toolbarButton)"

.PP
Implemented in \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompiler\fP, and \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowAddon\fP\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.IWindowFlowAddon\&.OnFlowWindowGUI (\fBFlowWindow\fP window)"

.PP
Implemented in \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompiler\fP, and \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowAddon\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
