.TH "UnityEngine.UI.Windows.Components.ButtonWithImageComponent" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Components.ButtonWithImageComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.IImageComponent\fP\&.
.PP
Inherited by \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonWithTextComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetImage\fP (Sprite sprite, bool withPivotsAndSize=false)"
.br
.ti -1c
.RI "void \fBSetImage\fP (Texture2D texture)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Image \fBimage\fP"
.br
.ti -1c
.RI "RawImage \fBrawImage\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file ButtonWithImageComponent\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.ButtonWithImageComponent\&.SetImage (Sprite sprite, bool withPivotsAndSize = \fCfalse\fP)"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.Components\&.IImageComponent\fP\&.
.PP
Definition at line 18 of file ButtonWithImageComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.ButtonWithImageComponent\&.SetImage (Texture2D texture)"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.Components\&.IImageComponent\fP\&.
.PP
Definition at line 39 of file ButtonWithImageComponent\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Image UnityEngine\&.UI\&.Windows\&.Components\&.ButtonWithImageComponent\&.image"

.PP
Definition at line 13 of file ButtonWithImageComponent\&.cs\&.
.SS "RawImage UnityEngine\&.UI\&.Windows\&.Components\&.ButtonWithImageComponent\&.rawImage"

.PP
Definition at line 16 of file ButtonWithImageComponent\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
