.TH "UnityEngine.UI.Windows.Components.ProgressAnimationProcessing" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Components.ProgressAnimationProcessing \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseVertexEffect\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBModifyVertices\fP (\fBList\fP< UIVertex > list)"
.br
.ti -1c
.RI "void \fBLateUpdate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Slider\&.Direction \fBdirection\fP"
.br
.ti -1c
.RI "float \fBduration\fP = 1f"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBStart\fP ()"
.br
.ti -1c
.RI "override void \fBOnValidate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file ProgressAnimationProcessing\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.ProgressAnimationProcessing\&.LateUpdate ()"

.PP
Definition at line 41 of file ProgressAnimationProcessing\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Components\&.ProgressAnimationProcessing\&.ModifyVertices (\fBList\fP< UIVertex > list)"

.PP
Definition at line 38 of file ProgressAnimationProcessing\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Components\&.ProgressAnimationProcessing\&.OnValidate ()\fC [protected]\fP"

.PP
Definition at line 76 of file ProgressAnimationProcessing\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Components\&.ProgressAnimationProcessing\&.Start ()\fC [protected]\fP"

.PP
Definition at line 21 of file ProgressAnimationProcessing\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Slider\&.Direction UnityEngine\&.UI\&.Windows\&.Components\&.ProgressAnimationProcessing\&.direction"

.PP
Definition at line 12 of file ProgressAnimationProcessing\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.Components\&.ProgressAnimationProcessing\&.duration = 1f"

.PP
Definition at line 14 of file ProgressAnimationProcessing\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
