.TH "UnityEngine.UI.Windows.Components.TextComponent" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Components.TextComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Components\&.ColoredComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.ITextComponent\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBValueFormat\fP : byte { \fBValueFormat\&.None\fP, \fBValueFormat\&.WithSpace\fP, \fBValueFormat\&.WithComma\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetValue\fP (int value, \fBValueFormat\fP format=ValueFormat\&.None)"
.br
.ti -1c
.RI "string \fBGetText\fP ()"
.br
.ti -1c
.RI "void \fBSetText\fP (string text)"
.br
.ti -1c
.RI "virtual void \fBSetTextColor\fP (Color color)"
.br
.ti -1c
.RI "virtual Color \fBGetTextColor\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBFormatValue\fP (int value, \fBValueFormat\fP format)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 5 of file TextComponent\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBUnityEngine\&.UI\&.Windows\&.Components\&.TextComponent\&.ValueFormat\fP : byte"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
.TP
\fB\fIWithSpace \fP\fP
.TP
\fB\fIWithComma \fP\fP
.PP
Definition at line 7 of file TextComponent\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static string UnityEngine\&.UI\&.Windows\&.Components\&.TextComponent\&.FormatValue (int value, \fBValueFormat\fP format)\fC [static]\fP"

.PP
Definition at line 18 of file TextComponent\&.cs\&.
.SS "string UnityEngine\&.UI\&.Windows\&.Components\&.TextComponent\&.GetText ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.Components\&.ITextComponent\fP\&.
.PP
Definition at line 48 of file TextComponent\&.cs\&.
.SS "virtual Color UnityEngine\&.UI\&.Windows\&.Components\&.TextComponent\&.GetTextColor ()\fC [virtual]\fP"

.PP
Definition at line 66 of file TextComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.TextComponent\&.SetText (string text)"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.Components\&.ITextComponent\fP\&.
.PP
Definition at line 54 of file TextComponent\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.Components\&.TextComponent\&.SetTextColor (Color color)\fC [virtual]\fP"

.PP
Definition at line 60 of file TextComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.TextComponent\&.SetValue (int value, \fBValueFormat\fP format = \fCValueFormat\&.None\fP)"

.PP
Definition at line 42 of file TextComponent\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
