.TH "UnityEditor.UI.Windows.Plugins.DevicePreview.DeviceInfo" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.DevicePreview.DeviceInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBmanufacturer\fP"
.br
.ti -1c
.RI "string \fBmodel\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "float \fBppi\fP"
.br
.ti -1c
.RI "string \fBdeviceOutput\fP"
.br
.ti -1c
.RI "bool \fBcurrent\fP = false"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ScreenOrientation \fBorientation\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file DevicePreviewParser\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DeviceInfo\&.current = false"

.PP
Definition at line 17 of file DevicePreviewParser\&.cs\&.
.SS "string UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DeviceInfo\&.deviceOutput"

.PP
Definition at line 15 of file DevicePreviewParser\&.cs\&.
.SS "int UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DeviceInfo\&.height"

.PP
Definition at line 13 of file DevicePreviewParser\&.cs\&.
.SS "string UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DeviceInfo\&.manufacturer"

.PP
Definition at line 10 of file DevicePreviewParser\&.cs\&.
.SS "string UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DeviceInfo\&.model"

.PP
Definition at line 11 of file DevicePreviewParser\&.cs\&.
.SS "float UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DeviceInfo\&.ppi"

.PP
Definition at line 14 of file DevicePreviewParser\&.cs\&.
.SS "int UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DeviceInfo\&.width"

.PP
Definition at line 12 of file DevicePreviewParser\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "ScreenOrientation UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DeviceInfo\&.orientation\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 20 of file DevicePreviewParser\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
