.TH "UnityEngine.UI.Windows.Plugins.Flow.FlowWindow.ComponentLink" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Plugins.Flow.FlowWindow.ComponentLink \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBComponentLink\fP (int \fBtargetWindowId\fP, \fBLayoutTag\fP \fBsourceComponentTag\fP, string comment)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtargetWindowId\fP"
.br
.ti -1c
.RI "\fBLayoutTag\fP \fBsourceComponentTag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file FlowWindow\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowWindow\&.ComponentLink\&.ComponentLink (int targetWindowId, \fBLayoutTag\fP sourceComponentTag, string comment)"

.PP
Definition at line 33 of file FlowWindow\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLayoutTag\fP UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowWindow\&.ComponentLink\&.sourceComponentTag"

.PP
Definition at line 27 of file FlowWindow\&.cs\&.
.SS "int UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowWindow\&.ComponentLink\&.targetWindowId"

.PP
Definition at line 26 of file FlowWindow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
