.TH "UnityEngine.UI.ButtonExtended" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.ButtonExtended \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Button\&.
.PP
Inherited by \fBUnityEngine\&.UI\&.ButtonWithReference\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBTransition\fP { \fBTransition\&.None\fP = 0, \fBTransition\&.ColorTint\fP = 1, \fBTransition\&.SpriteSwap\fP = 2, \fBTransition\&.Animation\fP = 3, \fBTransition\&.SpriteSwapAndColorTint\fP = 4 }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTransition\fP \fBtransitionExtended\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBInstantClearState\fP ()"
.br
.ti -1c
.RI "override void \fBDoStateTransition\fP (Selectable\&.SelectionState state, bool instant)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file ButtonExtended\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBUnityEngine\&.UI\&.ButtonExtended\&.Transition\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
.TP
\fB\fIColorTint \fP\fP
.TP
\fB\fISpriteSwap \fP\fP
.TP
\fB\fIAnimation \fP\fP
.TP
\fB\fISpriteSwapAndColorTint \fP\fP
.PP
Definition at line 8 of file ButtonExtended\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void UnityEngine\&.UI\&.ButtonExtended\&.DoStateTransition (Selectable\&.SelectionState state, bool instant)\fC [protected]\fP"

.PP
Definition at line 78 of file ButtonExtended\&.cs\&.
.SS "override void UnityEngine\&.UI\&.ButtonExtended\&.InstantClearState ()\fC [protected]\fP"

.PP
Definition at line 54 of file ButtonExtended\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTransition\fP UnityEngine\&.UI\&.ButtonExtended\&.transitionExtended"

.PP
Definition at line 19 of file ButtonExtended\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
