.TH "UnityEngine.UI.Windows.Transition" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Transition \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetup\fP (\fBWindowBase\fP window)"
.br
.ti -1c
.RI "void \fBOnInit\fP ()"
.br
.ti -1c
.RI "void \fBOnDeinit\fP ()"
.br
.ti -1c
.RI "void \fBOnShowEnd\fP ()"
.br
.ti -1c
.RI "void \fBOnHideEnd\fP ()"
.br
.ti -1c
.RI "void \fBOnShowBegin\fP (System\&.Action callback)"
.br
.ti -1c
.RI "void \fBOnHideBegin\fP (System\&.Action callback)"
.br
.ti -1c
.RI "void \fBSaveToCache\fP (Texture2D screen, System\&.Action callback, bool grabEveryFrame=false)"
.br
.ti -1c
.RI "void \fBOnPostRender\fP ()"
.br
.ti -1c
.RI "void \fBOnPreRender\fP ()"
.br
.ti -1c
.RI "void \fBOnRenderImage\fP (RenderTexture source, RenderTexture destination)"
.br
.ti -1c
.RI "float \fBGetAnimationDuration\fP (bool forward)"
.br
.ti -1c
.RI "void \fBStartRenderToTexture\fP ()"
.br
.ti -1c
.RI "void \fBStopRenderToTexture\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTransitionBase\fP \fBtransition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 279 of file WindowBaseModules\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "float UnityEngine\&.UI\&.Windows\&.Transition\&.GetAnimationDuration (bool forward)"

.PP
Definition at line 413 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Transition\&.OnDeinit ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 302 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Transition\&.OnHideBegin (System\&.Action callback)"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 319 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Transition\&.OnHideEnd ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 304 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Transition\&.OnInit ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 301 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Transition\&.OnPostRender ()"

.PP
Definition at line 346 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Transition\&.OnPreRender ()"

.PP
Definition at line 382 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Transition\&.OnRenderImage (RenderTexture source, RenderTexture destination)"

.PP
Definition at line 395 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Transition\&.OnShowBegin (System\&.Action callback)"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 305 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Transition\&.OnShowEnd ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 303 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Transition\&.SaveToCache (Texture2D screen, System\&.Action callback, bool grabEveryFrame = \fCfalse\fP)"

.PP
Definition at line 337 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Transition\&.Setup (\fBWindowBase\fP window)"

.PP
Definition at line 288 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Transition\&.StartRenderToTexture ()"

.PP
Definition at line 421 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Transition\&.StopRenderToTexture ()"

.PP
Definition at line 452 of file WindowBaseModules\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTransitionBase\fP UnityEngine\&.UI\&.Windows\&.Transition\&.transition"

.PP
Definition at line 281 of file WindowBaseModules\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
