.TH "UnityEditor.UI.Windows.WindowGUIUtilities" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.WindowGUIUtilities \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBButtonAddon\fP (string addonName, string buttonCaption, params GUILayoutOption[] options)"
.br
.ti -1c
.RI "static bool \fBButtonAddon\fP (string addonName, string buttonCaption, GUIStyle buttonStyle, params GUILayoutOption[] options)"
.br
.ti -1c
.RI "static bool \fBButtonAddon\fP (string addonName, string buttonCaption, string description, params GUILayoutOption[] options)"
.br
.ti -1c
.RI "static bool \fBButtonAddon\fP (string addonName, string buttonCaption, string description, GUIStyle buttonStyle, params GUILayoutOption[] options)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file WindowGUIUtilities\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static bool UnityEditor\&.UI\&.Windows\&.WindowGUIUtilities\&.ButtonAddon (string addonName, string buttonCaption, params GUILayoutOption[] options)\fC [static]\fP"

.PP
Definition at line 7 of file WindowGUIUtilities\&.cs\&.
.SS "static bool UnityEditor\&.UI\&.Windows\&.WindowGUIUtilities\&.ButtonAddon (string addonName, string buttonCaption, GUIStyle buttonStyle, params GUILayoutOption[] options)\fC [static]\fP"

.PP
Definition at line 13 of file WindowGUIUtilities\&.cs\&.
.SS "static bool UnityEditor\&.UI\&.Windows\&.WindowGUIUtilities\&.ButtonAddon (string addonName, string buttonCaption, string description, params GUILayoutOption[] options)\fC [static]\fP"

.PP
Definition at line 19 of file WindowGUIUtilities\&.cs\&.
.SS "static bool UnityEditor\&.UI\&.Windows\&.WindowGUIUtilities\&.ButtonAddon (string addonName, string buttonCaption, string description, GUIStyle buttonStyle, params GUILayoutOption[] options)\fC [static]\fP"

.PP
Definition at line 25 of file WindowGUIUtilities\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
