.TH "UnityEngine.UI.Windows.WindowLayoutBase" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.WindowLayoutBase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.WindowComponentBase\fP, and \fBUnityEngine\&.UI\&.Windows\&.IWindowComponentLayout\fP\&.
.PP
Inherited by \fBUnityEngine\&.UI\&.Windows\&.WindowLayoutElement\fP, and \fBUnityEngine\&.UI\&.Windows\&.WindowModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUnload\fP ()"
.br
.ti -1c
.RI "void \fBLoad\fP (\fBWindowComponent\fP component)"
.br
.ti -1c
.RI "virtual void \fBSetup\fP (\fBWindowComponent\fP component, \fBLayout\&.Component\fP activatorInstance)"
.br
.ti -1c
.RI "virtual \fBWindowComponent\fP \fBGetCurrentComponent\fP ()"
.br
.ti -1c
.RI "override void \fBShow\fP (System\&.Action callback, bool resetAnimation)"
.br
.RI "\fIShow component with callback after end\&. Animation component can use current layout element root or current component root\&. \fP"
.ti -1c
.RI "override void \fBHide\fP (System\&.Action callback, bool immediately)"
.br
.RI "\fIHide the specified callback and immediately\&. Animation component can use current layout element root or current component root\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file WindowLayoutBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBWindowComponent\fP UnityEngine\&.UI\&.Windows\&.WindowLayoutBase\&.GetCurrentComponent ()\fC [virtual]\fP"

.PP
Definition at line 40 of file WindowLayoutBase\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.WindowLayoutBase\&.Hide (System\&.Action callback, bool immediately)\fC [virtual]\fP"

.PP
Hide the specified callback and immediately\&. Animation component can use current layout element root or current component root\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcallback\fP Callback\&.
.br
\fIimmediately\fP If set to \fCtrue\fP immediately\&.
.RE
.PP

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowComponentBase\fP\&.
.PP
Definition at line 77 of file WindowLayoutBase\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.WindowLayoutBase\&.Load (\fBWindowComponent\fP component)"

.PP
Definition at line 24 of file WindowLayoutBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowLayoutBase\&.Setup (\fBWindowComponent\fP component, \fBLayout\&.Component\fP activatorInstance)\fC [virtual]\fP"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowComponentLayout\fP\&.
.PP
Definition at line 32 of file WindowLayoutBase\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.WindowLayoutBase\&.Show (System\&.Action callback, bool resetAnimation)\fC [virtual]\fP"

.PP
Show component with callback after end\&. Animation component can use current layout element root or current component root\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcallback\fP Callback\&.
.br
\fIresetAnimation\fP If set to \fCtrue\fP reset animation\&.
.RE
.PP

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowComponentBase\fP\&.
.PP
Definition at line 46 of file WindowLayoutBase\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.WindowLayoutBase\&.Unload ()"

.PP
Definition at line 11 of file WindowLayoutBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
