.TH "UnityEditor.UI.Windows.VersionInfo" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.VersionInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBdownloadLink\fP = 'https://github\&.com/chromealex/Unity3d\&.UI\&.Windows'"
.br
.ti -1c
.RI "const string \fBbundleVersion\fP = '0\&.8a'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file VersionInfo\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const string UnityEditor\&.UI\&.Windows\&.VersionInfo\&.bundleVersion = '0\&.8a'"

.PP
Definition at line 8 of file VersionInfo\&.cs\&.
.SS "const string UnityEditor\&.UI\&.Windows\&.VersionInfo\&.downloadLink = 'https://github\&.com/chromealex/Unity3d\&.UI\&.Windows'"

.PP
Definition at line 6 of file VersionInfo\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
