.TH "UnityEngine.UI.Windows.Modules.BackgroundCloseable" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Modules.BackgroundCloseable \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.WindowModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetCallback\fP (System\&.Action callback, bool overrideAutoHide=true)"
.br
.ti -1c
.RI "override void \fBOnDeinit\fP ()"
.br
.RI "\fIRaises the deinit event\&. You can override this method but call it's base\&. \fP"
.ti -1c
.RI "void \fBHideWindow\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file BackgroundCloseable\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.UI\&.Windows\&.Modules\&.BackgroundCloseable\&.HideWindow ()"

.PP
Definition at line 25 of file BackgroundCloseable\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Modules\&.BackgroundCloseable\&.OnDeinit ()\fC [virtual]\fP"

.PP
Raises the deinit event\&. You can override this method but call it's base\&. 
.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowComponentBase\fP\&.
.PP
Definition at line 19 of file BackgroundCloseable\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Modules\&.BackgroundCloseable\&.SetCallback (System\&.Action callback, bool overrideAutoHide = \fCtrue\fP)"

.PP
Definition at line 12 of file BackgroundCloseable\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
