.TH "UnityEngine.UI.Windows.WindowComponentLibraryLinker.Item" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.WindowComponentLibraryLinker.Item \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBtitle\fP"
.br
.ti -1c
.RI "string \fBlocalDirectory\fP"
.br
.ti -1c
.RI "\fBWindowComponent\fP \fBmainComponent\fP"
.br
.ti -1c
.RI "\fBWindowComponent\fP[] \fBcomponents\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file WindowComponentLibraryLinker\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBWindowComponent\fP [] UnityEngine\&.UI\&.Windows\&.WindowComponentLibraryLinker\&.Item\&.components"

.PP
Definition at line 19 of file WindowComponentLibraryLinker\&.cs\&.
.SS "string UnityEngine\&.UI\&.Windows\&.WindowComponentLibraryLinker\&.Item\&.localDirectory"

.PP
Definition at line 17 of file WindowComponentLibraryLinker\&.cs\&.
.SS "\fBWindowComponent\fP UnityEngine\&.UI\&.Windows\&.WindowComponentLibraryLinker\&.Item\&.mainComponent"

.PP
Definition at line 18 of file WindowComponentLibraryLinker\&.cs\&.
.SS "string UnityEngine\&.UI\&.Windows\&.WindowComponentLibraryLinker\&.Item\&.title"

.PP
Definition at line 16 of file WindowComponentLibraryLinker\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
