.TH "UnityEngine.UI.Windows.WindowComponentLibraryLinker" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.WindowComponentLibraryLinker \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBItem\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBchild\fP"
.br
.ti -1c
.RI "\fBItem\fP[] \fBitems\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file WindowComponentLibraryLinker\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool UnityEngine\&.UI\&.Windows\&.WindowComponentLibraryLinker\&.child"

.PP
Definition at line 85 of file WindowComponentLibraryLinker\&.cs\&.
.SS "\fBItem\fP [] UnityEngine\&.UI\&.Windows\&.WindowComponentLibraryLinker\&.items"

.PP
Definition at line 86 of file WindowComponentLibraryLinker\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
