.TH "UnityEditor.UI.Windows.WindowUtilities" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.WindowUtilities \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBLoadAddons\fP ()"
.br
.ti -1c
.RI "static List< T > \fBGetAddons< T >\fP (System\&.Action< string, T > forEach=null)"
.br
.ti -1c
.RI "static \fBIWindowAddon\fP \fBGetAddon\fP (string addonName)"
.br
.ti -1c
.RI "static bool \fBIsAddonAvailable\fP (string addonName)"
.br
.ti -1c
.RI "static Type \fBGetTypeFromAllAssemblies\fP (string typeName)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file WindowUtilities\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBIWindowAddon\fP UnityEditor\&.UI\&.Windows\&.WindowUtilities\&.GetAddon (string addonName)\fC [static]\fP"

.PP
Definition at line 61 of file WindowUtilities\&.cs\&.
.SS "static List<T> UnityEditor\&.UI\&.Windows\&.WindowUtilities\&.GetAddons< T > (System\&.Action< string, T > forEach = \fCnull\fP)\fC [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIWindowAddon\fP
.PP
Definition at line 45 of file WindowUtilities\&.cs\&.
.SS "static Type UnityEditor\&.UI\&.Windows\&.WindowUtilities\&.GetTypeFromAllAssemblies (string typeName)\fC [static]\fP"

.PP
Definition at line 103 of file WindowUtilities\&.cs\&.
.SS "static bool UnityEditor\&.UI\&.Windows\&.WindowUtilities\&.IsAddonAvailable (string addonName)\fC [static]\fP"

.PP
Definition at line 89 of file WindowUtilities\&.cs\&.
.SS "static void UnityEditor\&.UI\&.Windows\&.WindowUtilities\&.LoadAddons ()\fC [static]\fP"

.PP
Definition at line 22 of file WindowUtilities\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
