.TH "UnityEngine.UI.Windows.Animations.WindowTransitionBasic" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Animations.WindowTransitionBasic \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBParameters\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBTransitionBase\&.ParametersBase\fP \fBGetDefaultInputParameters\fP ()"
.br
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.ti -1c
.RI "override void \fBSetupCamera\fP (Camera camera)"
.br
.ti -1c
.RI "override bool \fBIsValid\fP (\fBWindowBase\fP window)"
.br
.ti -1c
.RI "override void \fBOnPlay\fP (\fBWindowBase\fP window, object tag, \fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root, bool forward, System\&.Action callback)"
.br
.ti -1c
.RI "override void \fBSetInState\fP (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)"
.br
.ti -1c
.RI "override void \fBSetOutState\fP (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)"
.br
.ti -1c
.RI "override void \fBSetResetState\fP (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)"
.br
.ti -1c
.RI "override void \fBOnRenderTransition\fP (\fBWindowBase\fP window, RenderTexture source, RenderTexture destination)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBParameters\fP \fBdefaultInputParams\fP"
.br
.ti -1c
.RI "bool \fBgrabEveryFrame\fP = false"
.br
.ti -1c
.RI "CameraClearFlags \fBclearFlags\fP = CameraClearFlags\&.Depth"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Material \fBmaterial\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file WindowTransitionBasic\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBTransitionBase\&.ParametersBase\fP UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.GetDefaultInputParameters ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\fP\&.
.PP
Definition at line 91 of file WindowTransitionBasic\&.cs\&.
.SS "override bool UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.IsValid (\fBWindowBase\fP window)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\fP\&.
.PP
Definition at line 109 of file WindowTransitionBasic\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.OnInit ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\fP\&.
.PP
Definition at line 97 of file WindowTransitionBasic\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.OnPlay (\fBWindowBase\fP window, object tag, \fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root, bool forward, System\&.Action callback)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\fP\&.
.PP
Definition at line 115 of file WindowTransitionBasic\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.OnRenderTransition (\fBWindowBase\fP window, RenderTexture source, RenderTexture destination)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\fP\&.
.PP
Definition at line 199 of file WindowTransitionBasic\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.SetInState (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\fP\&.
.PP
Definition at line 172 of file WindowTransitionBasic\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.SetOutState (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\fP\&.
.PP
Definition at line 181 of file WindowTransitionBasic\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.SetResetState (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\fP\&.
.PP
Definition at line 190 of file WindowTransitionBasic\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.SetupCamera (Camera camera)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\fP\&.
.PP
Definition at line 103 of file WindowTransitionBasic\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "CameraClearFlags UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.clearFlags = CameraClearFlags\&.Depth"

.PP
Definition at line 85 of file WindowTransitionBasic\&.cs\&.
.SS "\fBParameters\fP UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.defaultInputParams"

.PP
Definition at line 72 of file WindowTransitionBasic\&.cs\&.
.SS "bool UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.grabEveryFrame = false"

.PP
Definition at line 84 of file WindowTransitionBasic\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Material UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.material\fC [get]\fP"

.PP
Definition at line 74 of file WindowTransitionBasic\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
