.TH "UnityEditor.UI.Windows.WindowBaseInspector" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.WindowBaseInspector \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Editor\&.
.SH "Detailed Description"
.PP 
Definition at line 11 of file WindowBaseInspector\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
