.TH "UnityEngine.UI.Windows.Components.PopupComponent" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Components.PopupComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.WindowComponent\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBState\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBDropState\fP : byte { \fBDropState\&.Auto\fP, \fBDropState\&.Down\fP, \fBDropState\&.Up\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.RI "\fIRaises the init event\&. You can override this method but call it's base\&. \fP"
.ti -1c
.RI "override void \fBOnDeinit\fP ()"
.br
.RI "\fIRaises the deinit event\&. You can override this method but call it's base\&. \fP"
.ti -1c
.RI "override void \fBOnShowBegin\fP (System\&.Action callback)"
.br
.RI "\fIRaises the show begin event\&. Wait while all sub components return the callback\&. You can override this method but call it's base\&. \fP"
.ti -1c
.RI "void \fBToggle\fP ()"
.br
.ti -1c
.RI "void \fBSetState\fP (bool opened, bool immediately)"
.br
.ti -1c
.RI "T \fBAddItem< T >\fP ()"
.br
.ti -1c
.RI "\fBList\fP< T > \fBGetItems< T >\fP ()"
.br
.ti -1c
.RI "T \fBGetItem< T >\fP (int index)"
.br
.ti -1c
.RI "void \fBSetItems\fP (int capacity, UnityAction< \fBIComponent\fP > onItem=null)"
.br
.ti -1c
.RI "void \fBSetItems< T >\fP (int capacity, UnityAction< T, int > onItem=null)"
.br
.ti -1c
.RI "void \fBSelect\fP (int index, bool closePopup=true)"
.br
.ti -1c
.RI "int \fBGetSelectedIndex\fP ()"
.br
.ti -1c
.RI "void \fBUpdateDropState\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLinkerComponent\fP \fBbuttonWithText\fP"
.br
.ti -1c
.RI "\fBLinkerComponent\fP \fBlist\fP"
.br
.ti -1c
.RI "\fBDropState\fP \fBdropState\fP = DropState\&.Auto"
.br
.ti -1c
.RI "float \fBmaxHeight\fP = 200f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file PopupComponent\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBUnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.DropState\fP : byte"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIAuto \fP\fP
.TP
\fB\fIDown \fP\fP
.TP
\fB\fIUp \fP\fP
.PP
Definition at line 12 of file PopupComponent\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "T UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.AddItem< T > ()"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIITextComponent\fP
.PP
Definition at line 196 of file PopupComponent\&.cs\&.
.SS "T UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.GetItem< T > (int index)"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIITextComponent\fP
.PP
Definition at line 208 of file PopupComponent\&.cs\&.
.SS "\fBList\fP<T> UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.GetItems< T > ()"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIITextComponent\fP
.PP
Definition at line 202 of file PopupComponent\&.cs\&.
.SS "int UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.GetSelectedIndex ()"

.PP
Definition at line 271 of file PopupComponent\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.OnDeinit ()\fC [virtual]\fP"

.PP
Raises the deinit event\&. You can override this method but call it's base\&. 
.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowComponent\fP\&.
.PP
Definition at line 107 of file PopupComponent\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.OnInit ()\fC [virtual]\fP"

.PP
Raises the init event\&. You can override this method but call it's base\&. 
.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowComponent\fP\&.
.PP
Definition at line 76 of file PopupComponent\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.OnShowBegin (System\&.Action callback)\fC [virtual]\fP"

.PP
Raises the show begin event\&. Wait while all sub components return the callback\&. You can override this method but call it's base\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcallback\fP Callback\&.
.RE
.PP

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowComponent\fP\&.
.PP
Definition at line 115 of file PopupComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.Select (int index, bool closePopup = \fCtrue\fP)"

.PP
Definition at line 241 of file PopupComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.SetItems (int capacity, UnityAction< \fBIComponent\fP > onItem = \fCnull\fP)"

.PP
Definition at line 214 of file PopupComponent\&.cs\&.
.SS "void \fBUnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.SetItems\fP< T > (int capacity, UnityAction< T, int > onItem = \fCnull\fP)"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIITextComponent\fP
.PP
Definition at line 220 of file PopupComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.SetState (bool opened, bool immediately)"

.PP
Definition at line 147 of file PopupComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.Toggle ()"

.PP
Definition at line 123 of file PopupComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.UpdateDropState ()"

.PP
Definition at line 277 of file PopupComponent\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLinkerComponent\fP UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.buttonWithText"

.PP
Definition at line 58 of file PopupComponent\&.cs\&.
.SS "\fBDropState\fP UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.dropState = DropState\&.Auto"

.PP
Definition at line 69 of file PopupComponent\&.cs\&.
.SS "\fBLinkerComponent\fP UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.list"

.PP
Definition at line 59 of file PopupComponent\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.maxHeight = 200f"

.PP
Definition at line 70 of file PopupComponent\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
