.TH "UnityEngine.UI.Windows.Plugins.Flow.FlowData" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Plugins.Flow.FlowData \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindowBase\fP \fBGetRootScreen\fP ()"
.br
.ti -1c
.RI "List< \fBWindowBase\fP > \fBGetAllScreens\fP (System\&.Func< \fBFlowWindow\fP, bool > predicate=null)"
.br
.ti -1c
.RI "List< \fBWindowBase\fP > \fBGetDefaultScreens\fP ()"
.br
.ti -1c
.RI "void \fBSave\fP ()"
.br
.ti -1c
.RI "int \fBGetNextTagId\fP ()"
.br
.ti -1c
.RI "\fBFlowTag\fP \fBGetTag\fP (int id)"
.br
.ti -1c
.RI "void \fBAddTag\fP (\fBFlowWindow\fP window, \fBFlowTag\fP tag)"
.br
.ti -1c
.RI "void \fBRemoveTag\fP (\fBFlowWindow\fP window, \fBFlowTag\fP tag)"
.br
.ti -1c
.RI "void \fBSetRootWindow\fP (int id)"
.br
.ti -1c
.RI "int \fBGetRootWindow\fP ()"
.br
.ti -1c
.RI "List< int > \fBGetDefaultWindows\fP ()"
.br
.ti -1c
.RI "void \fBSetDefaultWindows\fP (List< int > \fBdefaultWindows\fP)"
.br
.ti -1c
.RI "void \fBResetSelection\fP ()"
.br
.ti -1c
.RI "List< int > \fBGetSelected\fP ()"
.br
.ti -1c
.RI "void \fBSelectWindows\fP (int[] ids)"
.br
.ti -1c
.RI "void \fBSelectWindowsInRect\fP (Rect rect, System\&.Func< \fBFlowWindow\fP, bool > predicate=null)"
.br
.ti -1c
.RI "Vector2 \fBGetScrollPosition\fP ()"
.br
.ti -1c
.RI "void \fBSetScrollPosition\fP (Vector2 \fBscrollPos\fP)"
.br
.ti -1c
.RI "\fBFlowWindow\fP \fBCreateDefaultLink\fP ()"
.br
.ti -1c
.RI "\fBFlowWindow\fP \fBCreateWindow\fP ()"
.br
.ti -1c
.RI "\fBFlowWindow\fP \fBCreateContainer\fP ()"
.br
.ti -1c
.RI "IEnumerable< \fBFlowWindow\fP > \fBGetWindows\fP ()"
.br
.ti -1c
.RI "IEnumerable< \fBFlowWindow\fP > \fBGetContainers\fP ()"
.br
.ti -1c
.RI "\fBFlowWindow\fP \fBGetWindow\fP (int id)"
.br
.ti -1c
.RI "int \fBAllocateId\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBlastModified\fP = '-'"
.br
.ti -1c
.RI "string \fBnamespaceName\fP"
.br
.ti -1c
.RI "bool \fBforceRecompile\fP"
.br
.ti -1c
.RI "Vector2 \fBscrollPos\fP = new Vector2(-1f, -1f)"
.br
.ti -1c
.RI "int \fBrootWindow\fP"
.br
.ti -1c
.RI "List< int > \fBdefaultWindows\fP = new List<int>()"
.br
.ti -1c
.RI "List< \fBFlowWindow\fP > \fBwindows\fP = new List<\fBFlowWindow\fP>()"
.br
.ti -1c
.RI "bool \fBisDirty\fP = false"
.br
.ti -1c
.RI "List< \fBFlowTag\fP > \fBtags\fP = new List<\fBFlowTag\fP>()"
.br
.ti -1c
.RI "bool \fBflowWindowWithLayout\fP"
.br
.ti -1c
.RI "float \fBflowWindowWithLayoutScaleFactor\fP = 0f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file FlowData\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.AddTag (\fBFlowWindow\fP window, \fBFlowTag\fP tag)"

.PP
Definition at line 130 of file FlowData\&.cs\&.
.SS "int UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.AllocateId ()"

.PP
Definition at line 346 of file FlowData\&.cs\&.
.SS "\fBFlowWindow\fP UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.CreateContainer ()"

.PP
Definition at line 315 of file FlowData\&.cs\&.
.SS "\fBFlowWindow\fP UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.CreateDefaultLink ()"

.PP
Definition at line 289 of file FlowData\&.cs\&.
.SS "\fBFlowWindow\fP UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.CreateWindow ()"

.PP
Definition at line 302 of file FlowData\&.cs\&.
.SS "List<\fBWindowBase\fP> UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.GetAllScreens (System\&.Func< \fBFlowWindow\fP, bool > predicate = \fCnull\fP)"

.PP
Definition at line 68 of file FlowData\&.cs\&.
.SS "IEnumerable<\fBFlowWindow\fP> UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.GetContainers ()"

.PP
Definition at line 334 of file FlowData\&.cs\&.
.SS "List<\fBWindowBase\fP> UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.GetDefaultScreens ()"

.PP
Definition at line 88 of file FlowData\&.cs\&.
.SS "List<int> UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.GetDefaultWindows ()"

.PP
Definition at line 171 of file FlowData\&.cs\&.
.SS "int UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.GetNextTagId ()"

.PP
Definition at line 111 of file FlowData\&.cs\&.
.SS "\fBWindowBase\fP UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.GetRootScreen ()"

.PP
Definition at line 55 of file FlowData\&.cs\&.
.SS "int UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.GetRootWindow ()"

.PP
Definition at line 165 of file FlowData\&.cs\&.
.SS "Vector2 UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.GetScrollPosition ()"

.PP
Definition at line 227 of file FlowData\&.cs\&.
.SS "List<int> UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.GetSelected ()"

.PP
Definition at line 189 of file FlowData\&.cs\&.
.SS "\fBFlowTag\fP UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.GetTag (int id)"

.PP
Definition at line 124 of file FlowData\&.cs\&.
.SS "\fBFlowWindow\fP UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.GetWindow (int id)"

.PP
Definition at line 340 of file FlowData\&.cs\&.
.SS "IEnumerable<\fBFlowWindow\fP> UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.GetWindows ()"

.PP
Definition at line 328 of file FlowData\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.RemoveTag (\fBFlowWindow\fP window, \fBFlowTag\fP tag)"

.PP
Definition at line 149 of file FlowData\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.ResetSelection ()"

.PP
Definition at line 183 of file FlowData\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.Save ()"

.PP
Definition at line 94 of file FlowData\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.SelectWindows (int[] ids)"

.PP
Definition at line 195 of file FlowData\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.SelectWindowsInRect (Rect rect, System\&.Func< \fBFlowWindow\fP, bool > predicate = \fCnull\fP)"

.PP
Definition at line 210 of file FlowData\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.SetDefaultWindows (List< int > defaultWindows)"

.PP
Definition at line 177 of file FlowData\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.SetRootWindow (int id)"

.PP
Definition at line 157 of file FlowData\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.SetScrollPosition (Vector2 scrollPos)"

.PP
Definition at line 233 of file FlowData\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "List<int> UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.defaultWindows = new List<int>()"

.PP
Definition at line 37 of file FlowData\&.cs\&.
.SS "bool UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.flowWindowWithLayout"

.PP
Definition at line 47 of file FlowData\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.flowWindowWithLayoutScaleFactor = 0f"

.PP
Definition at line 48 of file FlowData\&.cs\&.
.SS "bool UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.forceRecompile"

.PP
Definition at line 32 of file FlowData\&.cs\&.
.SS "bool UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.isDirty = false"

.PP
Definition at line 40 of file FlowData\&.cs\&.
.SS "string UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.lastModified = '-'"

.PP
Definition at line 29 of file FlowData\&.cs\&.
.SS "string UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.namespaceName"

.PP
Definition at line 31 of file FlowData\&.cs\&.
.SS "int UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.rootWindow"

.PP
Definition at line 36 of file FlowData\&.cs\&.
.SS "Vector2 UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.scrollPos = new Vector2(-1f, -1f)"

.PP
Definition at line 34 of file FlowData\&.cs\&.
.SS "List<\fBFlowTag\fP> UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.tags = new List<\fBFlowTag\fP>()"

.PP
Definition at line 42 of file FlowData\&.cs\&.
.SS "List<\fBFlowWindow\fP> UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowData\&.windows = new List<\fBFlowWindow\fP>()"

.PP
Definition at line 39 of file FlowData\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
