.TH "UnityEngine.UI.Windows.WindowComponent" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.WindowComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.WindowComponentBase\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.IComponent\fP\&.
.PP
Inherited by \fBUnityEngine\&.UI\&.Windows\&.Components\&.ColoredComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.DummyComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.ImageComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.InputFieldComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.LinkerComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.List\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.Table\&.TableItem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBList\fP< \fBWindowComponent\fP > \fBGetSubComponents\fP ()"
.br
.RI "\fIGets the sub components\&. \fP"
.ti -1c
.RI "\fBWindowLayoutBase\fP \fBGetLayoutRoot\fP ()"
.br
.RI "\fIGets the layout root\&. Basicaly it's the parent transform from current\&. But it's not always so\&. Sometimes you need to get layout element where this component (or it's parent) stored to play animation (for example)\&. \fP"
.ti -1c
.RI "void \fBRegisterSubComponent\fP (\fBWindowComponent\fP subComponent)"
.br
.RI "\fIRegisters the sub component\&. If you want to instantiate new component manualy but wants the window events - register this component here\&. \fP"
.ti -1c
.RI "void \fBUnregisterSubComponent\fP (\fBWindowComponent\fP subComponent)"
.br
.RI "\fIUnregisters the sub component\&. \fP"
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.RI "\fIRaises the init event\&. You can override this method but call it's base\&. \fP"
.ti -1c
.RI "override void \fBOnDeinit\fP ()"
.br
.RI "\fIRaises the deinit event\&. You can override this method but call it's base\&. \fP"
.ti -1c
.RI "override void \fBOnShowEnd\fP ()"
.br
.RI "\fIRaises the show end event\&. You can override this method but call it's base\&. \fP"
.ti -1c
.RI "override void \fBOnHideEnd\fP ()"
.br
.RI "\fIRaises the hide end event\&. You can override this method but call it's base\&. \fP"
.ti -1c
.RI "override void \fBOnShowBegin\fP (System\&.Action callback)"
.br
.RI "\fIRaises the show begin event\&. Wait while all sub components return the callback\&. You can override this method but call it's base\&. \fP"
.ti -1c
.RI "override void \fBOnHideBegin\fP (System\&.Action callback)"
.br
.RI "\fIRaises the hide begin event\&. Wait while all sub components return the callback\&. You can override this method but call it's base\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBautoRegisterSubComponents\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file WindowComponent\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBWindowLayoutBase\fP UnityEngine\&.UI\&.Windows\&.WindowComponent\&.GetLayoutRoot ()"

.PP
Gets the layout root\&. Basicaly it's the parent transform from current\&. But it's not always so\&. Sometimes you need to get layout element where this component (or it's parent) stored to play animation (for example)\&. 
.PP
\fBReturns:\fP
.RS 4
The layout root\&.
.RE
.PP

.PP
Definition at line 49 of file WindowComponent\&.cs\&.
.SS "\fBList\fP<\fBWindowComponent\fP> UnityEngine\&.UI\&.Windows\&.WindowComponent\&.GetSubComponents ()"

.PP
Gets the sub components\&. 
.PP
\fBReturns:\fP
.RS 4
The sub components\&.
.RE
.PP

.PP
Definition at line 21 of file WindowComponent\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.WindowComponent\&.OnDeinit ()\fC [virtual]\fP"

.PP
Raises the deinit event\&. You can override this method but call it's base\&. 
.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowComponentBase\fP\&.
.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Components\&.Tabs\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.LinkerComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.InputFieldComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonHoverComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonWithTipComponent\fP\&.
.PP
Definition at line 139 of file WindowComponent\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.WindowComponent\&.OnHideBegin (System\&.Action callback)\fC [virtual]\fP"

.PP
Raises the hide begin event\&. Wait while all sub components return the callback\&. You can override this method but call it's base\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcallback\fP Callback\&.
.RE
.PP

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowComponentBase\fP\&.
.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Components\&.List\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.LinkerComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.ProgressWithParticlesComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.ProgressComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonHoverComponent\fP\&.
.PP
Definition at line 180 of file WindowComponent\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.WindowComponent\&.OnHideEnd ()\fC [virtual]\fP"

.PP
Raises the hide end event\&. You can override this method but call it's base\&. 
.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowComponentBase\fP\&.
.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Components\&.LinkerComponent\fP\&.
.PP
Definition at line 155 of file WindowComponent\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.WindowComponent\&.OnInit ()\fC [virtual]\fP"

.PP
Raises the init event\&. You can override this method but call it's base\&. 
.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowComponentBase\fP\&.
.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.LinkerComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.ProgressComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.List\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.Tabs\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.ToggleComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonWithTipComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.ProgressWithParticlesComponent\fP\&.
.PP
Definition at line 131 of file WindowComponent\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.WindowComponent\&.OnShowBegin (System\&.Action callback)\fC [virtual]\fP"

.PP
Raises the show begin event\&. Wait while all sub components return the callback\&. You can override this method but call it's base\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcallback\fP Callback\&.
.RE
.PP

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowComponentBase\fP\&.
.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.LinkerComponent\fP\&.
.PP
Definition at line 163 of file WindowComponent\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.WindowComponent\&.OnShowEnd ()\fC [virtual]\fP"

.PP
Raises the show end event\&. You can override this method but call it's base\&. 
.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowComponentBase\fP\&.
.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Components\&.LinkerComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.ProgressWithParticlesComponent\fP\&.
.PP
Definition at line 147 of file WindowComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.WindowComponent\&.RegisterSubComponent (\fBWindowComponent\fP subComponent)"

.PP
Registers the sub component\&. If you want to instantiate new component manualy but wants the window events - register this component here\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsubComponent\fP Sub component\&.
.RE
.PP

.PP
Definition at line 60 of file WindowComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.WindowComponent\&.UnregisterSubComponent (\fBWindowComponent\fP subComponent)"

.PP
Unregisters the sub component\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsubComponent\fP Sub component\&.
.RE
.PP

.PP
Definition at line 96 of file WindowComponent\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool UnityEngine\&.UI\&.Windows\&.WindowComponent\&.autoRegisterSubComponents = true"

.PP
Definition at line 11 of file WindowComponent\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
