.TH "UnityEngine.UI.Windows.WindowModule" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.WindowModule \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.WindowLayoutBase\fP\&.
.PP
Inherited by \fBUnityEngine\&.UI\&.Windows\&.Modules\&.BackgroundCloseable\fP, \fBUnityEngine\&.UI\&.Windows\&.Modules\&.BackgroundLock\fP, and \fBUnityEngine\&.UI\&.Windows\&.Modules\&.CloseButton\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdefaultSortingOrder\fP"
.br
.ti -1c
.RI "bool \fBdefaultBackgroundLayer\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file WindowModule\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool UnityEngine\&.UI\&.Windows\&.WindowModule\&.defaultBackgroundLayer"

.PP
Definition at line 14 of file WindowModule\&.cs\&.
.SS "int UnityEngine\&.UI\&.Windows\&.WindowModule\&.defaultSortingOrder"

.PP
Definition at line 13 of file WindowModule\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
