.TH "UnityEngine.UI.Windows.WindowSystem.HistoryItem" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.WindowSystem.HistoryItem \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHistoryItem\fP (\fBWindowBase\fP \fBwindow\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBWindowBase\fP \fBwindow\fP"
.br
.ti -1c
.RI "\fBWindowObjectState\fP \fBstate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file WindowSystem\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEngine\&.UI\&.Windows\&.WindowSystem\&.HistoryItem\&.HistoryItem (\fBWindowBase\fP window)"

.PP
Definition at line 19 of file WindowSystem\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBWindowObjectState\fP UnityEngine\&.UI\&.Windows\&.WindowSystem\&.HistoryItem\&.state"

.PP
Definition at line 17 of file WindowSystem\&.cs\&.
.SS "\fBWindowBase\fP UnityEngine\&.UI\&.Windows\&.WindowSystem\&.HistoryItem\&.window"

.PP
Definition at line 16 of file WindowSystem\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
