.TH "UnityEngine.UI.Windows.Modules.Modules" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Modules.Modules \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBModuleInfo\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCreate\fP (\fBWindowBase\fP window, Transform modulesRoot)"
.br
.ti -1c
.RI "float \fBGetAnimationDuration\fP (bool forward)"
.br
.ti -1c
.RI "T \fBGet< T >\fP ()"
.br
.ti -1c
.RI "void \fBOnInit\fP ()"
.br
.ti -1c
.RI "void \fBOnDeinit\fP ()"
.br
.ti -1c
.RI "void \fBOnShowBegin\fP (System\&.Action callback)"
.br
.ti -1c
.RI "void \fBOnShowEnd\fP ()"
.br
.ti -1c
.RI "void \fBOnHideBegin\fP (System\&.Action callback)"
.br
.ti -1c
.RI "void \fBOnHideEnd\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file WindowBaseModules\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.Create (\fBWindowBase\fP window, Transform modulesRoot)"

.PP
Definition at line 132 of file WindowBaseModules\&.cs\&.
.SS "T UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.Get< T > ()"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIWindowModule\fP
.PP
Definition at line 160 of file WindowBaseModules\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.GetAnimationDuration (bool forward)"

.PP
Definition at line 142 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.OnDeinit ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 175 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.OnHideBegin (System\&.Action callback)"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 200 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.OnHideEnd ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 223 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.OnInit ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 174 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.OnShowBegin (System\&.Action callback)"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 176 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.OnShowEnd ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 199 of file WindowBaseModules\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
