.TH "UnityEngine.UI.Windows.Components.ImageComponent" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Components.ImageComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.WindowComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.IImageComponent\fP\&.
.PP
Inherited by \fBUnityEngine\&.UI\&.Windows\&.Components\&.DecoratorComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetImage\fP (Sprite sprite, bool withPivotsAndSize=false)"
.br
.ti -1c
.RI "void \fBSetImage\fP (Texture2D texture)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Image \fBimage\fP"
.br
.ti -1c
.RI "RawImage \fBrawImage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file ImageComponent\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.ImageComponent\&.SetImage (Sprite sprite, bool withPivotsAndSize = \fCfalse\fP)"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.Components\&.IImageComponent\fP\&.
.PP
Definition at line 17 of file ImageComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.ImageComponent\&.SetImage (Texture2D texture)"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.Components\&.IImageComponent\fP\&.
.PP
Definition at line 38 of file ImageComponent\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Image UnityEngine\&.UI\&.Windows\&.Components\&.ImageComponent\&.image"

.PP
Definition at line 12 of file ImageComponent\&.cs\&.
.SS "RawImage UnityEngine\&.UI\&.Windows\&.Components\&.ImageComponent\&.rawImage"

.PP
Definition at line 15 of file ImageComponent\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
