.TH "UnityEngine.UI.Windows.Plugins.FlowCompiler.Tpl" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Plugins.FlowCompiler.Tpl \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInfo\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBReplaceText\fP (string text, \fBInfo\fP oldInfo, \fBInfo\fP newInfo)"
.br
.ti -1c
.RI "static string \fBGetNamespace\fP ()"
.br
.ti -1c
.RI "static string \fBGetBaseClassName\fP (\fBFlowWindow\fP flowWindow)"
.br
.ti -1c
.RI "static string \fBGetDerivedClassName\fP (\fBFlowWindow\fP flowWindow)"
.br
.ti -1c
.RI "static string \fBGetNamespace\fP (\fBFlowWindow\fP window)"
.br
.ti -1c
.RI "static string \fBGenerateTransitionMethods\fP (\fBFlowWindow\fP window)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file FlowCompilerSystem\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static string UnityEngine\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.Tpl\&.GenerateTransitionMethods (\fBFlowWindow\fP window)\fC [static]\fP"

.PP
Definition at line 116 of file FlowCompilerSystem\&.cs\&.
.SS "static string UnityEngine\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.Tpl\&.GetBaseClassName (\fBFlowWindow\fP flowWindow)\fC [static]\fP"

.PP
Definition at line 98 of file FlowCompilerSystem\&.cs\&.
.SS "static string UnityEngine\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.Tpl\&.GetDerivedClassName (\fBFlowWindow\fP flowWindow)\fC [static]\fP"

.PP
Definition at line 104 of file FlowCompilerSystem\&.cs\&.
.SS "static string UnityEngine\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.Tpl\&.GetNamespace ()\fC [static]\fP"

.PP
Definition at line 92 of file FlowCompilerSystem\&.cs\&.
.SS "static string UnityEngine\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.Tpl\&.GetNamespace (\fBFlowWindow\fP window)\fC [static]\fP"

.PP
Definition at line 110 of file FlowCompilerSystem\&.cs\&.
.SS "static string UnityEngine\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.Tpl\&.ReplaceText (string text, \fBInfo\fP oldInfo, \fBInfo\fP newInfo)\fC [static]\fP"

.PP
Definition at line 86 of file FlowCompilerSystem\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
