.TH "UnityEngine.UI.Windows.Animations.WindowAnimationTransitionAlpha" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Animations.WindowAnimationTransitionAlpha \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBParameters\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBTransitionBase\&.ParametersBase\fP \fBGetDefaultInputParameters\fP ()"
.br
.ti -1c
.RI "override void \fBOnPlay\fP (\fBWindowBase\fP window, object tag, \fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root, bool forward, System\&.Action callback)"
.br
.ti -1c
.RI "override void \fBSetInState\fP (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)"
.br
.ti -1c
.RI "override void \fBSetOutState\fP (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)"
.br
.ti -1c
.RI "override void \fBSetResetState\fP (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBParameters\fP \fBdefaultInputParams\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file WindowAnimationTransitionAlpha\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBTransitionBase\&.ParametersBase\fP UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionAlpha\&.GetDefaultInputParameters ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\fP\&.
.PP
Definition at line 70 of file WindowAnimationTransitionAlpha\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionAlpha\&.OnPlay (\fBWindowBase\fP window, object tag, \fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root, bool forward, System\&.Action callback)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\fP\&.
.PP
Definition at line 76 of file WindowAnimationTransitionAlpha\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionAlpha\&.SetInState (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\fP\&.
.PP
Definition at line 103 of file WindowAnimationTransitionAlpha\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionAlpha\&.SetOutState (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\fP\&.
.PP
Definition at line 114 of file WindowAnimationTransitionAlpha\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionAlpha\&.SetResetState (\fBTransitionInputParameters\fP parameters, \fBWindowComponentBase\fP root)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\fP\&.
.PP
Definition at line 125 of file WindowAnimationTransitionAlpha\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBParameters\fP UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionAlpha\&.defaultInputParams"

.PP
Definition at line 68 of file WindowAnimationTransitionAlpha\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
