.TH "UnityEditor.UI.Windows.WindowComponentLibraryMenu" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.WindowComponentLibraryMenu \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBCreateComponent\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file WindowComponentLibraryMenu\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void UnityEditor\&.UI\&.Windows\&.WindowComponentLibraryMenu\&.CreateComponent ()\fC [static]\fP"

.PP
Definition at line 40 of file WindowComponentLibraryMenu\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
