.TH "UnityEngine.UI.Windows.WindowSystemSettings.Base" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.WindowSystemSettings.Base \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBminDepth\fP = 90f"
.br
.ti -1c
.RI "float \fBmaxDepth\fP = 98f"
.br
.ti -1c
.RI "int \fBpoolSize\fP = 100"
.br
.ti -1c
.RI "float \fBminZDepth\fP = 0f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file WindowSystemSettings\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float UnityEngine\&.UI\&.Windows\&.WindowSystemSettings\&.Base\&.maxDepth = 98f"

.PP
Definition at line 10 of file WindowSystemSettings\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.WindowSystemSettings\&.Base\&.minDepth = 90f"

.PP
Definition at line 9 of file WindowSystemSettings\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.WindowSystemSettings\&.Base\&.minZDepth = 0f"

.PP
Definition at line 13 of file WindowSystemSettings\&.cs\&.
.SS "int UnityEngine\&.UI\&.Windows\&.WindowSystemSettings\&.Base\&.poolSize = 100"

.PP
Definition at line 11 of file WindowSystemSettings\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
