.TH "UnityEditor.UI.Windows.Types.LayoutWindowTypeEditor" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Types.LayoutWindowTypeEditor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Editor, and \fBUnityEngine\&.UI\&.Windows\&.IPreviewEditor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInspectorGUI\fP ()"
.br
.ti -1c
.RI "override bool \fBHasPreviewGUI\fP ()"
.br
.ti -1c
.RI "override void \fBOnPreviewGUI\fP (Rect r, GUIStyle background)"
.br
.ti -1c
.RI "virtual void \fBOnPreviewGUI\fP (Color color, Rect r, GUIStyle background)"
.br
.ti -1c
.RI "virtual void \fBOnPreviewGUI\fP (Color color, Rect r, GUIStyle background, bool drawInfo, bool selectable)"
.br
.ti -1c
.RI "override void \fBOnPreviewSettings\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file LayoutWindowTypeEditor\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool UnityEditor\&.UI\&.Windows\&.Types\&.LayoutWindowTypeEditor\&.HasPreviewGUI ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IPreviewEditor\fP\&.
.PP
Definition at line 23 of file LayoutWindowTypeEditor\&.cs\&.
.SS "override void UnityEditor\&.UI\&.Windows\&.Types\&.LayoutWindowTypeEditor\&.OnInspectorGUI ()"

.PP
Definition at line 17 of file LayoutWindowTypeEditor\&.cs\&.
.SS "override void UnityEditor\&.UI\&.Windows\&.Types\&.LayoutWindowTypeEditor\&.OnPreviewGUI (Rect r, GUIStyle background)"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IPreviewEditor\fP\&.
.PP
Definition at line 29 of file LayoutWindowTypeEditor\&.cs\&.
.SS "virtual void UnityEditor\&.UI\&.Windows\&.Types\&.LayoutWindowTypeEditor\&.OnPreviewGUI (Color color, Rect r, GUIStyle background)\fC [virtual]\fP"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IPreviewEditor\fP\&.
.PP
Definition at line 35 of file LayoutWindowTypeEditor\&.cs\&.
.SS "virtual void UnityEditor\&.UI\&.Windows\&.Types\&.LayoutWindowTypeEditor\&.OnPreviewGUI (Color color, Rect r, GUIStyle background, bool drawInfo, bool selectable)\fC [virtual]\fP"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IPreviewEditor\fP\&.
.PP
Definition at line 43 of file LayoutWindowTypeEditor\&.cs\&.
.SS "override void UnityEditor\&.UI\&.Windows\&.Types\&.LayoutWindowTypeEditor\&.OnPreviewSettings ()"

.PP
Definition at line 90 of file LayoutWindowTypeEditor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
