.TH "UnityEditor.UI.Windows.WindowBaseModulesProperty" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.WindowBaseModulesProperty \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyDrawer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP (Rect position, SerializedProperty property, GUIContent label)"
.br
.ti -1c
.RI "override void \fBOnGUI\fP (Rect position, SerializedProperty property, GUIContent label)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file WindowBaseModulesProperty\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.UI\&.Windows\&.WindowBaseModulesProperty\&.Init (Rect position, SerializedProperty property, GUIContent label)"

.PP
Definition at line 15 of file WindowBaseModulesProperty\&.cs\&.
.SS "override void UnityEditor\&.UI\&.Windows\&.WindowBaseModulesProperty\&.OnGUI (Rect position, SerializedProperty property, GUIContent label)"

.PP
Definition at line 64 of file WindowBaseModulesProperty\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
