.TH "UnityEditor.UI.Windows.WindowComponentLibraryChooser" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.WindowComponentLibraryChooser \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits EditorWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBScan\fP ()"
.br
.ti -1c
.RI "void \fBUpdateSize\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBShow\fP (System\&.Action< \fBWindowComponentLibraryLinker\&.Item\fP > onSelect)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file WindowComponentLibraryChooser\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.UI\&.Windows\&.WindowComponentLibraryChooser\&.Scan ()"

.PP
Definition at line 45 of file WindowComponentLibraryChooser\&.cs\&.
.SS "static void UnityEditor\&.UI\&.Windows\&.WindowComponentLibraryChooser\&.Show (System\&.Action< \fBWindowComponentLibraryLinker\&.Item\fP > onSelect)\fC [static]\fP"

.PP
Definition at line 30 of file WindowComponentLibraryChooser\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.WindowComponentLibraryChooser\&.UpdateSize ()"

.PP
Definition at line 55 of file WindowComponentLibraryChooser\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
