.TH "UnityEditor.UI.Windows.Plugins.DevicePreview.DevicePreviewWindow" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.DevicePreview.DevicePreviewWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEditor\&.EditorWindowExt\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGameView\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnClose\fP ()"
.br
.ti -1c
.RI "void \fBValidate\fP ()"
.br
.ti -1c
.RI "override void \fBUpdate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDevicePreviewWindow\fP \fBShowEditor\fP (System\&.Action onClose)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGameView\fP \fBgameView\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file DevicePreviewWindow\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreviewWindow\&.OnClose ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEditor\&.EditorWindowExt\fP\&.
.PP
Definition at line 267 of file DevicePreviewWindow\&.cs\&.
.SS "static \fBDevicePreviewWindow\fP UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreviewWindow\&.ShowEditor (System\&.Action onClose)\fC [static]\fP"

.PP
Definition at line 248 of file DevicePreviewWindow\&.cs\&.
.SS "override void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreviewWindow\&.Update ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEditor\&.EditorWindowExt\fP\&.
.PP
Definition at line 289 of file DevicePreviewWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreviewWindow\&.Validate ()"

.PP
Definition at line 277 of file DevicePreviewWindow\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBGameView\fP UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreviewWindow\&.gameView"

.PP
Definition at line 333 of file DevicePreviewWindow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
