.TH "UnityEngine.UI.Windows.Extensions.FilterAttribute" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Extensions.FilterAttribute \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyAttribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFilterAttribute\fP (Type \fBtype\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly Type \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file FilterAttribute\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEngine\&.UI\&.Windows\&.Extensions\&.FilterAttribute\&.FilterAttribute (Type type)"

.PP
Definition at line 10 of file FilterAttribute\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly Type UnityEngine\&.UI\&.Windows\&.Extensions\&.FilterAttribute\&.type"

.PP
Definition at line 8 of file FilterAttribute\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
