.TH "UnityEngine.UI.Windows.WindowSystem.Settings" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.WindowSystem.Settings \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBWindowSystemSettings\fP \fBfile\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBminZDepth\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBminDepth\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBmaxDepth\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBpoolSize\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file WindowSystem\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBWindowSystemSettings\fP UnityEngine\&.UI\&.Windows\&.WindowSystem\&.Settings\&.file"

.PP
Definition at line 31 of file WindowSystem\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "float UnityEngine\&.UI\&.Windows\&.WindowSystem\&.Settings\&.maxDepth\fC [get]\fP"

.PP
Definition at line 53 of file WindowSystem\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.WindowSystem\&.Settings\&.minDepth\fC [get]\fP"

.PP
Definition at line 43 of file WindowSystem\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.WindowSystem\&.Settings\&.minZDepth\fC [get]\fP"

.PP
Definition at line 33 of file WindowSystem\&.cs\&.
.SS "int UnityEngine\&.UI\&.Windows\&.WindowSystem\&.Settings\&.poolSize\fC [get]\fP"

.PP
Definition at line 62 of file WindowSystem\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
