.TH "UnityEngine.UI.ButtonWithLabel" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.ButtonWithLabel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.ButtonWithReference\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBlabel\fP"
.br
.ti -1c
.RI "ColorBlock \fBlabelColor\fP = ColorBlock\&.defaultColorBlock"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDoStateTransition\fP (Selectable\&.SelectionState state, bool instant)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 6 of file ButtonWithLabel\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void UnityEngine\&.UI\&.ButtonWithLabel\&.DoStateTransition (Selectable\&.SelectionState state, bool instant)\fC [protected]\fP"

.PP
Definition at line 11 of file ButtonWithLabel\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Text UnityEngine\&.UI\&.ButtonWithLabel\&.label"

.PP
Definition at line 8 of file ButtonWithLabel\&.cs\&.
.SS "ColorBlock UnityEngine\&.UI\&.ButtonWithLabel\&.labelColor = ColorBlock\&.defaultColorBlock"

.PP
Definition at line 9 of file ButtonWithLabel\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
