.TH "UnityEditor.UI.Windows.Plugins.FlowCompiler.FlowCompilerWizard" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.FlowCompiler.FlowCompilerWizard \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEditor\&.EditorWindowExt\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBOnGUI\fP ()"
.br
.ti -1c
.RI "void \fBDrawSteps\fP ()"
.br
.ti -1c
.RI "void \fBDrawPart4\fP ()"
.br
.ti -1c
.RI "void \fBDrawPart3\fP ()"
.br
.ti -1c
.RI "void \fBDrawPart2\fP ()"
.br
.ti -1c
.RI "void \fBDrawPart1\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFlowCompilerWizard\fP \fBShowEditor\fP (System\&.Action onClose)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static object \fBcompilationSync\fP = null"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 11 of file FlowCompilerWizard\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompilerWizard\&.DrawPart1 ()"

.PP
Definition at line 325 of file FlowCompilerWizard\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompilerWizard\&.DrawPart2 ()"

.PP
Definition at line 226 of file FlowCompilerWizard\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompilerWizard\&.DrawPart3 ()"

.PP
Definition at line 204 of file FlowCompilerWizard\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompilerWizard\&.DrawPart4 ()"

.PP
Definition at line 190 of file FlowCompilerWizard\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompilerWizard\&.DrawSteps ()"

.PP
Definition at line 175 of file FlowCompilerWizard\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompilerWizard\&.OnGUI ()"

.PP
Definition at line 91 of file FlowCompilerWizard\&.cs\&.
.SS "static \fBFlowCompilerWizard\fP UnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompilerWizard\&.ShowEditor (System\&.Action onClose)\fC [static]\fP"

.PP
Definition at line 15 of file FlowCompilerWizard\&.cs\&.
.SS "override void UnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompilerWizard\&.Update ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEditor\&.EditorWindowExt\fP\&.
.PP
Definition at line 72 of file FlowCompilerWizard\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "object UnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompilerWizard\&.compilationSync = null\fC [static]\fP"

.PP
Definition at line 13 of file FlowCompilerWizard\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
