.TH "UnityEngine.UI.Windows.WindowLayoutRoot" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.WindowLayoutRoot \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMode\fP : byte { \fBMode\&.None\fP, \fBMode\&.FlexibleWidth\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRebuild\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMode\fP \fBmode\fP = Mode\&.None"
.br
.ti -1c
.RI "float \fBminWidth\fP = 1024f"
.br
.ti -1c
.RI "float \fBmaxWidth\fP = 1920f"
.br
.ti -1c
.RI "float \fBmargin\fP = 100f"
.br
.ti -1c
.RI "Rect \fBeditorRect\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "RectTransform \fBrectTransform\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file WindowLayoutRoot\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBUnityEngine\&.UI\&.Windows\&.WindowLayoutRoot\&.Mode\fP : byte"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
.TP
\fB\fIFlexibleWidth \fP\fP
.PP
Definition at line 9 of file WindowLayoutRoot\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.UI\&.Windows\&.WindowLayoutRoot\&.Rebuild ()"

.PP
Definition at line 36 of file WindowLayoutRoot\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Rect UnityEngine\&.UI\&.Windows\&.WindowLayoutRoot\&.editorRect"

.PP
Definition at line 34 of file WindowLayoutRoot\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.WindowLayoutRoot\&.margin = 100f"

.PP
Definition at line 31 of file WindowLayoutRoot\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.WindowLayoutRoot\&.maxWidth = 1920f"

.PP
Definition at line 30 of file WindowLayoutRoot\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.WindowLayoutRoot\&.minWidth = 1024f"

.PP
Definition at line 29 of file WindowLayoutRoot\&.cs\&.
.SS "\fBMode\fP UnityEngine\&.UI\&.Windows\&.WindowLayoutRoot\&.mode = Mode\&.None"

.PP
Definition at line 27 of file WindowLayoutRoot\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "RectTransform UnityEngine\&.UI\&.Windows\&.WindowLayoutRoot\&.rectTransform\fC [get]\fP"

.PP
Definition at line 15 of file WindowLayoutRoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
