.TH "UnityEngine.UI.Windows.WindowBase" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.WindowBase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.WindowObject\fP, and \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Inherited by \fBUnityEngine\&.UI\&.Windows\&.Types\&.LayoutWindowType\fP, and \fBUnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindowObjectState\fP \fBGetState\fP ()"
.br
.RI "\fIGets the state\&. \fP"
.ti -1c
.RI "virtual string \fBGetSortingLayerName\fP ()"
.br
.RI "\fIGets the name of the sorting layer\&. \fP"
.ti -1c
.RI "virtual int \fBGetSortingOrder\fP ()"
.br
.RI "\fIGets the sorting order\&. \fP"
.ti -1c
.RI "float \fBGetAnimationDuration\fP (bool forward)"
.br
.RI "\fIGets the duration of the animation\&. \fP"
.ti -1c
.RI "virtual float \fBGetTransitionAnimationDuration\fP (bool forward)"
.br
.RI "\fIGets the duration of the transition animation\&. \fP"
.ti -1c
.RI "virtual float \fBGetModuleAnimationDuration\fP (bool forward)"
.br
.RI "\fIGets the duration of the module animation\&. \fP"
.ti -1c
.RI "T \fBGetModule< T >\fP ()"
.br
.RI "\fIGets the module\&. \fP"
.ti -1c
.RI "void \fBShow\fP ()"
.br
.RI "\fIShow this instance\&. \fP"
.ti -1c
.RI "void \fBShow\fP (System\&.Action onShowEnd)"
.br
.RI "\fIShow the specified onShowEnd\&. \fP"
.ti -1c
.RI "bool \fBHide\fP ()"
.br
.RI "\fIHide this instance\&. \fP"
.ti -1c
.RI "bool \fBHide\fP (System\&.Action onHideEnd)"
.br
.RI "\fIHide the specified onHideEnd\&. Wait while all components, animations, events and modules return the callback\&. \fP"
.ti -1c
.RI "virtual float \fBGetLayoutAnimationDuration\fP (bool forward)"
.br
.RI "\fIGets the duration of the layout animation\&. \fP"
.ti -1c
.RI "virtual void \fBOnParametersPass\fP ()"
.br
.RI "\fIRaises the parameters pass event\&. Don't override this method - use your own\&. Window will use reflection to determine your method\&. Example: OnParametersPass(T1 param1, T2 param2, etc\&.) You can use any types in any order and call window with them\&. \fP"
.ti -1c
.RI "virtual void \fBOnEmptyPass\fP ()"
.br
.RI "\fIRaises the empty pass event\&. \fP"
.ti -1c
.RI "virtual void \fBOnInit\fP ()"
.br
.RI "\fIRaises the init event\&. \fP"
.ti -1c
.RI "virtual void \fBOnDeinit\fP ()"
.br
.RI "\fIRaises the deinit event\&. \fP"
.ti -1c
.RI "virtual void \fBOnShowBegin\fP (System\&.Action callback)"
.br
.RI "\fIRaises the show begin event\&. \fP"
.ti -1c
.RI "virtual void \fBOnShowEnd\fP ()"
.br
.RI "\fIRaises the show end event\&. \fP"
.ti -1c
.RI "virtual void \fBOnHideBegin\fP (System\&.Action callback)"
.br
.RI "\fIRaises the hide begin event\&. \fP"
.ti -1c
.RI "virtual void \fBOnHideEnd\fP ()"
.br
.RI "\fIRaises the hide end event\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Camera \fBworkCamera\fP"
.br
.ti -1c
.RI "\fBPreferences\fP \fBpreferences\fP"
.br
.ti -1c
.RI "\fBTransition\fP \fBtransition\fP"
.br
.ti -1c
.RI "\fBModules\&.Modules\fP \fBmodules\fP"
.br
.ti -1c
.RI "\fBEvents\fP \fBevents\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual Transform \fBGetLayoutRoot\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnLayoutInit\fP (float depth, int raycastPriority, int orderInLayer)"
.br
.RI "\fIRaises the layout init event\&. \fP"
.ti -1c
.RI "virtual void \fBOnLayoutDeinit\fP ()"
.br
.RI "\fIRaises the layout deinit event\&. \fP"
.ti -1c
.RI "virtual void \fBOnLayoutShowBegin\fP (System\&.Action callback)"
.br
.RI "\fIRaises the layout show begin event\&. \fP"
.ti -1c
.RI "virtual void \fBOnLayoutShowEnd\fP ()"
.br
.RI "\fIRaises the layout show end event\&. \fP"
.ti -1c
.RI "virtual void \fBOnLayoutHideBegin\fP (System\&.Action callback)"
.br
.RI "\fIRaises the layout hide begin event\&. \fP"
.ti -1c
.RI "virtual void \fBOnLayoutHideEnd\fP ()"
.br
.RI "\fIRaises the layout hide end event\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file WindowBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "float UnityEngine\&.UI\&.Windows\&.WindowBase\&.GetAnimationDuration (bool forward)"

.PP
Gets the duration of the animation\&. 
.PP
\fBReturns:\fP
.RS 4
The animation duration\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIforward\fP If set to \fCtrue\fP forward\&.
.RE
.PP

.PP
Definition at line 190 of file WindowBase\&.cs\&.
.SS "virtual float UnityEngine\&.UI\&.Windows\&.WindowBase\&.GetLayoutAnimationDuration (bool forward)\fC [virtual]\fP"

.PP
Gets the duration of the layout animation\&. 
.PP
\fBReturns:\fP
.RS 4
The layout animation duration\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIforward\fP If set to \fCtrue\fP forward\&.
.RE
.PP

.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\fP, and \fBUnityEngine\&.UI\&.Windows\&.Types\&.LayoutWindowType\fP\&.
.PP
Definition at line 358 of file WindowBase\&.cs\&.
.SS "virtual Transform UnityEngine\&.UI\&.Windows\&.WindowBase\&.GetLayoutRoot ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\fP, and \fBUnityEngine\&.UI\&.Windows\&.Types\&.LayoutWindowType\fP\&.
.PP
Definition at line 351 of file WindowBase\&.cs\&.
.SS "T UnityEngine\&.UI\&.Windows\&.WindowBase\&.GetModule< T > ()"

.PP
Gets the module\&. 
.PP
\fBReturns:\fP
.RS 4
The module\&.
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The 1st type parameter\&.
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIWindowModule\fP
.PP
Definition at line 227 of file WindowBase\&.cs\&.
.SS "virtual float UnityEngine\&.UI\&.Windows\&.WindowBase\&.GetModuleAnimationDuration (bool forward)\fC [virtual]\fP"

.PP
Gets the duration of the module animation\&. 
.PP
\fBReturns:\fP
.RS 4
The module animation duration\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIforward\fP If set to \fCtrue\fP forward\&.
.RE
.PP

.PP
Definition at line 216 of file WindowBase\&.cs\&.
.SS "virtual string UnityEngine\&.UI\&.Windows\&.WindowBase\&.GetSortingLayerName ()\fC [virtual]\fP"

.PP
Gets the name of the sorting layer\&. 
.PP
\fBReturns:\fP
.RS 4
The sorting layer name\&.
.RE
.PP

.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Types\&.LayoutWindowType\fP\&.
.PP
Definition at line 169 of file WindowBase\&.cs\&.
.SS "virtual int UnityEngine\&.UI\&.Windows\&.WindowBase\&.GetSortingOrder ()\fC [virtual]\fP"

.PP
Gets the sorting order\&. 
.PP
\fBReturns:\fP
.RS 4
The sorting order\&.
.RE
.PP

.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Types\&.LayoutWindowType\fP\&.
.PP
Definition at line 179 of file WindowBase\&.cs\&.
.SS "\fBWindowObjectState\fP UnityEngine\&.UI\&.Windows\&.WindowBase\&.GetState ()"

.PP
Gets the state\&. 
.PP
\fBReturns:\fP
.RS 4
The state\&.
.RE
.PP

.PP
Definition at line 126 of file WindowBase\&.cs\&.
.SS "virtual float UnityEngine\&.UI\&.Windows\&.WindowBase\&.GetTransitionAnimationDuration (bool forward)\fC [virtual]\fP"

.PP
Gets the duration of the transition animation\&. 
.PP
\fBReturns:\fP
.RS 4
The transition animation duration\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIforward\fP If set to \fCtrue\fP forward\&.
.RE
.PP

.PP
Definition at line 205 of file WindowBase\&.cs\&.
.SS "bool UnityEngine\&.UI\&.Windows\&.WindowBase\&.Hide ()"

.PP
Hide this instance\&. 
.PP
Definition at line 285 of file WindowBase\&.cs\&.
.SS "bool UnityEngine\&.UI\&.Windows\&.WindowBase\&.Hide (System\&.Action onHideEnd)"

.PP
Hide the specified onHideEnd\&. Wait while all components, animations, events and modules return the callback\&. 
.PP
\fBParameters:\fP
.RS 4
\fIonHideEnd\fP On hide end\&.
.RE
.PP

.PP
Definition at line 296 of file WindowBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowBase\&.OnDeinit ()\fC [virtual]\fP"

.PP
Raises the deinit event\&. 
.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 421 of file WindowBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowBase\&.OnEmptyPass ()\fC [virtual]\fP"

.PP
Raises the empty pass event\&. 
.PP
Definition at line 411 of file WindowBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowBase\&.OnHideBegin (System\&.Action callback)\fC [virtual]\fP"

.PP
Raises the hide begin event\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcallback\fP Callback\&.
.RE
.PP

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 438 of file WindowBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowBase\&.OnHideEnd ()\fC [virtual]\fP"

.PP
Raises the hide end event\&. 
.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 443 of file WindowBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowBase\&.OnInit ()\fC [virtual]\fP"

.PP
Raises the init event\&. 
.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 416 of file WindowBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowBase\&.OnLayoutDeinit ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the layout deinit event\&. 
.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Types\&.LayoutWindowType\fP, and \fBUnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\fP\&.
.PP
Definition at line 375 of file WindowBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowBase\&.OnLayoutHideBegin (System\&.Action callback)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the layout hide begin event\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcallback\fP Callback\&.
.RE
.PP

.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\fP, and \fBUnityEngine\&.UI\&.Windows\&.Types\&.LayoutWindowType\fP\&.
.PP
Definition at line 392 of file WindowBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowBase\&.OnLayoutHideEnd ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the layout hide end event\&. 
.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Types\&.LayoutWindowType\fP, and \fBUnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\fP\&.
.PP
Definition at line 397 of file WindowBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowBase\&.OnLayoutInit (float depth, int raycastPriority, int orderInLayer)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the layout init event\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdepth\fP Depth\&.
.br
\fIraycastPriority\fP Raycast priority\&.
.br
\fIorderInLayer\fP Order in layer\&.
.RE
.PP

.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Types\&.LayoutWindowType\fP, and \fBUnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\fP\&.
.PP
Definition at line 370 of file WindowBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowBase\&.OnLayoutShowBegin (System\&.Action callback)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the layout show begin event\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcallback\fP Callback\&.
.RE
.PP

.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\fP, and \fBUnityEngine\&.UI\&.Windows\&.Types\&.LayoutWindowType\fP\&.
.PP
Definition at line 381 of file WindowBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowBase\&.OnLayoutShowEnd ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the layout show end event\&. 
.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Types\&.LayoutWindowType\fP, and \fBUnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\fP\&.
.PP
Definition at line 386 of file WindowBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowBase\&.OnParametersPass ()\fC [virtual]\fP"

.PP
Raises the parameters pass event\&. Don't override this method - use your own\&. Window will use reflection to determine your method\&. Example: OnParametersPass(T1 param1, T2 param2, etc\&.) You can use any types in any order and call window with them\&. 
.PP
Definition at line 406 of file WindowBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowBase\&.OnShowBegin (System\&.Action callback)\fC [virtual]\fP"

.PP
Raises the show begin event\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcallback\fP Callback\&.
.RE
.PP

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 427 of file WindowBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowBase\&.OnShowEnd ()\fC [virtual]\fP"

.PP
Raises the show end event\&. 
.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 432 of file WindowBase\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.WindowBase\&.Show ()"

.PP
Show this instance\&. 
.PP
Definition at line 236 of file WindowBase\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.WindowBase\&.Show (System\&.Action onShowEnd)"

.PP
Show the specified onShowEnd\&. 
.PP
\fBParameters:\fP
.RS 4
\fIonShowEnd\fP On show end\&.
.RE
.PP

.PP
Definition at line 246 of file WindowBase\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBEvents\fP UnityEngine\&.UI\&.Windows\&.WindowBase\&.events"

.PP
Definition at line 36 of file WindowBase\&.cs\&.
.SS "\fBModules\&.Modules\fP UnityEngine\&.UI\&.Windows\&.WindowBase\&.modules"

.PP
Definition at line 35 of file WindowBase\&.cs\&.
.SS "\fBPreferences\fP UnityEngine\&.UI\&.Windows\&.WindowBase\&.preferences"

.PP
Definition at line 33 of file WindowBase\&.cs\&.
.SS "\fBTransition\fP UnityEngine\&.UI\&.Windows\&.WindowBase\&.transition"

.PP
Definition at line 34 of file WindowBase\&.cs\&.
.SS "Camera UnityEngine\&.UI\&.Windows\&.WindowBase\&.workCamera"

.PP
Definition at line 31 of file WindowBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
