.TH "UnityEngine.UI.Windows.Animations.WindowTransitionBasic.Parameters" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Animations.WindowTransitionBasic.Parameters \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.ParametersBase\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBState\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParameters\fP (\fBTransitionBase\&.ParametersBase\fP baseDefaults)"
.br
.ti -1c
.RI "override void \fBSetup\fP (\fBTransitionBase\&.ParametersBase\fP defaults)"
.br
.ti -1c
.RI "float \fBGetIn\fP ()"
.br
.ti -1c
.RI "float \fBGetOut\fP ()"
.br
.ti -1c
.RI "float \fBGetReset\fP ()"
.br
.ti -1c
.RI "float \fBGetResult\fP (bool forward)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Material \fBmaterial\fP"
.br
.ti -1c
.RI "\fBState\fP \fBresetState\fP"
.br
.ti -1c
.RI "\fBState\fP \fBinState\fP"
.br
.ti -1c
.RI "\fBState\fP \fBoutState\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file WindowTransitionBasic\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.Parameters\&.Parameters (\fBTransitionBase\&.ParametersBase\fP baseDefaults)"

.PP
Definition at line 11 of file WindowTransitionBasic\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "float UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.Parameters\&.GetIn ()"

.PP
Definition at line 40 of file WindowTransitionBasic\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.Parameters\&.GetOut ()"

.PP
Definition at line 46 of file WindowTransitionBasic\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.Parameters\&.GetReset ()"

.PP
Definition at line 52 of file WindowTransitionBasic\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.Parameters\&.GetResult (bool forward)"

.PP
Definition at line 58 of file WindowTransitionBasic\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.Parameters\&.Setup (\fBTransitionBase\&.ParametersBase\fP defaults)"

.PP
Definition at line 26 of file WindowTransitionBasic\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBState\fP UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.Parameters\&.inState"

.PP
Definition at line 23 of file WindowTransitionBasic\&.cs\&.
.SS "Material UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.Parameters\&.material"

.PP
Definition at line 20 of file WindowTransitionBasic\&.cs\&.
.SS "\fBState\fP UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.Parameters\&.outState"

.PP
Definition at line 24 of file WindowTransitionBasic\&.cs\&.
.SS "\fBState\fP UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasic\&.Parameters\&.resetState"

.PP
Definition at line 22 of file WindowTransitionBasic\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
