.TH "UnityEditor.UI.Windows.Plugins.DevicePreview.Parser" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.DevicePreview.Parser \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBCollect\fP (bool forced=true)"
.br
.ti -1c
.RI "static int \fBConvertInchesToPPI\fP (float inches, int width, int height)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static List< \fBDeviceInfo\fP > \fBpopular\fP = new List<\fBDeviceInfo\fP>()"
.br
.ti -1c
.RI "static List< \fBDeviceInfo\fP > \fBp720\fP = new List<\fBDeviceInfo\fP>()"
.br
.ti -1c
.RI "static List< \fBDeviceInfo\fP > \fBp1080\fP = new List<\fBDeviceInfo\fP>()"
.br
.ti -1c
.RI "static List< \fBDeviceInfo\fP > \fBp1440\fP = new List<\fBDeviceInfo\fP>()"
.br
.ti -1c
.RI "static Dictionary< string, List< \fBDeviceInfo\fP > > \fBmanufacturerToDevices\fP = new Dictionary<string, List<\fBDeviceInfo\fP>>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 65 of file DevicePreviewParser\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Parser\&.Collect (bool forced = \fCtrue\fP)\fC [static]\fP"

.PP
Definition at line 73 of file DevicePreviewParser\&.cs\&.
.SS "static int UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Parser\&.ConvertInchesToPPI (float inches, int width, int height)\fC [static]\fP"

.PP
Definition at line 159 of file DevicePreviewParser\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<string, List<\fBDeviceInfo\fP> > UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Parser\&.manufacturerToDevices = new Dictionary<string, List<\fBDeviceInfo\fP>>()\fC [static]\fP"

.PP
Definition at line 71 of file DevicePreviewParser\&.cs\&.
.SS "List<\fBDeviceInfo\fP> UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Parser\&.p1080 = new List<\fBDeviceInfo\fP>()\fC [static]\fP"

.PP
Definition at line 69 of file DevicePreviewParser\&.cs\&.
.SS "List<\fBDeviceInfo\fP> UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Parser\&.p1440 = new List<\fBDeviceInfo\fP>()\fC [static]\fP"

.PP
Definition at line 70 of file DevicePreviewParser\&.cs\&.
.SS "List<\fBDeviceInfo\fP> UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Parser\&.p720 = new List<\fBDeviceInfo\fP>()\fC [static]\fP"

.PP
Definition at line 68 of file DevicePreviewParser\&.cs\&.
.SS "List<\fBDeviceInfo\fP> UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.Parser\&.popular = new List<\fBDeviceInfo\fP>()\fC [static]\fP"

.PP
Definition at line 67 of file DevicePreviewParser\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
