.TH "UnityEngine.UI.Windows.Components.PopupComponent.State" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Components.PopupComponent.State \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBState\fP (RectTransform \fBrect\fP, \fBList\fP \fBlist\fP, Vector2 \fBanchorMin\fP, Vector2 \fBanchorMax\fP, bool \fBreverse\fP)"
.br
.ti -1c
.RI "void \fBSet\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RectTransform \fBrect\fP"
.br
.ti -1c
.RI "\fBList\fP \fBlist\fP"
.br
.ti -1c
.RI "bool \fBreverse\fP"
.br
.ti -1c
.RI "Vector2 \fBanchorMin\fP"
.br
.ti -1c
.RI "Vector2 \fBanchorMax\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file PopupComponent\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.State\&.State (RectTransform rect, \fBList\fP list, Vector2 anchorMin, Vector2 anchorMax, bool reverse)"

.PP
Definition at line 30 of file PopupComponent\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.State\&.Set ()"

.PP
Definition at line 41 of file PopupComponent\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector2 UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.State\&.anchorMax"

.PP
Definition at line 28 of file PopupComponent\&.cs\&.
.SS "Vector2 UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.State\&.anchorMin"

.PP
Definition at line 27 of file PopupComponent\&.cs\&.
.SS "\fBList\fP UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.State\&.list"

.PP
Definition at line 24 of file PopupComponent\&.cs\&.
.SS "RectTransform UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.State\&.rect"

.PP
Definition at line 23 of file PopupComponent\&.cs\&.
.SS "bool UnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\&.State\&.reverse"

.PP
Definition at line 25 of file PopupComponent\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
