.TH "UnityEngine.UI.Windows.Extensions.FilterDrawer" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Extensions.FilterDrawer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyDrawer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override float \fBGetPropertyHeight\fP (SerializedProperty property, GUIContent label)"
.br
.ti -1c
.RI "override void \fBOnGUI\fP (Rect position, SerializedProperty property, GUIContent label)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file FilterAttributeDrawer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override float UnityEngine\&.UI\&.Windows\&.Extensions\&.FilterDrawer\&.GetPropertyHeight (SerializedProperty property, GUIContent label)"

.PP
Definition at line 11 of file FilterAttributeDrawer\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Extensions\&.FilterDrawer\&.OnGUI (Rect position, SerializedProperty property, GUIContent label)"

.PP
Definition at line 17 of file FilterAttributeDrawer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
