.TH "UnityEditor.UI.Windows.Plugins.Flow.Editors.FlowInspectorWindow" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.Flow.Editors.FlowInspectorWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEditor\&.EditorWindowExt\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float \fBGetWidth\fP ()"
.br
.ti -1c
.RI "new void \fBFocus\fP ()"
.br
.ti -1c
.RI "void \fBOnSelected\fP (GameObject go)"
.br
.ti -1c
.RI "void \fBShowView\fP ()"
.br
.ti -1c
.RI "void \fBHideView\fP ()"
.br
.ti -1c
.RI "void \fBUpdateSize\fP (float \fBprogress\fP)"
.br
.ti -1c
.RI "new void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBOnGUI\fP ()"
.br
.ti -1c
.RI "override void \fBOnClose\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFlowSystemEditorWindow\fP \fBrootWindow\fP"
.br
.ti -1c
.RI "const float \fBMIN_WIDTH\fP = 275f"
.br
.ti -1c
.RI "const float \fBMAX_WIDTH\fP = 350f"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file FlowInspectorWindow\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "new void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowInspectorWindow\&.Focus ()"

.PP
Definition at line 24 of file FlowInspectorWindow\&.cs\&.
.SS "float UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowInspectorWindow\&.GetWidth ()"

.PP
Definition at line 18 of file FlowInspectorWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowInspectorWindow\&.HideView ()"

.PP
Definition at line 82 of file FlowInspectorWindow\&.cs\&.
.SS "override void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowInspectorWindow\&.OnClose ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEditor\&.EditorWindowExt\fP\&.
.PP
Definition at line 200 of file FlowInspectorWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowInspectorWindow\&.OnGUI ()"

.PP
Definition at line 163 of file FlowInspectorWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowInspectorWindow\&.OnSelected (GameObject go)"

.PP
Definition at line 36 of file FlowInspectorWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowInspectorWindow\&.ShowView ()"
FlowSystem\&.GetData()\&.editorWindowAsPopup; 
.PP
Definition at line 60 of file FlowInspectorWindow\&.cs\&.
.SS "new void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowInspectorWindow\&.Update ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEditor\&.EditorWindowExt\fP\&.
.PP
Definition at line 100 of file FlowInspectorWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowInspectorWindow\&.UpdateSize (float progress)"

.PP
Definition at line 88 of file FlowInspectorWindow\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const float UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowInspectorWindow\&.MAX_WIDTH = 350f"

.PP
Definition at line 16 of file FlowInspectorWindow\&.cs\&.
.SS "const float UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowInspectorWindow\&.MIN_WIDTH = 275f"

.PP
Definition at line 15 of file FlowInspectorWindow\&.cs\&.
.SS "\fBFlowSystemEditorWindow\fP UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowInspectorWindow\&.rootWindow"

.PP
Definition at line 10 of file FlowInspectorWindow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
