.TH "UnityEngine.UI.Windows.Animations.TransitionInputParameters" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Animations.TransitionInputParameters \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionAlphaParameters\fP, \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionSlideParameters\fP, and \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasicParameters\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSetDefaultParameters\fP (\fBTransitionBase\&.ParametersBase\fP parameters)"
.br
.ti -1c
.RI "virtual T \fBGetParameters< T >\fP ()"
.br
.ti -1c
.RI "virtual \fBTransitionBase\&.ParametersBase\fP \fBGetParameters\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBuseDefault\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file TransitionInputParameters\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBTransitionBase\&.ParametersBase\fP UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionInputParameters\&.GetParameters ()\fC [virtual]\fP"

.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionAlphaParameters\fP, \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionSlideParameters\fP, and \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasicParameters\fP\&.
.PP
Definition at line 22 of file TransitionInputParameters\&.cs\&.
.SS "virtual T \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionInputParameters\&.GetParameters\fP< T > ()\fC [virtual]\fP"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fITransitionBase\&.ParametersBase\fP
.PP
Definition at line 16 of file TransitionInputParameters\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionInputParameters\&.SetDefaultParameters (\fBTransitionBase\&.ParametersBase\fP parameters)\fC [virtual]\fP"

.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionAlphaParameters\fP, \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionSlideParameters\fP, and \fBUnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasicParameters\fP\&.
.PP
Definition at line 10 of file TransitionInputParameters\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool UnityEngine\&.UI\&.Windows\&.Animations\&.TransitionInputParameters\&.useDefault = true"

.PP
Definition at line 8 of file TransitionInputParameters\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
