.TH "UnityEngine.UI.Windows.Components.ButtonWithTextComponent" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Components.ButtonWithTextComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonWithImageComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.ITextComponent\fP\&.
.PP
Inherited by \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonHoverComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.ToggleItemComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetValue\fP (int value, \fBTextComponent\&.ValueFormat\fP format=TextComponent\&.ValueFormat\&.None)"
.br
.ti -1c
.RI "string \fBGetText\fP ()"
.br
.ti -1c
.RI "void \fBSetText\fP (string \fBtext\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBtext\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file ButtonWithTextComponent\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "string UnityEngine\&.UI\&.Windows\&.Components\&.ButtonWithTextComponent\&.GetText ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.Components\&.ITextComponent\fP\&.
.PP
Definition at line 19 of file ButtonWithTextComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.ButtonWithTextComponent\&.SetText (string text)"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.Components\&.ITextComponent\fP\&.
.PP
Definition at line 25 of file ButtonWithTextComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.ButtonWithTextComponent\&.SetValue (int value, \fBTextComponent\&.ValueFormat\fP format = \fCTextComponent\&.ValueFormat\&.None\fP)"

.PP
Definition at line 13 of file ButtonWithTextComponent\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Text UnityEngine\&.UI\&.Windows\&.Components\&.ButtonWithTextComponent\&.text"

.PP
Definition at line 11 of file ButtonWithTextComponent\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
