.TH "UnityEditor.EditorWindowExt" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.EditorWindowExt \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits EditorWindow\&.
.PP
Inherited by \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreviewWindow\fP, \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowGameViewRenderWindow\fP, \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowGameViewWindow\fP, \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowHierarchyWindow\fP, \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowInspectorWindow\fP, \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSystemEditorWindow\fP, and \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompilerWizard\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnActive\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnInactive\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnClose\fP ()"
.br
.ti -1c
.RI "void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "void \fBOnDestroy\fP ()"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP ()"
.br
.ti -1c
.RI "bool \fBIsVisible\fP ()"
.br
.ti -1c
.RI "void \fBDrawProgress\fP (float \fBprogress\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "float \fBprogress\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 101 of file FlowEditorWindowExt\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.EditorWindowExt\&.DrawProgress (float progress)"

.PP
Definition at line 174 of file FlowEditorWindowExt\&.cs\&.
.SS "bool UnityEditor\&.EditorWindowExt\&.IsVisible ()"

.PP
Definition at line 165 of file FlowEditorWindowExt\&.cs\&.
.SS "virtual void UnityEditor\&.EditorWindowExt\&.OnActive ()\fC [virtual]\fP"

.PP
Reimplemented in \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSystemEditorWindow\fP\&.
.PP
Definition at line 106 of file FlowEditorWindowExt\&.cs\&.
.SS "virtual void UnityEditor\&.EditorWindowExt\&.OnClose ()\fC [virtual]\fP"

.PP
Reimplemented in \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowGameViewWindow\fP, \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowHierarchyWindow\fP, \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreviewWindow\fP, \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowInspectorWindow\fP, \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowGameViewRenderWindow\fP, and \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSystemEditorWindow\fP\&.
.PP
Definition at line 108 of file FlowEditorWindowExt\&.cs\&.
.SS "void UnityEditor\&.EditorWindowExt\&.OnDestroy ()"

.PP
Definition at line 124 of file FlowEditorWindowExt\&.cs\&.
.SS "void UnityEditor\&.EditorWindowExt\&.OnDisable ()"

.PP
Definition at line 117 of file FlowEditorWindowExt\&.cs\&.
.SS "void UnityEditor\&.EditorWindowExt\&.OnEnable ()"

.PP
Definition at line 110 of file FlowEditorWindowExt\&.cs\&.
.SS "virtual void UnityEditor\&.EditorWindowExt\&.OnInactive ()\fC [virtual]\fP"

.PP
Reimplemented in \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSystemEditorWindow\fP\&.
.PP
Definition at line 107 of file FlowEditorWindowExt\&.cs\&.
.SS "virtual void UnityEditor\&.EditorWindowExt\&.Update ()\fC [virtual]\fP"

.PP
Reimplemented in \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreviewWindow\fP, \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowGameViewWindow\fP, \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSystemEditorWindow\fP, \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowInspectorWindow\fP, \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowGameViewRenderWindow\fP, \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowHierarchyWindow\fP, and \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompilerWizard\fP\&.
.PP
Definition at line 131 of file FlowEditorWindowExt\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float UnityEditor\&.EditorWindowExt\&.progress\fC [protected]\fP"

.PP
Definition at line 173 of file FlowEditorWindowExt\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
