.TH "UnityEngine.UI.Windows.Modules.Modules.ModuleInfo" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Modules.Modules.ModuleInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModuleInfo\fP (\fBWindowModule\fP \fBmoduleSource\fP, int \fBsortingOrder\fP, bool \fBbackgroundLayer\fP)"
.br
.ti -1c
.RI "void \fBCreate\fP (\fBWindowBase\fP window, Transform modulesRoot)"
.br
.ti -1c
.RI "float \fBGetDuration\fP (bool forward)"
.br
.ti -1c
.RI "T \fBGet< T >\fP ()"
.br
.ti -1c
.RI "void \fBOnInit\fP ()"
.br
.ti -1c
.RI "void \fBOnDeinit\fP ()"
.br
.ti -1c
.RI "void \fBOnShowBegin\fP (System\&.Action callback)"
.br
.ti -1c
.RI "void \fBOnShowEnd\fP ()"
.br
.ti -1c
.RI "void \fBOnHideBegin\fP (System\&.Action callback)"
.br
.ti -1c
.RI "void \fBOnHideEnd\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBWindowModule\fP \fBmoduleSource\fP"
.br
.ti -1c
.RI "int \fBsortingOrder\fP"
.br
.ti -1c
.RI "bool \fBbackgroundLayer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file WindowBaseModules\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.ModuleInfo\&.ModuleInfo (\fBWindowModule\fP moduleSource, int sortingOrder, bool backgroundLayer)"

.PP
Definition at line 26 of file WindowBaseModules\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.ModuleInfo\&.Create (\fBWindowBase\fP window, Transform modulesRoot)"

.PP
Definition at line 34 of file WindowBaseModules\&.cs\&.
.SS "T UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.ModuleInfo\&.Get< T > ()"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIWindowModule\fP
.PP
Definition at line 60 of file WindowBaseModules\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.ModuleInfo\&.GetDuration (bool forward)"

.PP
Definition at line 54 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.ModuleInfo\&.OnDeinit ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 67 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.ModuleInfo\&.OnHideBegin (System\&.Action callback)"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 83 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.ModuleInfo\&.OnHideEnd ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 97 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.ModuleInfo\&.OnInit ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 66 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.ModuleInfo\&.OnShowBegin (System\&.Action callback)"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 68 of file WindowBaseModules\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.ModuleInfo\&.OnShowEnd ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 82 of file WindowBaseModules\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.ModuleInfo\&.backgroundLayer"

.PP
Definition at line 21 of file WindowBaseModules\&.cs\&.
.SS "\fBWindowModule\fP UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.ModuleInfo\&.moduleSource"

.PP
Definition at line 19 of file WindowBaseModules\&.cs\&.
.SS "int UnityEngine\&.UI\&.Windows\&.Modules\&.Modules\&.ModuleInfo\&.sortingOrder"

.PP
Definition at line 20 of file WindowBaseModules\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
