.TH "UnityEngine.UI.Windows.Plugins.Flow.FlowTag" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Plugins.Flow.FlowTag \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFlowTag\fP (int \fBid\fP, string \fBtitle\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "string \fBtitle\fP"
.br
.ti -1c
.RI "int \fBcolor\fP"
.br
.ti -1c
.RI "bool \fBenabled\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file FlowData\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowTag\&.FlowTag (int id, string title)"

.PP
Definition at line 16 of file FlowData\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowTag\&.color"

.PP
Definition at line 13 of file FlowData\&.cs\&.
.SS "bool UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowTag\&.enabled = true"

.PP
Definition at line 14 of file FlowData\&.cs\&.
.SS "int UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowTag\&.id"

.PP
Definition at line 11 of file FlowData\&.cs\&.
.SS "string UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowTag\&.title"

.PP
Definition at line 12 of file FlowData\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
