.TH "UnityEngine.UI.Windows.Types" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Types \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLayout\fP"
.br
.ti -1c
.RI "class \fBLayoutWindowType\fP"
.br
.ti -1c
.RI "class \fBTextTipWindowType\fP"
.br
.ti -1c
.RI "class \fBTipWindowType\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
