.TH "UnityEngine.UI.Windows.Components.ProgressWithParticlesComponent" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Components.ProgressWithParticlesComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Components\&.ProgressComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.RI "\fIRaises the init event\&. You can override this method but call it's base\&. \fP"
.ti -1c
.RI "override void \fBSetColor\fP (Color color)"
.br
.ti -1c
.RI "override void \fBOnShowEnd\fP ()"
.br
.RI "\fIRaises the show end event\&. You can override this method but call it's base\&. \fP"
.ti -1c
.RI "override void \fBOnHideBegin\fP (System\&.Action callback)"
.br
.RI "\fIRaises the hide begin event\&. Wait while all sub components return the callback\&. You can override this method but call it's base\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ParticleSystemCached \fBeffect\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file ProgressWithParticlesComponent\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void UnityEngine\&.UI\&.Windows\&.Components\&.ProgressWithParticlesComponent\&.OnHideBegin (System\&.Action callback)\fC [virtual]\fP"

.PP
Raises the hide begin event\&. Wait while all sub components return the callback\&. You can override this method but call it's base\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcallback\fP Callback\&.
.RE
.PP

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Components\&.ProgressComponent\fP\&.
.PP
Definition at line 81 of file ProgressWithParticlesComponent\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Components\&.ProgressWithParticlesComponent\&.OnInit ()\fC [virtual]\fP"

.PP
Raises the init event\&. You can override this method but call it's base\&. 
.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Components\&.ProgressComponent\fP\&.
.PP
Definition at line 10 of file ProgressWithParticlesComponent\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Components\&.ProgressWithParticlesComponent\&.OnShowEnd ()\fC [virtual]\fP"

.PP
Raises the show end event\&. You can override this method but call it's base\&. 
.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowComponent\fP\&.
.PP
Definition at line 71 of file ProgressWithParticlesComponent\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Components\&.ProgressWithParticlesComponent\&.SetColor (Color color)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Components\&.ColoredComponent\fP\&.
.PP
Definition at line 25 of file ProgressWithParticlesComponent\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "ParticleSystemCached UnityEngine\&.UI\&.Windows\&.Components\&.ProgressWithParticlesComponent\&.effect"

.PP
Definition at line 8 of file ProgressWithParticlesComponent\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
