.TH "UnityEditor.UI.ButtonWithReferenceEditor" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.ButtonWithReferenceEditor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEditor\&.UI\&.ButtonExtendedEditor\fP\&.
.PP
Inherited by \fBUnityEditor\&.UI\&.ButtonWithLabelEditor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInspectorGUI\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnEnable\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file ButtonWithLabelEditor\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void UnityEditor\&.UI\&.ButtonWithReferenceEditor\&.OnEnable ()\fC [protected]\fP"

.PP
Definition at line 46 of file ButtonWithLabelEditor\&.cs\&.
.SS "override void UnityEditor\&.UI\&.ButtonWithReferenceEditor\&.OnInspectorGUI ()"

.PP
Definition at line 55 of file ButtonWithLabelEditor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
