.TH "UnityEngine.UI.Windows.Components.Table.Table" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Components.Table.Table \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Components\&.List\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetColumnsCount\fP (int columns)"
.br
.ti -1c
.RI "T \fBAddItem< T >\fP (int column)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBWindowComponent\fP \fBheaderSource\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file Table\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "T UnityEngine\&.UI\&.Windows\&.Components\&.Table\&.Table\&.AddItem< T > (int column)"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIWindowComponent\fP
.PP
Definition at line 24 of file Table\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.Table\&.Table\&.SetColumnsCount (int columns)"

.PP
Definition at line 18 of file Table\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBWindowComponent\fP UnityEngine\&.UI\&.Windows\&.Components\&.Table\&.Table\&.headerSource"

.PP
Definition at line 13 of file Table\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
