.TH "UnityEngine.UI.Windows.WindowSystemPlatforms" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.WindowSystemPlatforms \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.WindowSystem\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.RI "\fIInit this instance\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file WindowSystemPlatforms\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void UnityEngine\&.UI\&.Windows\&.WindowSystemPlatforms\&.Init ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Init this instance\&. 
.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowSystem\fP\&.
.PP
Definition at line 26 of file WindowSystemPlatforms\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
