.TH "UnityEditor.UI.Windows.Plugins.DevicePreview.DevicePreview" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.DevicePreview.DevicePreview \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowAddon\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBShow\fP (System\&.Action onClose)"
.br
.ti -1c
.RI "override void \fBOnFlowSettingsGUI\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBShowEditor\fP ()"
.br
.ti -1c
.RI "static void \fBShowEditor\fP (System\&.Action onClose)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file DevicePreviewAddon\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreview\&.OnFlowSettingsGUI ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowAddon\fP\&.
.PP
Definition at line 31 of file DevicePreviewAddon\&.cs\&.
.SS "override void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreview\&.Show (System\&.Action onClose)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowAddon\fP\&.
.PP
Definition at line 25 of file DevicePreviewAddon\&.cs\&.
.SS "static void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreview\&.ShowEditor ()\fC [static]\fP"

.PP
Definition at line 13 of file DevicePreviewAddon\&.cs\&.
.SS "static void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreview\&.ShowEditor (System\&.Action onClose)\fC [static]\fP"

.PP
Definition at line 19 of file DevicePreviewAddon\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
