.TH "UnityEditor.UI.Windows.Plugins.FlowCompiler.FlowCompiler" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.FlowCompiler.FlowCompiler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowAddon\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBShow\fP (System\&.Action onClose)"
.br
.ti -1c
.RI "override void \fBOnFlowSettingsGUI\fP ()"
.br
.ti -1c
.RI "override void \fBOnFlowWindowGUI\fP (\fBFlowWindow\fP window)"
.br
.ti -1c
.RI "override void \fBOnFlowToolbarGUI\fP (GUIStyle buttonStyle)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBShowEditor\fP (System\&.Action onClose)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file FlowCompilerAddon\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void UnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompiler\&.OnFlowSettingsGUI ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowAddon\fP\&.
.PP
Definition at line 23 of file FlowCompilerAddon\&.cs\&.
.SS "override void UnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompiler\&.OnFlowToolbarGUI (GUIStyle buttonStyle)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowAddon\fP\&.
.PP
Definition at line 75 of file FlowCompilerAddon\&.cs\&.
.SS "override void UnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompiler\&.OnFlowWindowGUI (\fBFlowWindow\fP window)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowAddon\fP\&.
.PP
Definition at line 51 of file FlowCompilerAddon\&.cs\&.
.SS "override void UnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompiler\&.Show (System\&.Action onClose)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowAddon\fP\&.
.PP
Definition at line 17 of file FlowCompilerAddon\&.cs\&.
.SS "static void UnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompiler\&.ShowEditor (System\&.Action onClose)\fC [static]\fP"

.PP
Definition at line 11 of file FlowCompilerAddon\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
