.TH "UnityEngine.UI.Windows.Animations.WindowAnimationTransitionAlpha.Parameters.State" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Animations.WindowAnimationTransitionAlpha.Parameters.State \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBto\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file WindowAnimationTransitionAlpha\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionAlpha\&.Parameters\&.State\&.to"

.PP
Definition at line 16 of file WindowAnimationTransitionAlpha\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
