.TH "UnityEditor.UI.Windows.Plugins.Flow.FlowChooserFilterMenu" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.Flow.FlowChooserFilterMenu \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBCreateLayout\fP ()"
.br
.ti -1c
.RI "static void \fBCreateScreen\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file FlowChooserFilterMenu\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowChooserFilterMenu\&.CreateLayout ()\fC [static]\fP"

.PP
Definition at line 54 of file FlowChooserFilterMenu\&.cs\&.
.SS "static void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowChooserFilterMenu\&.CreateScreen ()\fC [static]\fP"

.PP
Definition at line 161 of file FlowChooserFilterMenu\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
