.TH "UnityEditor.UI.Windows.Plugins.Flow.FlowDropDownFilterWindow" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.Flow.FlowDropDownFilterWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits EditorWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBScan< T >\fP (bool strongType)"
.br
.ti -1c
.RI "void \fBOnFocusLost\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBShow< T >\fP (Rect buttonRect, System\&.Action< T > onSelect, System\&.Action< T > onEveryGUI=null, bool strongType=true)"
.br
.ti -1c
.RI "static void \fBShow< T >\fP (Rect buttonRect, Vector2 windowSize, System\&.Action< T > onSelect, System\&.Action< T > onEveryGUI=null, bool strongType=true)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file FlowDropDownFilterWindow\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowDropDownFilterWindow\&.OnFocusLost ()"

.PP
Definition at line 53 of file FlowDropDownFilterWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowDropDownFilterWindow\&.Scan< T > (bool strongType)"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIComponent\fP
.PP
Definition at line 47 of file FlowDropDownFilterWindow\&.cs\&.
.SS "static void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowDropDownFilterWindow\&.Show< T > (Rect buttonRect, System\&.Action< T > onSelect, System\&.Action< T > onEveryGUI = \fCnull\fP, bool strongType = \fCtrue\fP)\fC [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIComponent\fP
.PP
Definition at line 12 of file FlowDropDownFilterWindow\&.cs\&.
.SS "static void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowDropDownFilterWindow\&.Show< T > (Rect buttonRect, Vector2 windowSize, System\&.Action< T > onSelect, System\&.Action< T > onEveryGUI = \fCnull\fP, bool strongType = \fCtrue\fP)\fC [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIComponent\fP
.PP
Definition at line 20 of file FlowDropDownFilterWindow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
