.TH "UnityEngine.UI.Windows.WindowLayoutElement" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.WindowLayoutElement \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.WindowLayoutBase\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "new \fBLayoutTag\fP \fBtag\fP = LayoutTag\&.None"
.br
.ti -1c
.RI "bool \fBcontainsLayouts\fP = false"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file WindowLayoutElement\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool UnityEngine\&.UI\&.Windows\&.WindowLayoutElement\&.containsLayouts = false"

.PP
Definition at line 13 of file WindowLayoutElement\&.cs\&.
.SS "new \fBLayoutTag\fP UnityEngine\&.UI\&.Windows\&.WindowLayoutElement\&.tag = LayoutTag\&.None"

.PP
Definition at line 10 of file WindowLayoutElement\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
