.TH "UnityEngine.UI.Windows.Components.ToggleComponent" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Components.ToggleComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Components\&.List\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.RI "\fIRaises the init event\&. You can override this method but call it's base\&. \fP"
.ti -1c
.RI "virtual void \fBSetCallback\fP (UnityAction< bool > callback)"
.br
.ti -1c
.RI "virtual void \fBSetCallback\fP (UnityAction< \fBToggleItemComponent\fP, bool > callback)"
.br
.ti -1c
.RI "override T \fBAddItem< T >\fP ()"
.br
.ti -1c
.RI "override void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBSelect\fP (\fBIComponent\fP element)"
.br
.ti -1c
.RI "void \fBSelect\fP (int index)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ToggleGroup \fBtoggleGroup\fP"
.br
.ti -1c
.RI "bool \fBallowSwitchOff\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file ToggleComponent\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override T UnityEngine\&.UI\&.Windows\&.Components\&.ToggleComponent\&.AddItem< T > ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Components\&.List\fP\&.
.PP
Definition at line 43 of file ToggleComponent\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Components\&.ToggleComponent\&.Clear ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Components\&.List\fP\&.
.PP
Definition at line 68 of file ToggleComponent\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Components\&.ToggleComponent\&.OnInit ()\fC [virtual]\fP"

.PP
Raises the init event\&. You can override this method but call it's base\&. 
.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Components\&.List\fP\&.
.PP
Definition at line 18 of file ToggleComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.ToggleComponent\&.Select (\fBIComponent\fP element)"

.PP
Definition at line 81 of file ToggleComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.ToggleComponent\&.Select (int index)"

.PP
Definition at line 87 of file ToggleComponent\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.Components\&.ToggleComponent\&.SetCallback (UnityAction< bool > callback)\fC [virtual]\fP"

.PP
Definition at line 29 of file ToggleComponent\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.Components\&.ToggleComponent\&.SetCallback (UnityAction< \fBToggleItemComponent\fP, bool > callback)\fC [virtual]\fP"

.PP
Definition at line 36 of file ToggleComponent\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool UnityEngine\&.UI\&.Windows\&.Components\&.ToggleComponent\&.allowSwitchOff = false"

.PP
Definition at line 11 of file ToggleComponent\&.cs\&.
.SS "ToggleGroup UnityEngine\&.UI\&.Windows\&.Components\&.ToggleComponent\&.toggleGroup"

.PP
Definition at line 10 of file ToggleComponent\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
