.TH "UnityEditor.UI.Windows.Plugins.Flow.Flow" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.Flow.Flow \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEditor\&.UI\&.Windows\&.IWindowAddon\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShow\fP (System\&.Action onClose)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBDrawModuleSettingsGUI\fP (string caption, System\&.Action onGUI)"
.br
.ti -1c
.RI "static void \fBShowEditor\fP ()"
.br
.ti -1c
.RI "static void \fBShowEditorFromContextMenu\fP ()"
.br
.ti -1c
.RI "static \fBFlowSystemEditorWindow\fP \fBShowEditor\fP (System\&.Action onClose)"
.br
.ti -1c
.RI "static void \fBOnDrawWindowGUI\fP (\fBFlowWindow\fP window)"
.br
.ti -1c
.RI "static void \fBOnDrawSettingsGUI\fP ()"
.br
.ti -1c
.RI "static void \fBOnDrawToolbarGUI\fP (GUIStyle buttonStyle)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file FlowAddon\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Flow\&.DrawModuleSettingsGUI (string caption, System\&.Action onGUI)\fC [static]\fP"

.PP
Definition at line 29 of file FlowAddon\&.cs\&.
.SS "static void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Flow\&.OnDrawSettingsGUI ()\fC [static]\fP"

.PP
Definition at line 92 of file FlowAddon\&.cs\&.
.SS "static void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Flow\&.OnDrawToolbarGUI (GUIStyle buttonStyle)\fC [static]\fP"

.PP
Definition at line 130 of file FlowAddon\&.cs\&.
.SS "static void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Flow\&.OnDrawWindowGUI (\fBFlowWindow\fP window)\fC [static]\fP"

.PP
Definition at line 81 of file FlowAddon\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Flow\&.Show (System\&.Action onClose)"

.PP
Implements \fBUnityEditor\&.UI\&.Windows\&.IWindowAddon\fP\&.
.PP
Definition at line 75 of file FlowAddon\&.cs\&.
.SS "static void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Flow\&.ShowEditor ()\fC [static]\fP"

.PP
Definition at line 42 of file FlowAddon\&.cs\&.
.SS "static \fBFlowSystemEditorWindow\fP UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Flow\&.ShowEditor (System\&.Action onClose)\fC [static]\fP"

.PP
Definition at line 69 of file FlowAddon\&.cs\&.
.SS "static void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Flow\&.ShowEditorFromContextMenu ()\fC [static]\fP"

.PP
Definition at line 56 of file FlowAddon\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
