.TH "UnityEditor.UI.Windows.Plugins.Flow.FlowAddon" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.Flow.FlowAddon \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.IWindowFlowAddon\fP\&.
.PP
Inherited by \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreview\fP, and \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompiler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBShow\fP (System\&.Action onClose)"
.br
.ti -1c
.RI "virtual void \fBOnFlowSettingsGUI\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnFlowWindowGUI\fP (\fBFlowWindow\fP window)"
.br
.ti -1c
.RI "virtual void \fBOnFlowToolbarGUI\fP (GUIStyle buttonStyle)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file FlowAddon\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowAddon\&.OnFlowSettingsGUI ()\fC [virtual]\fP"

.PP
Implements \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.IWindowFlowAddon\fP\&.
.PP
Reimplemented in \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreview\fP, and \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompiler\fP\&.
.PP
Definition at line 21 of file FlowAddon\&.cs\&.
.SS "virtual void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowAddon\&.OnFlowToolbarGUI (GUIStyle buttonStyle)\fC [virtual]\fP"

.PP
Implements \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.IWindowFlowAddon\fP\&.
.PP
Reimplemented in \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompiler\fP\&.
.PP
Definition at line 23 of file FlowAddon\&.cs\&.
.SS "virtual void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowAddon\&.OnFlowWindowGUI (\fBFlowWindow\fP window)\fC [virtual]\fP"

.PP
Implements \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.IWindowFlowAddon\fP\&.
.PP
Reimplemented in \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompiler\fP\&.
.PP
Definition at line 22 of file FlowAddon\&.cs\&.
.SS "virtual void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowAddon\&.Show (System\&.Action onClose)\fC [virtual]\fP"

.PP
Implements \fBUnityEditor\&.UI\&.Windows\&.IWindowAddon\fP\&.
.PP
Reimplemented in \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreview\fP, and \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.FlowCompiler\fP\&.
.PP
Definition at line 20 of file FlowAddon\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowAddon\&.name"

.PP
Definition at line 18 of file FlowAddon\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
