.TH "UnityEngine.UI.Windows.Types.Layout.Component" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Types.Layout.Component \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBComponent\fP (\fBLayoutTag\fP \fBtag\fP, string description)"
.br
.ti -1c
.RI "\fBIWindowEventsAsync\fP \fBCreate\fP (\fBWindowBase\fP window, \fBWindowLayoutElement\fP root)"
.br
.ti -1c
.RI "\fBWindowLayoutElement\fP \fBGetContainer\fP ()"
.br
.ti -1c
.RI "T \fBGet< T >\fP (\fBLayoutTag\fP \fBtag\fP=LayoutTag\&.None)"
.br
.ti -1c
.RI "float \fBGetDuration\fP (bool forward)"
.br
.ti -1c
.RI "void \fBOnInit\fP ()"
.br
.ti -1c
.RI "void \fBOnDeinit\fP ()"
.br
.ti -1c
.RI "void \fBOnShowBegin\fP (System\&.Action callback)"
.br
.ti -1c
.RI "void \fBOnShowEnd\fP ()"
.br
.ti -1c
.RI "void \fBOnHideBegin\fP (System\&.Action callback)"
.br
.ti -1c
.RI "void \fBOnHideEnd\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLayoutTag\fP \fBtag\fP"
.br
.ti -1c
.RI "\fBWindowComponent\fP \fBcomponent\fP"
.br
.ti -1c
.RI "int \fBsortingOrder\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 134 of file LayoutWindowType\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEngine\&.UI\&.Windows\&.Types\&.Layout\&.Component\&.Component (\fBLayoutTag\fP tag, string description)"

.PP
Definition at line 145 of file LayoutWindowType\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBIWindowEventsAsync\fP UnityEngine\&.UI\&.Windows\&.Types\&.Layout\&.Component\&.Create (\fBWindowBase\fP window, \fBWindowLayoutElement\fP root)"

.PP
Definition at line 178 of file LayoutWindowType\&.cs\&.
.SS "T UnityEngine\&.UI\&.Windows\&.Types\&.Layout\&.Component\&.Get< T > (\fBLayoutTag\fP tag = \fCLayoutTag\&.None\fP)"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIWindowComponent\fP
.PP
Definition at line 220 of file LayoutWindowType\&.cs\&.
.SS "\fBWindowLayoutElement\fP UnityEngine\&.UI\&.Windows\&.Types\&.Layout\&.Component\&.GetContainer ()"

.PP
Definition at line 214 of file LayoutWindowType\&.cs\&.
.SS "float UnityEngine\&.UI\&.Windows\&.Types\&.Layout\&.Component\&.GetDuration (bool forward)"

.PP
Definition at line 238 of file LayoutWindowType\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Types\&.Layout\&.Component\&.OnDeinit ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 256 of file LayoutWindowType\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Types\&.Layout\&.Component\&.OnHideBegin (System\&.Action callback)"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 276 of file LayoutWindowType\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Types\&.Layout\&.Component\&.OnHideEnd ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 282 of file LayoutWindowType\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Types\&.Layout\&.Component\&.OnInit ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 249 of file LayoutWindowType\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Types\&.Layout\&.Component\&.OnShowBegin (System\&.Action callback)"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 263 of file LayoutWindowType\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Types\&.Layout\&.Component\&.OnShowEnd ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Definition at line 269 of file LayoutWindowType\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBWindowComponent\fP UnityEngine\&.UI\&.Windows\&.Types\&.Layout\&.Component\&.component"

.PP
Definition at line 142 of file LayoutWindowType\&.cs\&.
.SS "int UnityEngine\&.UI\&.Windows\&.Types\&.Layout\&.Component\&.sortingOrder = 0"

.PP
Definition at line 143 of file LayoutWindowType\&.cs\&.
.SS "\fBLayoutTag\fP UnityEngine\&.UI\&.Windows\&.Types\&.Layout\&.Component\&.tag"

.PP
Definition at line 140 of file LayoutWindowType\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
