.TH "UnityEngine.UI.Windows.IWindowAnimation" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.IWindowAnimation \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Inherited by \fBUnityEngine\&.UI\&.Windows\&.WindowComponentBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float \fBGetAnimationDuration\fP (bool forward)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file IWindowComponent\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "float UnityEngine\&.UI\&.Windows\&.IWindowAnimation\&.GetAnimationDuration (bool forward)"

.PP
Implemented in \fBUnityEngine\&.UI\&.Windows\&.WindowComponentBase\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
