.TH "UnityEngine.UI.Windows.Components.IComponent" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Components.IComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBUnityEngine\&.UI\&.Windows\&.Components\&.IImageComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.ISelectable\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.ITextComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.WindowComponent\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 5 of file ITextComponent\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
