.TH "UnityEngine.UI.Windows.Animations.WindowTransitionBasicParameters" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Animations.WindowTransitionBasicParameters \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionInputParameters\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBSetDefaultParameters\fP (\fBTransitionBase\&.ParametersBase\fP \fBparameters\fP)"
.br
.ti -1c
.RI "override \fBTransitionBase\&.ParametersBase\fP \fBGetParameters\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBWindowTransitionBasic\&.Parameters\fP \fBparameters\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file WindowTransitionBasicParameters\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBTransitionBase\&.ParametersBase\fP UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasicParameters\&.GetParameters ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionInputParameters\fP\&.
.PP
Definition at line 16 of file WindowTransitionBasicParameters\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasicParameters\&.SetDefaultParameters (\fBTransitionBase\&.ParametersBase\fP parameters)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionInputParameters\fP\&.
.PP
Definition at line 10 of file WindowTransitionBasicParameters\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBWindowTransitionBasic\&.Parameters\fP UnityEngine\&.UI\&.Windows\&.Animations\&.WindowTransitionBasicParameters\&.parameters"

.PP
Definition at line 8 of file WindowTransitionBasicParameters\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
