.TH "UnityEngine.UI.Windows.Animations.WindowAnimationTransitionSlide.Parameters" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Animations.WindowAnimationTransitionSlide.Parameters \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Animations\&.TransitionBase\&.ParametersBase\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBState\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParameters\fP (\fBTransitionBase\&.ParametersBase\fP baseDefaults)"
.br
.ti -1c
.RI "override void \fBSetup\fP (\fBTransitionBase\&.ParametersBase\fP defaults)"
.br
.ti -1c
.RI "Vector2 \fBGetIn\fP ()"
.br
.ti -1c
.RI "Vector2 \fBGetOut\fP ()"
.br
.ti -1c
.RI "Vector2 \fBGetReset\fP ()"
.br
.ti -1c
.RI "Vector2 \fBGetResult\fP (bool forward)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBmoveRoot\fP = false"
.br
.ti -1c
.RI "\fBState\fP \fBresetState\fP"
.br
.ti -1c
.RI "\fBState\fP \fBinState\fP"
.br
.ti -1c
.RI "\fBState\fP \fBoutState\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file WindowAnimationTransitionSlide\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionSlide\&.Parameters\&.Parameters (\fBTransitionBase\&.ParametersBase\fP baseDefaults)"

.PP
Definition at line 12 of file WindowAnimationTransitionSlide\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "Vector2 UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionSlide\&.Parameters\&.GetIn ()"

.PP
Definition at line 41 of file WindowAnimationTransitionSlide\&.cs\&.
.SS "Vector2 UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionSlide\&.Parameters\&.GetOut ()"

.PP
Definition at line 47 of file WindowAnimationTransitionSlide\&.cs\&.
.SS "Vector2 UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionSlide\&.Parameters\&.GetReset ()"

.PP
Definition at line 53 of file WindowAnimationTransitionSlide\&.cs\&.
.SS "Vector2 UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionSlide\&.Parameters\&.GetResult (bool forward)"

.PP
Definition at line 59 of file WindowAnimationTransitionSlide\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionSlide\&.Parameters\&.Setup (\fBTransitionBase\&.ParametersBase\fP defaults)"

.PP
Definition at line 27 of file WindowAnimationTransitionSlide\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBState\fP UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionSlide\&.Parameters\&.inState"

.PP
Definition at line 24 of file WindowAnimationTransitionSlide\&.cs\&.
.SS "bool UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionSlide\&.Parameters\&.moveRoot = false"

.PP
Definition at line 21 of file WindowAnimationTransitionSlide\&.cs\&.
.SS "\fBState\fP UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionSlide\&.Parameters\&.outState"

.PP
Definition at line 25 of file WindowAnimationTransitionSlide\&.cs\&.
.SS "\fBState\fP UnityEngine\&.UI\&.Windows\&.Animations\&.WindowAnimationTransitionSlide\&.Parameters\&.resetState"

.PP
Definition at line 23 of file WindowAnimationTransitionSlide\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
