.TH "UnityEditor.EditorWindowSceneView" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.EditorWindowSceneView \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits SceneView\&.
.PP
Inherited by \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowSceneViewWindow\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnActive\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnInactive\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnClose\fP ()"
.br
.ti -1c
.RI "override void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "override void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "new void \fBOnDestroy\fP ()"
.br
.ti -1c
.RI "new void \fBUpdate\fP ()"
.br
.ti -1c
.RI "bool \fBIsVisible\fP ()"
.br
.ti -1c
.RI "void \fBDrawProgress\fP (float \fBprogress\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "float \fBprogress\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file FlowEditorWindowExt\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.EditorWindowSceneView\&.DrawProgress (float progress)"

.PP
Definition at line 92 of file FlowEditorWindowExt\&.cs\&.
.SS "bool UnityEditor\&.EditorWindowSceneView\&.IsVisible ()"

.PP
Definition at line 83 of file FlowEditorWindowExt\&.cs\&.
.SS "virtual void UnityEditor\&.EditorWindowSceneView\&.OnActive ()\fC [virtual]\fP"

.PP
Definition at line 11 of file FlowEditorWindowExt\&.cs\&.
.SS "virtual void UnityEditor\&.EditorWindowSceneView\&.OnClose ()\fC [virtual]\fP"

.PP
Reimplemented in \fBUnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowSceneViewWindow\fP\&.
.PP
Definition at line 13 of file FlowEditorWindowExt\&.cs\&.
.SS "new void UnityEditor\&.EditorWindowSceneView\&.OnDestroy ()"

.PP
Definition at line 31 of file FlowEditorWindowExt\&.cs\&.
.SS "override void UnityEditor\&.EditorWindowSceneView\&.OnDisable ()"

.PP
Definition at line 23 of file FlowEditorWindowExt\&.cs\&.
.SS "override void UnityEditor\&.EditorWindowSceneView\&.OnEnable ()"

.PP
Definition at line 15 of file FlowEditorWindowExt\&.cs\&.
.SS "virtual void UnityEditor\&.EditorWindowSceneView\&.OnInactive ()\fC [virtual]\fP"

.PP
Definition at line 12 of file FlowEditorWindowExt\&.cs\&.
.SS "new void UnityEditor\&.EditorWindowSceneView\&.Update ()"

.PP
Definition at line 47 of file FlowEditorWindowExt\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float UnityEditor\&.EditorWindowSceneView\&.progress\fC [protected]\fP"

.PP
Definition at line 91 of file FlowEditorWindowExt\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
