.TH "UnityEngine.UI.Windows.Plugins.Flow" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Plugins.Flow \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFlowData\fP"
.br
.ti -1c
.RI "class \fBFlowDatabase\fP"
.br
.ti -1c
.RI "class \fBFlowLayoutWindowTypeTemplate\fP"
.br
.ti -1c
.RI "class \fBFlowSystem\fP"
.br
.ti -1c
.RI "class \fBFlowTag\fP"
.br
.ti -1c
.RI "class \fBFlowWindow\fP"
.br
.ti -1c
.RI "class \fBFlowWindowLayoutTemplate\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBCompletedState\fP { \fBCompletedState\&.NotReady\fP, \fBCompletedState\&.ReadyButWarnings\fP, \fBCompletedState\&.Ready\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBUnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.CompletedState\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINotReady \fP\fP
.TP
\fB\fIReadyButWarnings \fP\fP
.TP
\fB\fIReady \fP\fP
.PP
Definition at line 13 of file FlowWindow\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
