.TH "UnityEditor.UI.ButtonExtendedEditor" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.ButtonExtendedEditor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ButtonEditor\&.
.PP
Inherited by \fBUnityEditor\&.UI\&.ButtonWithReferenceEditor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInspectorGUI\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "override void \fBOnDisable\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file ButtonExtendedEditor\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void UnityEditor\&.UI\&.ButtonExtendedEditor\&.OnDisable ()\fC [protected]\fP"

.PP
Definition at line 43 of file ButtonExtendedEditor\&.cs\&.
.SS "override void UnityEditor\&.UI\&.ButtonExtendedEditor\&.OnEnable ()\fC [protected]\fP"

.PP
Definition at line 22 of file ButtonExtendedEditor\&.cs\&.
.SS "override void UnityEditor\&.UI\&.ButtonExtendedEditor\&.OnInspectorGUI ()"

.PP
Definition at line 57 of file ButtonExtendedEditor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
