.TH "UnityEngine.UI.Windows.Animations" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Animations \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTransitionBase\fP"
.br
.ti -1c
.RI "class \fBTransitionInputParameters\fP"
.br
.ti -1c
.RI "class \fBWindowAnimationBase\fP"
.br
.ti -1c
.RI "class \fBWindowAnimationTransitionAlpha\fP"
.br
.ti -1c
.RI "class \fBWindowAnimationTransitionAlphaParameters\fP"
.br
.ti -1c
.RI "class \fBWindowAnimationTransitionSlide\fP"
.br
.ti -1c
.RI "class \fBWindowAnimationTransitionSlideParameters\fP"
.br
.ti -1c
.RI "class \fBWindowTransitionBasic\fP"
.br
.ti -1c
.RI "class \fBWindowTransitionBasicParameters\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
