.TH "UnityEditor.UI.Windows.Plugins.Flow.Editors.FlowSceneViewWindow" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.Flow.Editors.FlowSceneViewWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEditor\&.EditorWindowSceneView\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShowView\fP ()"
.br
.ti -1c
.RI "void \fBHideView\fP ()"
.br
.ti -1c
.RI "void \fBUpdateSize\fP (float \fBprogress\fP)"
.br
.ti -1c
.RI "new void \fBUpdate\fP ()"
.br
.ti -1c
.RI "override void \fBOnClose\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFlowSystemEditorWindow\fP \fBrootWindow\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file FlowSceneViewWindow\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowSceneViewWindow\&.HideView ()"

.PP
Definition at line 37 of file FlowSceneViewWindow\&.cs\&.
.SS "override void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowSceneViewWindow\&.OnClose ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEditor\&.EditorWindowSceneView\fP\&.
.PP
Definition at line 84 of file FlowSceneViewWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowSceneViewWindow\&.ShowView ()"
FlowSystem\&.GetData()\&.editorWindowAsPopup; 
.PP
Definition at line 16 of file FlowSceneViewWindow\&.cs\&.
.SS "new void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowSceneViewWindow\&.Update ()"

.PP
Definition at line 55 of file FlowSceneViewWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowSceneViewWindow\&.UpdateSize (float progress)"

.PP
Definition at line 43 of file FlowSceneViewWindow\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFlowSystemEditorWindow\fP UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowSceneViewWindow\&.rootWindow"

.PP
Definition at line 9 of file FlowSceneViewWindow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
