.TH "UnityEditor.UI.Windows.Plugins.Flow.FlowChooserFilterWindow" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.Flow.FlowChooserFilterWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits EditorWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnLostFocus\fP ()"
.br
.ti -1c
.RI "void \fBScan< T >\fP (bool strongType, string directory=null)"
.br
.ti -1c
.RI "void \fBScanAssets< T >\fP (string directory=null, System\&.Func< T, bool > predicate=null)"
.br
.ti -1c
.RI "void \fBUpdateSize\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBShow< T >\fP (EditorWindow root, System\&.Action< T > onSelect, System\&.Action< T > onEveryGUI=null, bool strongType=false, string directory=null)"
.br
.ti -1c
.RI "static void \fBShowAssets< T >\fP (EditorWindow root, System\&.Action< T > onSelect, System\&.Func< T, bool > onEveryGUI=null, System\&.Func< T, bool > predicate=null, string directory=null)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file FlowChooserFilterWindow\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowChooserFilterWindow\&.OnLostFocus ()"

.PP
Definition at line 94 of file FlowChooserFilterWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowChooserFilterWindow\&.Scan< T > (bool strongType, string directory = \fCnull\fP)"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIComponent\fP
.PP
Definition at line 100 of file FlowChooserFilterWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowChooserFilterWindow\&.ScanAssets< T > (string directory = \fCnull\fP, System\&.Func< T, bool > predicate = \fCnull\fP)"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIScriptableObject\fP
.PP
Definition at line 106 of file FlowChooserFilterWindow\&.cs\&.
.SS "static void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowChooserFilterWindow\&.Show< T > (EditorWindow root, System\&.Action< T > onSelect, System\&.Action< T > onEveryGUI = \fCnull\fP, bool strongType = \fCfalse\fP, string directory = \fCnull\fP)\fC [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIComponent\fP
.PP
Definition at line 50 of file FlowChooserFilterWindow\&.cs\&.
.SS "static void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowChooserFilterWindow\&.ShowAssets< T > (EditorWindow root, System\&.Action< T > onSelect, System\&.Func< T, bool > onEveryGUI = \fCnull\fP, System\&.Func< T, bool > predicate = \fCnull\fP, string directory = \fCnull\fP)\fC [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIScriptableObject\fP
.PP
Definition at line 71 of file FlowChooserFilterWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowChooserFilterWindow\&.Update ()"

.PP
Definition at line 131 of file FlowChooserFilterWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowChooserFilterWindow\&.UpdateSize ()"

.PP
Definition at line 112 of file FlowChooserFilterWindow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
