.TH "UnityEditor.UI.Windows.Plugins.Flow.FlowSceneItem" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.Flow.FlowSceneItem \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFlowSceneItem\fP (\fBFlowSystemEditorWindow\fP rootWindow, \fBFlowWindow\fP window, AnimatedValues\&.AnimFloat progressValue)"
.br
.ti -1c
.RI "void \fBOnLostFocus\fP ()"
.br
.ti -1c
.RI "void \fBShow\fP ()"
.br
.ti -1c
.RI "void \fBHide\fP ()"
.br
.ti -1c
.RI "void \fBDispose\fP (bool onDestroy=false, AnimatedValues\&.AnimFloat progressValue=null)"
.br
.ti -1c
.RI "void \fBOnGUI\fP (SceneView sceneView)"
.br
.ti -1c
.RI "\fBWindowBase\fP \fBGetScreenInstance\fP ()"
.br
.ti -1c
.RI "\fBWindowLayout\fP \fBGetLayoutInstance\fP ()"
.br
.ti -1c
.RI "void \fBSetScreenDirty\fP ()"
.br
.ti -1c
.RI "void \fBSetLayoutDirty\fP ()"
.br
.ti -1c
.RI "void \fBSetTab\fP (int index)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const float \fBPOPUP_OFFSET\fP = 50f"
.br
.ti -1c
.RI "const float \fBPOPUP_MARGIN\fP = 5f"
.br
.ti -1c
.RI "bool \fBisLocked\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file FlowItemEditorWindow\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneItem\&.FlowSceneItem (\fBFlowSystemEditorWindow\fP rootWindow, \fBFlowWindow\fP window, AnimatedValues\&.AnimFloat progressValue)"

.PP
Definition at line 71 of file FlowItemEditorWindow\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneItem\&.Dispose (bool onDestroy = \fCfalse\fP, AnimatedValues\&.AnimFloat progressValue = \fCnull\fP)"

.PP
Definition at line 171 of file FlowItemEditorWindow\&.cs\&.
.SS "\fBWindowLayout\fP UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneItem\&.GetLayoutInstance ()"

.PP
Definition at line 320 of file FlowItemEditorWindow\&.cs\&.
.SS "\fBWindowBase\fP UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneItem\&.GetScreenInstance ()"

.PP
Definition at line 314 of file FlowItemEditorWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneItem\&.Hide ()"

.PP
Definition at line 161 of file FlowItemEditorWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneItem\&.OnGUI (SceneView sceneView)"

.PP
Definition at line 224 of file FlowItemEditorWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneItem\&.OnLostFocus ()"

.PP
Definition at line 146 of file FlowItemEditorWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneItem\&.SetLayoutDirty ()"

.PP
Definition at line 336 of file FlowItemEditorWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneItem\&.SetScreenDirty ()"

.PP
Definition at line 326 of file FlowItemEditorWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneItem\&.SetTab (int index)"

.PP
Definition at line 346 of file FlowItemEditorWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneItem\&.Show ()"

.PP
Definition at line 150 of file FlowItemEditorWindow\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneItem\&.isLocked = false"

.PP
Definition at line 69 of file FlowItemEditorWindow\&.cs\&.
.SS "const float UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneItem\&.POPUP_MARGIN = 5f"

.PP
Definition at line 18 of file FlowItemEditorWindow\&.cs\&.
.SS "const float UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowSceneItem\&.POPUP_OFFSET = 50f"

.PP
Definition at line 17 of file FlowItemEditorWindow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
