.TH "UnityEngine.UI.Windows.Types.TipWindowType" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Types.TipWindowType \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.WindowBase\fP\&.
.PP
Inherited by \fBUnityEngine\&.UI\&.Windows\&.Types\&.TextTipWindowType\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnHover\fP (Transform worldElement, Vector3 worldPoint, Camera gameCamera, Vector3 offset=default(Vector3))"
.br
.ti -1c
.RI "void \fBOnHover\fP (RectTransform uiElement)"
.br
.ti -1c
.RI "void \fBOnLeave\fP ()"
.br
.ti -1c
.RI "override float \fBGetLayoutAnimationDuration\fP (bool forward)"
.br
.RI "\fIGets the duration of the layout animation\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RectTransform \fBroot\fP"
.br
.ti -1c
.RI "\fBWindowLayoutBase\fP \fBanimationRoot\fP"
.br
.ti -1c
.RI "Canvas \fBcanvas\fP"
.br
.ti -1c
.RI "UnityEngine\&.EventSystems\&.BaseRaycaster \fBraycaster\fP"
.br
.ti -1c
.RI "bool \fBinitializedChild\fP = false"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnLayoutInit\fP (float depth, int raycastPriority, int orderInLayer)"
.br
.RI "\fIRaises the layout init event\&. \fP"
.ti -1c
.RI "override void \fBOnLayoutDeinit\fP ()"
.br
.RI "\fIRaises the layout deinit event\&. \fP"
.ti -1c
.RI "override void \fBOnLayoutHideEnd\fP ()"
.br
.RI "\fIRaises the layout hide end event\&. \fP"
.ti -1c
.RI "override void \fBOnLayoutShowEnd\fP ()"
.br
.RI "\fIRaises the layout show end event\&. \fP"
.ti -1c
.RI "override void \fBOnLayoutShowBegin\fP (System\&.Action callback)"
.br
.RI "\fIRaises the layout show begin event\&. \fP"
.ti -1c
.RI "override void \fBOnLayoutHideBegin\fP (System\&.Action callback)"
.br
.RI "\fIRaises the layout hide begin event\&. \fP"
.ti -1c
.RI "override Transform \fBGetLayoutRoot\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file TipWindowType\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override float UnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\&.GetLayoutAnimationDuration (bool forward)\fC [virtual]\fP"

.PP
Gets the duration of the layout animation\&. 
.PP
\fBReturns:\fP
.RS 4
The layout animation duration\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIforward\fP If set to \fCtrue\fP forward\&.
.RE
.PP

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowBase\fP\&.
.PP
Definition at line 118 of file TipWindowType\&.cs\&.
.SS "override Transform UnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\&.GetLayoutRoot ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowBase\fP\&.
.PP
Definition at line 112 of file TipWindowType\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\&.OnHover (Transform worldElement, Vector3 worldPoint, Camera gameCamera, Vector3 offset = \fCdefault(Vector3)\fP)"

.PP
Definition at line 21 of file TipWindowType\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\&.OnHover (RectTransform uiElement)"

.PP
Definition at line 35 of file TipWindowType\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\&.OnLayoutDeinit ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the layout deinit event\&. 
.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowBase\fP\&.
.PP
Definition at line 68 of file TipWindowType\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\&.OnLayoutHideBegin (System\&.Action callback)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the layout hide begin event\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcallback\fP Callback\&.
.RE
.PP

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowBase\fP\&.
.PP
Definition at line 98 of file TipWindowType\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\&.OnLayoutHideEnd ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the layout hide end event\&. 
.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowBase\fP\&.
.PP
Definition at line 73 of file TipWindowType\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\&.OnLayoutInit (float depth, int raycastPriority, int orderInLayer)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the layout init event\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdepth\fP Depth\&.
.br
\fIraycastPriority\fP Raycast priority\&.
.br
\fIorderInLayer\fP Order in layer\&.
.RE
.PP

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowBase\fP\&.
.PP
Definition at line 63 of file TipWindowType\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\&.OnLayoutShowBegin (System\&.Action callback)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the layout show begin event\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcallback\fP Callback\&.
.RE
.PP

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowBase\fP\&.
.PP
Definition at line 84 of file TipWindowType\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\&.OnLayoutShowEnd ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Raises the layout show end event\&. 
.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowBase\fP\&.
.PP
Definition at line 78 of file TipWindowType\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\&.OnLeave ()"

.PP
Definition at line 57 of file TipWindowType\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBWindowLayoutBase\fP UnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\&.animationRoot"

.PP
Definition at line 10 of file TipWindowType\&.cs\&.
.SS "Canvas UnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\&.canvas"

.PP
Definition at line 13 of file TipWindowType\&.cs\&.
.SS "bool UnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\&.initializedChild = false"

.PP
Definition at line 17 of file TipWindowType\&.cs\&.
.SS "UnityEngine\&.EventSystems\&.BaseRaycaster UnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\&.raycaster"

.PP
Definition at line 15 of file TipWindowType\&.cs\&.
.SS "RectTransform UnityEngine\&.UI\&.Windows\&.Types\&.TipWindowType\&.root"

.PP
Definition at line 9 of file TipWindowType\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
