.TH "UnityEditor.UI.Windows.Plugins.DevicePreview.DevicePreviewWindow.GameView" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.DevicePreview.DevicePreviewWindow.GameView \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGameView\fP (\fBDevicePreviewWindow\fP \fBroot\fP)"
.br
.ti -1c
.RI "void \fBResize\fP (float \fBwidth\fP, float \fBheight\fP)"
.br
.ti -1c
.RI "bool \fBSetResolution\fP (int \fBwidth\fP, int \fBheight\fP, float ppi, ScreenOrientation orientation, \fBIDeviceOutput\fP deviceOutput)"
.br
.ti -1c
.RI "void \fBCleanUp\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBOnGUI\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDevicePreviewWindow\fP \fBroot\fP"
.br
.ti -1c
.RI "float \fBwidth\fP = 600f"
.br
.ti -1c
.RI "float \fBheight\fP = 400f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file DevicePreviewWindow\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreviewWindow\&.GameView\&.GameView (\fBDevicePreviewWindow\fP root)"

.PP
Definition at line 26 of file DevicePreviewWindow\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreviewWindow\&.GameView\&.CleanUp ()"

.PP
Definition at line 93 of file DevicePreviewWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreviewWindow\&.GameView\&.OnGUI ()"

.PP
Definition at line 105 of file DevicePreviewWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreviewWindow\&.GameView\&.Resize (float width, float height)"

.PP
Definition at line 32 of file DevicePreviewWindow\&.cs\&.
.SS "bool UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreviewWindow\&.GameView\&.SetResolution (int width, int height, float ppi, ScreenOrientation orientation, \fBIDeviceOutput\fP deviceOutput)"

.PP
Definition at line 46 of file DevicePreviewWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreviewWindow\&.GameView\&.Update ()"

.PP
Definition at line 99 of file DevicePreviewWindow\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreviewWindow\&.GameView\&.height = 400f"

.PP
Definition at line 20 of file DevicePreviewWindow\&.cs\&.
.SS "\fBDevicePreviewWindow\fP UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreviewWindow\&.GameView\&.root"

.PP
Definition at line 17 of file DevicePreviewWindow\&.cs\&.
.SS "float UnityEditor\&.UI\&.Windows\&.Plugins\&.DevicePreview\&.DevicePreviewWindow\&.GameView\&.width = 600f"

.PP
Definition at line 19 of file DevicePreviewWindow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
