.TH "UnityEngine.UI.Windows.Plugins.Flow.FlowDatabase" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Plugins.Flow.FlowDatabase \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBRemoveLayoutComponent\fP (Transform element)"
.br
.ti -1c
.RI "static \fBWindowLayoutElement\fP \fBAddLayoutElementComponent\fP (string name, Transform root, int siblingIndex)"
.br
.ti -1c
.RI "static TWith \fBReplaceComponents< TReplace, TWith >\fP (TReplace source, System\&.Type withType)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBCOMPONENTS_FOLDER\fP = 'Components'"
.br
.ti -1c
.RI "const string \fBLAYOUT_FOLDER\fP = 'Layouts'"
.br
.ti -1c
.RI "const string \fBSCREENS_FOLDER\fP = 'Screens'"
.br
.ti -1c
.RI "const string \fBOTHER_NAME\fP = 'Other'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file FlowDatabase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBWindowLayoutElement\fP UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowDatabase\&.AddLayoutElementComponent (string name, Transform root, int siblingIndex)\fC [static]\fP"

.PP
Definition at line 34 of file FlowDatabase\&.cs\&.
.SS "static void UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowDatabase\&.RemoveLayoutComponent (Transform element)\fC [static]\fP"

.PP
Definition at line 24 of file FlowDatabase\&.cs\&.
.SS "static TWith UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowDatabase\&.ReplaceComponents< TReplace, TWith > (TReplace source, System\&.Type withType)\fC [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fITReplace\fP : \fIComponent\fP
.TP
\fITWith\fP : \fIComponent\fP
.PP
Definition at line 63 of file FlowDatabase\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const string UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowDatabase\&.COMPONENTS_FOLDER = 'Components'"

.PP
Definition at line 19 of file FlowDatabase\&.cs\&.
.SS "const string UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowDatabase\&.LAYOUT_FOLDER = 'Layouts'"

.PP
Definition at line 20 of file FlowDatabase\&.cs\&.
.SS "const string UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowDatabase\&.OTHER_NAME = 'Other'"

.PP
Definition at line 22 of file FlowDatabase\&.cs\&.
.SS "const string UnityEngine\&.UI\&.Windows\&.Plugins\&.Flow\&.FlowDatabase\&.SCREENS_FOLDER = 'Screens'"

.PP
Definition at line 21 of file FlowDatabase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
