.TH "UnityEngine.UI.Windows.WindowComponentBase" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.WindowComponentBase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.WindowObject\fP, and \fBUnityEngine\&.UI\&.Windows\&.IWindowAnimation\fP\&.
.PP
Inherited by \fBUnityEngine\&.UI\&.Windows\&.WindowComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.WindowLayoutBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindowObjectState\fP \fBGetComponentState\fP ()"
.br
.RI "\fIGets the state of the component\&. \fP"
.ti -1c
.RI "void \fBShow\fP (bool resetAnimation=true)"
.br
.RI "\fIShow component\&. Animation component can use current layout element root or current component root\&. \fP"
.ti -1c
.RI "virtual void \fBShow\fP (System\&.Action callback, bool resetAnimation)"
.br
.RI "\fIShow component with callback after end\&. Animation component can use current layout element root or current component root\&. \fP"
.ti -1c
.RI "void \fBHide\fP ()"
.br
.RI "\fIHide this instance\&. Animation component can use current layout element root or current component root\&. \fP"
.ti -1c
.RI "void \fBHide\fP (bool immediately)"
.br
.RI "\fIHide the specified immediately\&. Animation component can use current layout element root or current component root\&. \fP"
.ti -1c
.RI "virtual void \fBHide\fP (System\&.Action callback, bool immediately)"
.br
.RI "\fIHide the specified callback and immediately\&. Animation component can use current layout element root or current component root\&. \fP"
.ti -1c
.RI "void \fBSetResetState\fP ()"
.br
.RI "\fISet up \fCreset\fP state to animation\&. \fP"
.ti -1c
.RI "void \fBSetInState\fP ()"
.br
.RI "\fISet up \fCin\fP state to animation\&. \fP"
.ti -1c
.RI "void \fBSetOutState\fP ()"
.br
.RI "\fISet up \fCout\fP state to animation\&. \fP"
.ti -1c
.RI "virtual float \fBGetAnimationDuration\fP (bool forward)"
.br
.RI "\fIGets the duration of the animation\&. \fP"
.ti -1c
.RI "virtual void \fBOnShowBegin\fP (System\&.Action callback)"
.br
.RI "\fIRaises the show begin event\&. Wait while all sub components return the callback\&. You can override this method but call it's base\&. \fP"
.ti -1c
.RI "virtual void \fBOnHideBegin\fP (System\&.Action callback)"
.br
.RI "\fIRaises the hide begin event\&. Wait while all sub components return the callback\&. You can override this method but call it's base\&. \fP"
.ti -1c
.RI "virtual void \fBOnInit\fP ()"
.br
.RI "\fIRaises the init event\&. You can override this method but call it's base\&. \fP"
.ti -1c
.RI "virtual void \fBOnDeinit\fP ()"
.br
.RI "\fIRaises the deinit event\&. You can override this method but call it's base\&. \fP"
.ti -1c
.RI "virtual void \fBOnShowEnd\fP ()"
.br
.RI "\fIRaises the show end event\&. You can override this method but call it's base\&. \fP"
.ti -1c
.RI "virtual void \fBOnHideEnd\fP ()"
.br
.RI "\fIRaises the hide end event\&. You can override this method but call it's base\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "new \fBWindowAnimationBase\fP \fBanimation\fP"
.br
.ti -1c
.RI "List< \fBTransitionInputParameters\fP > \fBanimationInputParams\fP = new List<\fBTransitionInputParameters\fP>()"
.br
.ti -1c
.RI "CanvasGroup \fBcanvas\fP"
.br
.ti -1c
.RI "bool \fBanimationRefresh\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file WindowComponentBase\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual float UnityEngine\&.UI\&.Windows\&.WindowComponentBase\&.GetAnimationDuration (bool forward)\fC [virtual]\fP"

.PP
Gets the duration of the animation\&. 
.PP
\fBReturns:\fP
.RS 4
The animation duration\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIforward\fP If set to \fCtrue\fP forward\&.
.RE
.PP

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowAnimation\fP\&.
.PP
Definition at line 120 of file WindowComponentBase\&.cs\&.
.SS "\fBWindowObjectState\fP UnityEngine\&.UI\&.Windows\&.WindowComponentBase\&.GetComponentState ()"

.PP
Gets the state of the component\&. 
.PP
\fBReturns:\fP
.RS 4
The component state\&.
.RE
.PP

.PP
Definition at line 26 of file WindowComponentBase\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.WindowComponentBase\&.Hide ()"

.PP
Hide this instance\&. Animation component can use current layout element root or current component root\&. 
.PP
Definition at line 59 of file WindowComponentBase\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.WindowComponentBase\&.Hide (bool immediately)"

.PP
Hide the specified immediately\&. Animation component can use current layout element root or current component root\&. 
.PP
\fBParameters:\fP
.RS 4
\fIimmediately\fP If set to \fCtrue\fP immediately\&.
.RE
.PP

.PP
Definition at line 70 of file WindowComponentBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowComponentBase\&.Hide (System\&.Action callback, bool immediately)\fC [virtual]\fP"

.PP
Hide the specified callback and immediately\&. Animation component can use current layout element root or current component root\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcallback\fP Callback\&.
.br
\fIimmediately\fP If set to \fCtrue\fP immediately\&.
.RE
.PP

.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.WindowLayoutBase\fP\&.
.PP
Definition at line 82 of file WindowComponentBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowComponentBase\&.OnDeinit ()\fC [virtual]\fP"

.PP
Raises the deinit event\&. You can override this method but call it's base\&. 
.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Components\&.Tabs\fP, \fBUnityEngine\&.UI\&.Windows\&.WindowComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.LinkerComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.InputFieldComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonHoverComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonWithTipComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Modules\&.BackgroundCloseable\fP\&.
.PP
Definition at line 240 of file WindowComponentBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowComponentBase\&.OnHideBegin (System\&.Action callback)\fC [virtual]\fP"

.PP
Raises the hide begin event\&. Wait while all sub components return the callback\&. You can override this method but call it's base\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcallback\fP Callback\&.
.RE
.PP

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Components\&.List\fP, \fBUnityEngine\&.UI\&.Windows\&.WindowComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.LinkerComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.ProgressWithParticlesComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.ProgressComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonHoverComponent\fP\&.
.PP
Definition at line 181 of file WindowComponentBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowComponentBase\&.OnHideEnd ()\fC [virtual]\fP"

.PP
Raises the hide end event\&. You can override this method but call it's base\&. 
.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.WindowComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.LinkerComponent\fP\&.
.PP
Definition at line 256 of file WindowComponentBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowComponentBase\&.OnInit ()\fC [virtual]\fP"

.PP
Raises the init event\&. You can override this method but call it's base\&. 
.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.WindowComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.LinkerComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.ProgressComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.List\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.Tabs\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.ToggleComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonWithTipComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.ProgressWithParticlesComponent\fP\&.
.PP
Definition at line 230 of file WindowComponentBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowComponentBase\&.OnShowBegin (System\&.Action callback)\fC [virtual]\fP"

.PP
Raises the show begin event\&. Wait while all sub components return the callback\&. You can override this method but call it's base\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcallback\fP Callback\&.
.RE
.PP

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.WindowComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.PopupComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.LinkerComponent\fP\&.
.PP
Definition at line 138 of file WindowComponentBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowComponentBase\&.OnShowEnd ()\fC [virtual]\fP"

.PP
Raises the show end event\&. You can override this method but call it's base\&. 
.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.WindowComponent\fP, \fBUnityEngine\&.UI\&.Windows\&.Components\&.LinkerComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.ProgressWithParticlesComponent\fP\&.
.PP
Definition at line 250 of file WindowComponentBase\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.WindowComponentBase\&.SetInState ()"

.PP
Set up \fCin\fP state to animation\&. 
.PP
Definition at line 100 of file WindowComponentBase\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.WindowComponentBase\&.SetOutState ()"

.PP
Set up \fCout\fP state to animation\&. 
.PP
Definition at line 109 of file WindowComponentBase\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.WindowComponentBase\&.SetResetState ()"

.PP
Set up \fCreset\fP state to animation\&. 
.PP
Definition at line 91 of file WindowComponentBase\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.WindowComponentBase\&.Show (bool resetAnimation = \fCtrue\fP)"

.PP
Show component\&. Animation component can use current layout element root or current component root\&. 
.PP
\fBParameters:\fP
.RS 4
\fIresetAnimation\fP If set to \fCtrue\fP reset animation\&.
.RE
.PP

.PP
Definition at line 37 of file WindowComponentBase\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.WindowComponentBase\&.Show (System\&.Action callback, bool resetAnimation)\fC [virtual]\fP"

.PP
Show component with callback after end\&. Animation component can use current layout element root or current component root\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcallback\fP Callback\&.
.br
\fIresetAnimation\fP If set to \fCtrue\fP reset animation\&.
.RE
.PP

.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.WindowLayoutBase\fP\&.
.PP
Definition at line 49 of file WindowComponentBase\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "new \fBWindowAnimationBase\fP UnityEngine\&.UI\&.Windows\&.WindowComponentBase\&.animation"

.PP
Definition at line 12 of file WindowComponentBase\&.cs\&.
.SS "List<\fBTransitionInputParameters\fP> UnityEngine\&.UI\&.Windows\&.WindowComponentBase\&.animationInputParams = new List<\fBTransitionInputParameters\fP>()"

.PP
Definition at line 14 of file WindowComponentBase\&.cs\&.
.SS "bool UnityEngine\&.UI\&.Windows\&.WindowComponentBase\&.animationRefresh = false"

.PP
Definition at line 18 of file WindowComponentBase\&.cs\&.
.SS "CanvasGroup UnityEngine\&.UI\&.Windows\&.WindowComponentBase\&.canvas"

.PP
Definition at line 16 of file WindowComponentBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
