.TH "UnityEngine.UI.Windows.WindowSystemFlow" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.WindowSystemFlow \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.WindowSystem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFlowData\fP \fBflow\fP"
.br
.ti -1c
.RI "bool \fBshowRootOnStart\fP = true"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.RI "\fIInit this instance\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 11 of file WindowSystemFlow\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void UnityEngine\&.UI\&.Windows\&.WindowSystemFlow\&.Init ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Init this instance\&. 
.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowSystem\fP\&.
.PP
Definition at line 24 of file WindowSystemFlow\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.WindowSystemFlow\&.Start ()"

.PP
Definition at line 42 of file WindowSystemFlow\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFlowData\fP UnityEngine\&.UI\&.Windows\&.WindowSystemFlow\&.flow"

.PP
Definition at line 13 of file WindowSystemFlow\&.cs\&.
.SS "bool UnityEngine\&.UI\&.Windows\&.WindowSystemFlow\&.showRootOnStart = true"

.PP
Definition at line 22 of file WindowSystemFlow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
