.TH "UnityEngine.UI.Windows.WindowObject" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.WindowObject \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBUnityEngine\&.UI\&.Windows\&.WindowBase\fP, \fBUnityEngine\&.UI\&.Windows\&.WindowComponentBase\fP, and \fBUnityEngine\&.UI\&.Windows\&.WindowLayout\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindowBase\fP \fBGetWindow\fP ()"
.br
.ti -1c
.RI "void \fBHideCurrentWindow\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file WindowObject\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBWindowBase\fP UnityEngine\&.UI\&.Windows\&.WindowObject\&.GetWindow ()"

.PP
Definition at line 17 of file WindowObject\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.WindowObject\&.HideCurrentWindow ()"

.PP
Definition at line 23 of file WindowObject\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
