.TH "UnityEngine.UI.Windows.IWindowComponentLayout" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.IWindowComponentLayout \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.IWindowEventsAsync\fP\&.
.PP
Inherited by \fBUnityEngine\&.UI\&.Windows\&.WindowLayoutBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetup\fP (\fBWindowComponent\fP component, \fBLayout\&.Component\fP activatorInstance)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file IWindowComponent\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.UI\&.Windows\&.IWindowComponentLayout\&.Setup (\fBWindowComponent\fP component, \fBLayout\&.Component\fP activatorInstance)"

.PP
Implemented in \fBUnityEngine\&.UI\&.Windows\&.WindowLayoutBase\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
