.TH "UnityEngine.UI.Windows.Extensions.ScrollRect" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Extensions.ScrollRect \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScrollRect\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdateDropdown\fP ()"
.br
.ti -1c
.RI "void \fBSetupAsDropdown\fP (float maxHeight)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LayoutElement \fBlayoutElement\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBStart\fP ()"
.br
.ti -1c
.RI "override void \fBLateUpdate\fP ()"
.br
.ti -1c
.RI "void \fBUpdateScrollBars\fP ()"
.br
.ti -1c
.RI "override void \fBOnRectTransformDimensionsChange\fP ()"
.br
.ti -1c
.RI "override void \fBOnTransformParentChanged\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file ScrollRect\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void UnityEngine\&.UI\&.Windows\&.Extensions\&.ScrollRect\&.LateUpdate ()\fC [protected]\fP"

.PP
Definition at line 29 of file ScrollRect\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Extensions\&.ScrollRect\&.OnRectTransformDimensionsChange ()\fC [protected]\fP"

.PP
Definition at line 52 of file ScrollRect\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Extensions\&.ScrollRect\&.OnTransformParentChanged ()\fC [protected]\fP"

.PP
Definition at line 60 of file ScrollRect\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Extensions\&.ScrollRect\&.SetupAsDropdown (float maxHeight)"

.PP
Definition at line 99 of file ScrollRect\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Extensions\&.ScrollRect\&.Start ()\fC [protected]\fP"

.PP
Definition at line 18 of file ScrollRect\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Extensions\&.ScrollRect\&.UpdateDropdown ()"

.PP
Definition at line 68 of file ScrollRect\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Extensions\&.ScrollRect\&.UpdateScrollBars ()\fC [protected]\fP"

.PP
Definition at line 42 of file ScrollRect\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "LayoutElement UnityEngine\&.UI\&.Windows\&.Extensions\&.ScrollRect\&.layoutElement"

.PP
Definition at line 10 of file ScrollRect\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
