.TH "UnityEditor.UI.Windows.WindowLayoutElementEditor" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.WindowLayoutElementEditor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Editor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "void \fBOnSceneView\fP (SceneView view)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file WindowLayoutElementEditor\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.UI\&.Windows\&.WindowLayoutElementEditor\&.OnDisable ()"

.PP
Definition at line 34 of file WindowLayoutElementEditor\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.WindowLayoutElementEditor\&.OnEnable ()"

.PP
Definition at line 16 of file WindowLayoutElementEditor\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.WindowLayoutElementEditor\&.OnSceneView (SceneView view)"

.PP
Definition at line 41 of file WindowLayoutElementEditor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
