.TH "UnityEngine.UI.Windows.Plugins.FlowCompiler.Tpl.Info" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Plugins.FlowCompiler.Tpl.Info \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInfo\fP (\fBFlowWindow\fP window)"
.br
.ti -1c
.RI "\fBInfo\fP (string \fBbaseNamespace\fP, string \fBclassname\fP, string \fBbaseClassname\fP, string \fBscreenName\fP)"
.br
.ti -1c
.RI "string \fBReplace\fP (string replace, System\&.Func< string, string > predicate=null)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBbaseNamespace\fP"
.br
.ti -1c
.RI "string \fBclassname\fP"
.br
.ti -1c
.RI "string \fBbaseClassname\fP"
.br
.ti -1c
.RI "string \fBscreenName\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBclassnameFile\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBbaseClassnameFile\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBclassnameWithNamespace\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file FlowCompilerSystem\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEngine\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.Tpl\&.Info\&.Info (\fBFlowWindow\fP window)"

.PP
Definition at line 53 of file FlowCompilerSystem\&.cs\&.
.SS "UnityEngine\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.Tpl\&.Info\&.Info (string baseNamespace, string classname, string baseClassname, string screenName)"

.PP
Definition at line 62 of file FlowCompilerSystem\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "string UnityEngine\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.Tpl\&.Info\&.Replace (string replace, System\&.Func< string, string > predicate = \fCnull\fP)"

.PP
Definition at line 71 of file FlowCompilerSystem\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string UnityEngine\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.Tpl\&.Info\&.baseClassname"

.PP
Definition at line 20 of file FlowCompilerSystem\&.cs\&.
.SS "string UnityEngine\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.Tpl\&.Info\&.baseNamespace"

.PP
Definition at line 18 of file FlowCompilerSystem\&.cs\&.
.SS "string UnityEngine\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.Tpl\&.Info\&.classname"

.PP
Definition at line 19 of file FlowCompilerSystem\&.cs\&.
.SS "string UnityEngine\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.Tpl\&.Info\&.screenName"

.PP
Definition at line 21 of file FlowCompilerSystem\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string UnityEngine\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.Tpl\&.Info\&.baseClassnameFile\fC [get]\fP"

.PP
Definition at line 33 of file FlowCompilerSystem\&.cs\&.
.SS "string UnityEngine\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.Tpl\&.Info\&.classnameFile\fC [get]\fP"

.PP
Definition at line 23 of file FlowCompilerSystem\&.cs\&.
.SS "string UnityEngine\&.UI\&.Windows\&.Plugins\&.FlowCompiler\&.Tpl\&.Info\&.classnameWithNamespace\fC [get]\fP"

.PP
Definition at line 43 of file FlowCompilerSystem\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
