.TH "UnityEditor.UI.Windows.Plugins.Flow.Editors.FlowGameViewWindow" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.UI.Windows.Plugins.Flow.Editors.FlowGameViewWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEditor\&.EditorWindowExt\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShowView\fP (\fBWindowBase\fP previewScreen, System\&.Action onClose)"
.br
.ti -1c
.RI "void \fBHideView\fP ()"
.br
.ti -1c
.RI "void \fBOnFocus\fP ()"
.br
.ti -1c
.RI "void \fBOnLostFocus\fP ()"
.br
.ti -1c
.RI "new void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBOnGUI\fP ()"
.br
.ti -1c
.RI "override void \fBOnClose\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFlowSystemEditorWindow\fP \fBrootWindow\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 135 of file FlowGameViewWindow\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowGameViewWindow\&.HideView ()"

.PP
Definition at line 218 of file FlowGameViewWindow\&.cs\&.
.SS "override void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowGameViewWindow\&.OnClose ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEditor\&.EditorWindowExt\fP\&.
.PP
Definition at line 435 of file FlowGameViewWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowGameViewWindow\&.OnFocus ()"

.PP
Definition at line 224 of file FlowGameViewWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowGameViewWindow\&.OnGUI ()"

.PP
Definition at line 279 of file FlowGameViewWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowGameViewWindow\&.OnLostFocus ()"

.PP
Definition at line 230 of file FlowGameViewWindow\&.cs\&.
.SS "void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowGameViewWindow\&.ShowView (\fBWindowBase\fP previewScreen, System\&.Action onClose)"

.PP
Definition at line 152 of file FlowGameViewWindow\&.cs\&.
.SS "new void UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowGameViewWindow\&.Update ()\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEditor\&.EditorWindowExt\fP\&.
.PP
Definition at line 236 of file FlowGameViewWindow\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFlowSystemEditorWindow\fP UnityEditor\&.UI\&.Windows\&.Plugins\&.Flow\&.Editors\&.FlowGameViewWindow\&.rootWindow"

.PP
Definition at line 137 of file FlowGameViewWindow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
