.TH "UnityEngine.UI.TextWithButton" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.TextWithButton \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Text\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Button \fBrootButton\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file TextWithButton\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Button UnityEngine\&.UI\&.TextWithButton\&.rootButton"

.PP
Definition at line 8 of file TextWithButton\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
