.TH "UnityEngine.UI.Windows.Components.ButtonComponent" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEngine.UI.Windows.Components.ButtonComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEngine\&.UI\&.Windows\&.Components\&.ColoredComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.ISelectable\fP\&.
.PP
Inherited by \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonWithImageComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetEnabledState\fP (bool state)"
.br
.ti -1c
.RI "void \fBSetDisabled\fP ()"
.br
.ti -1c
.RI "void \fBSetEnabled\fP ()"
.br
.ti -1c
.RI "void \fBSelect\fP ()"
.br
.ti -1c
.RI "void \fBDeselect\fP ()"
.br
.ti -1c
.RI "override void \fBSetColor\fP (Color color)"
.br
.ti -1c
.RI "virtual void \fBSetCallback\fP (UnityAction callback)"
.br
.ti -1c
.RI "virtual void \fBSetCallback\fP (UnityAction< \fBButtonComponent\fP > callback)"
.br
.ti -1c
.RI "override void \fBOnDeinit\fP ()"
.br
.RI "\fIRaises the deinit event\&. You can override this method but call it's base\&. \fP"
.ti -1c
.RI "void \fBOnClick\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Button \fBbutton\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 11 of file ButtonComponent\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.ButtonComponent\&.Deselect ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.Components\&.ISelectable\fP\&.
.PP
Definition at line 51 of file ButtonComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.ButtonComponent\&.OnClick ()"

.PP
Definition at line 99 of file ButtonComponent\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Components\&.ButtonComponent\&.OnDeinit ()\fC [virtual]\fP"

.PP
Raises the deinit event\&. You can override this method but call it's base\&. 
.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.WindowComponent\fP\&.
.PP
Reimplemented in \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonHoverComponent\fP, and \fBUnityEngine\&.UI\&.Windows\&.Components\&.ButtonWithTipComponent\fP\&.
.PP
Definition at line 89 of file ButtonComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.ButtonComponent\&.Select ()"

.PP
Implements \fBUnityEngine\&.UI\&.Windows\&.Components\&.ISelectable\fP\&.
.PP
Definition at line 45 of file ButtonComponent\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.Components\&.ButtonComponent\&.SetCallback (UnityAction callback)\fC [virtual]\fP"

.PP
Definition at line 69 of file ButtonComponent\&.cs\&.
.SS "virtual void UnityEngine\&.UI\&.Windows\&.Components\&.ButtonComponent\&.SetCallback (UnityAction< \fBButtonComponent\fP > callback)\fC [virtual]\fP"

.PP
Definition at line 79 of file ButtonComponent\&.cs\&.
.SS "override void UnityEngine\&.UI\&.Windows\&.Components\&.ButtonComponent\&.SetColor (Color color)\fC [virtual]\fP"

.PP
Reimplemented from \fBUnityEngine\&.UI\&.Windows\&.Components\&.ColoredComponent\fP\&.
.PP
Definition at line 57 of file ButtonComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.ButtonComponent\&.SetDisabled ()"

.PP
Definition at line 33 of file ButtonComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.ButtonComponent\&.SetEnabled ()"

.PP
Definition at line 39 of file ButtonComponent\&.cs\&.
.SS "void UnityEngine\&.UI\&.Windows\&.Components\&.ButtonComponent\&.SetEnabledState (bool state)"

.PP
Definition at line 19 of file ButtonComponent\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Button UnityEngine\&.UI\&.Windows\&.Components\&.ButtonComponent\&.button\fC [protected]\fP"

.PP
Definition at line 14 of file ButtonComponent\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
