.TH "C:/Unity3d.UI.Windows/Assets/UI.Windows/Core/WindowBase.cs" 3 "Fri Apr 3 2015" "Version version 0.8a" "Unity3D UI Windows Extension" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Unity3d.UI.Windows/Assets/UI.Windows/Core/WindowBase.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUnityEngine\&.UI\&.Windows\&.WindowBase\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBUnityEngine\&.UI\&.Windows\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBUnityEngine\&.UI\&.Windows\&.WindowObjectState\fP : byte { \fBUnityEngine\&.UI\&.Windows\&.WindowObjectState\&.NotInitialized\fP = 0, \fBUnityEngine\&.UI\&.Windows\&.WindowObjectState\&.Initializing\fP, \fBUnityEngine\&.UI\&.Windows\&.WindowObjectState\&.Initialized\fP, \fBUnityEngine\&.UI\&.Windows\&.WindowObjectState\&.Showing\fP, \fBUnityEngine\&.UI\&.Windows\&.WindowObjectState\&.Shown\fP, \fBUnityEngine\&.UI\&.Windows\&.WindowObjectState\&.Hiding\fP, \fBUnityEngine\&.UI\&.Windows\&.WindowObjectState\&.Hidden\fP }"
.br
.RI "\fIWindow or component object state\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Unity3D UI Windows Extension from the source code\&.
