//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the UI.Windows Flow Addon.
//
//     You may simply edit this file to setup your behavior.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI.Windows;

namespace ExampleProject.UI.MenuLoader {

	public class MenuLoaderScreenBase : LayoutWindowType {

		//------------------------------------------------------------------------------
		// <auto-generated>
		//     This code was generated by the UI.Windows Flow Addon.
		//
		//     You may simply edit this file to setup your behavior.
		// </auto-generated>
		//------------------------------------------------------------------------------
		public virtual ExampleProject.UI.Menu.GlobalMap.GlobalMapScreenBase FlowGlobalMap() {
			
			return WindowSystem.Show<ExampleProject.UI.Menu.GlobalMap.GlobalMapScreenBase>();
			
		}
		
	}

}