//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the UI.Windows Flow Addon.
//     You may simply edit this file to setup your behavior.
//     See more: https://github.com/chromealex/Unity3d.UI.Windows
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI.Windows;
using UnityEngine.UI.Windows.Components;
using UnityEngine.UI.Windows.Plugins.Analytics;

namespace ExampleProject.UI.Other.UserInfo {

	public class UserInfoScreen : UserInfoScreenBase {

		public override void OnInit() {

			base.OnInit();

			this.GetLayoutComponent<TextComponent>().SetText(string.Format("UserID: {0}", User.instance.id));

		}

	}

}