//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the UI.Windows Flow Addon.
//     You may simply edit this file to setup your behavior.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI.Windows;

namespace ExampleProject.UI.MainLoader {

	public class MainLoaderScreenBase : LayoutWindowType {
		
		/// <summary>
		/// Flows to the GlobalMap.
		/// Full Name: ExampleProject.UI.Menu.GlobalMap.GlobalMapScreen
		/// </summary>
		/// <returns>GlobalMap</returns>
		public virtual ExampleProject.UI.Menu.GlobalMap.GlobalMapScreen FlowGlobalMap() {
			
			return WindowSystem.Show<ExampleProject.UI.Menu.GlobalMap.GlobalMapScreen>();
			
		}
				
		/// <summary>
		/// Flows to the Background.
		/// Full Name: ExampleProject.UI.Background.BackgroundScreen
		/// </summary>
		/// <returns>Background</returns>
		public virtual ExampleProject.UI.Background.BackgroundScreen FlowBackground() {
			
			return WindowSystem.Show<ExampleProject.UI.Background.BackgroundScreen>();
			
		}
		
	}

}