//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the UI.Windows Flow Addon.
//     You may not edit this file because of it's auto-generated by FlowCompiler.
//     See more: https://github.com/chromealex/Unity3d.UI.Windows
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI.Windows;
using UnityEngine.UI.Windows.Types;

namespace ExampleProject.UI.Menu.GlobalMap {

	public class GlobalMapScreenBase : LayoutWindowType {
		
		/// <summary>
		/// Flows to the GameTypeChooser.
		/// Full Name: ExampleProject.UI.Menu.GameTypeChooser.GameTypeChooserScreen
		/// </summary>
		/// <returns>GameTypeChooser</returns>
		public virtual ExampleProject.UI.Menu.GameTypeChooser.GameTypeChooserScreen FlowGameTypeChooser(params object[] parameters) {
			
			var instance = WindowSystem.Show<ExampleProject.UI.Menu.GameTypeChooser.GameTypeChooserScreen>(parameters);
			instance.SetFunctionIterationIndex(this.GetFunctionIterationIndex());
			
			return instance;
			
		}
				
		/// <summary>
		/// Flows to the Shop.
		/// Full Name: ExampleProject.UI.Menu.ShopOperations.Shop.ShopScreen
		/// </summary>
		/// <returns>Shop</returns>
		public virtual ExampleProject.UI.Menu.ShopOperations.Shop.ShopScreen FlowShop(params object[] parameters) {
			
			var instance = WindowSystem.Show<ExampleProject.UI.Menu.ShopOperations.Shop.ShopScreen>(parameters);
			instance.SetFunctionIterationIndex(this.GetFunctionIterationIndex());
			
			return instance;
			
		}
				
		/// <summary>
		/// Request Social Module.
		/// Platform: Facebook (facebook.com)
		/// </summary>
		/// <returns>Social FB Module</returns>
		public virtual UnityEngine.UI.Windows.Plugins.Social.Modules.Impl.FB.FBModule GetSocialModule() {
			
			return UnityEngine.UI.Windows.Plugins.Social.Core.SocialSystem.instance.GetModule<UnityEngine.UI.Windows.Plugins.Social.Modules.Impl.FB.FBModule>();
			
		}
		
	}

}