//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the UI.Windows Flow Addon.
//     You may not edit this file because of it's auto-generated by FlowCompiler.
//     See more: https://github.com/chromealex/Unity3d.UI.Windows
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.UI.Windows;
using UnityEngine.UI.Windows.Types;

namespace ExampleProject.UI.Menu.GlobalMap {

	public class GlobalMapScreenBase : LayoutWindowType {
		
		/// <summary>
		/// Flows to the GameTypeChooser.
		/// Use this method to play transition effect on B window only.
		/// If you call Hide() on A window - it will hide with standard behaviour.
		/// Full Name: ExampleProject.UI.Menu.GameTypeChooser.GameTypeChooserScreen
		/// </summary>
		/// <returns>GameTypeChooser</returns>
		public virtual ExampleProject.UI.Menu.GameTypeChooser.GameTypeChooserScreen FlowGameTypeChooser(params object[] parameters) {
			
			ExampleProject.UI.Menu.GameTypeChooser.GameTypeChooserScreen instance = null;
			var item = UnityEngine.UI.Windows.Plugins.Flow.FlowSystem.GetAttachItem(1, 9);
			if (item == null || item.transition == null) {
				
				instance = WindowSystem.Show<ExampleProject.UI.Menu.GameTypeChooser.GameTypeChooserScreen>((window) => {
					
					window.SetFunctionIterationIndex(this.GetFunctionIterationIndex());
					
				}, parameters);
				
			} else {
				
				instance = WindowSystem.Show<ExampleProject.UI.Menu.GameTypeChooser.GameTypeChooserScreen>((window) => {
					
					window.SetFunctionIterationIndex(this.GetFunctionIterationIndex());
					
				}, item.transition, item.transitionParameters, parameters);
				
			}
			
			return instance;
			
		}
		
		/// <summary>
		/// Flows to the GameTypeChooser.
		/// Hides current window.
		/// Use this method to play transition effect on both windows (A and B).
		/// Full Name: ExampleProject.UI.Menu.GameTypeChooser.GameTypeChooserScreen
		/// </summary>
		/// <returns>GameTypeChooser</returns>
		public virtual ExampleProject.UI.Menu.GameTypeChooser.GameTypeChooserScreen FlowHideGameTypeChooser(params object[] parameters) {
			
			ExampleProject.UI.Menu.GameTypeChooser.GameTypeChooserScreen instance = null;
			var item = UnityEngine.UI.Windows.Plugins.Flow.FlowSystem.GetAttachItem(1, 9);
			if (item == null || item.transition == null) {
				
				this.Hide();
				instance = WindowSystem.Show<ExampleProject.UI.Menu.GameTypeChooser.GameTypeChooserScreen>((window) => {
					
					window.SetFunctionIterationIndex(this.GetFunctionIterationIndex());
					
				}, parameters);
				
			} else {
				
				this.Hide(item.transition, item.transitionParameters);
				instance = WindowSystem.Show<ExampleProject.UI.Menu.GameTypeChooser.GameTypeChooserScreen>((window) => {
					
					window.SetFunctionIterationIndex(this.GetFunctionIterationIndex());
					
				}, item.transition, item.transitionParameters, parameters);
				
			}
			
			return instance;
			
		}
				
		/// <summary>
		/// Flows to the Shop.
		/// Use this method to play transition effect on B window only.
		/// If you call Hide() on A window - it will hide with standard behaviour.
		/// Full Name: ExampleProject.UI.Menu.ShopOperations.Shop.ShopScreen
		/// </summary>
		/// <returns>Shop</returns>
		public virtual ExampleProject.UI.Menu.ShopOperations.Shop.ShopScreen FlowShop(params object[] parameters) {
			
			ExampleProject.UI.Menu.ShopOperations.Shop.ShopScreen instance = null;
			var item = UnityEngine.UI.Windows.Plugins.Flow.FlowSystem.GetAttachItem(1, 24);
			if (item == null || item.transition == null) {
				
				instance = WindowSystem.Show<ExampleProject.UI.Menu.ShopOperations.Shop.ShopScreen>((window) => {
					
					window.SetFunctionIterationIndex(this.GetFunctionIterationIndex());
					
				}, parameters);
				
			} else {
				
				instance = WindowSystem.Show<ExampleProject.UI.Menu.ShopOperations.Shop.ShopScreen>((window) => {
					
					window.SetFunctionIterationIndex(this.GetFunctionIterationIndex());
					
				}, item.transition, item.transitionParameters, parameters);
				
			}
			
			return instance;
			
		}
		
		/// <summary>
		/// Flows to the Shop.
		/// Hides current window.
		/// Use this method to play transition effect on both windows (A and B).
		/// Full Name: ExampleProject.UI.Menu.ShopOperations.Shop.ShopScreen
		/// </summary>
		/// <returns>Shop</returns>
		public virtual ExampleProject.UI.Menu.ShopOperations.Shop.ShopScreen FlowHideShop(params object[] parameters) {
			
			ExampleProject.UI.Menu.ShopOperations.Shop.ShopScreen instance = null;
			var item = UnityEngine.UI.Windows.Plugins.Flow.FlowSystem.GetAttachItem(1, 24);
			if (item == null || item.transition == null) {
				
				this.Hide();
				instance = WindowSystem.Show<ExampleProject.UI.Menu.ShopOperations.Shop.ShopScreen>((window) => {
					
					window.SetFunctionIterationIndex(this.GetFunctionIterationIndex());
					
				}, parameters);
				
			} else {
				
				this.Hide(item.transition, item.transitionParameters);
				instance = WindowSystem.Show<ExampleProject.UI.Menu.ShopOperations.Shop.ShopScreen>((window) => {
					
					window.SetFunctionIterationIndex(this.GetFunctionIterationIndex());
					
				}, item.transition, item.transitionParameters, parameters);
				
			}
			
			return instance;
			
		}
		
	}

}